# Generated by Django 6.0.3 on 2026-06-10 12:19

import django.db.models.deletion
from django.db import migrations, models

# Auth/HR/public-content collections stay global (tenant=NULL).
# Keep in sync with bridge.views.GLOBAL_COLLECTIONS.
GLOBAL_COLLECTIONS = {
    'users', 'tasks', 'attendanceSessions', 'attendanceRecords',
    'pointsHistory', 'publicGallery',
}


def backfill_tenant(apps, schema_editor):
    """Attribute all pre-existing business mirror docs to the default company
    (tenant #1) — same convention as the task10 membership backfill."""
    FirestoreMirrorDoc = apps.get_model('bridge', 'FirestoreMirrorDoc')
    Tenant = apps.get_model('tenants', 'Tenant')
    default = Tenant.objects.filter(TenantID=1).first() or Tenant.objects.order_by('TenantID').first()
    if default is None:
        return
    for doc in FirestoreMirrorDoc.objects.filter(tenant__isnull=True).iterator():
        root = doc.path.strip('/').split('/')[0]
        if root in GLOBAL_COLLECTIONS:
            continue
        doc.tenant_id = default.TenantID
        doc.save(update_fields=['tenant'])


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
        ('tenants', '0005_backfill_default_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestoremirrordoc',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirror_docs', to='tenants.tenant'),
        ),
        migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
    ]
