# Generated by Django 6.0.1 on 2026-03-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsclearance',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticsdeal',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticsexpense',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticspayment',
            name='payment_number',
            field=models.IntegerField(db_column='PaymentNumber', default=1),
        ),
        migrations.AlterField(
            model_name='logisticspayment',
            name='title',
            field=models.CharField(db_column='Title', default='Payment', max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticsshipment',
            name='shipment_number',
            field=models.CharField(db_column='ShipmentNumber', default='NEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='logisticsshipment',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
