# Generated by Django 6.0.3 on 2026-03-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_logisticsclearance_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsdeal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='logisticsdeal',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
        migrations.AddField(
            model_name='logisticspayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='logisticspayment',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
    ]
