# Generated manually to fix DB/schema drift.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0003_auto_sync_models"),
    ]

    # هذه الهجرة كُتبت يدوياً لترقيع انحراف المخطط على قاعدة الإنتاج القديمة، حيث
    # كانت هذه الأعمدة مفقودة من جدول logistics_deals. على قاعدة نظيفة ينشئها
    # 0001_initial أصلاً ⇒ تنفيذ DDL هنا يعني "Duplicate column". نُبقي أثرها على
    # الحالة فقط، وقد طُبِّق أثرها على قاعدة الإنتاج قبل هذا التعديل.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
            migrations.AddField(
                model_name="logisticsdeal",
                name="price_offer_id",
                field=models.CharField(
                    blank=True,
                    max_length=50,
                    null=True,
                    db_column="price_offer_id",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="original_offer_number",
                field=models.CharField(
                    blank=True,
                    max_length=50,
                    null=True,
                    db_column="original_offer_number",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="factory_name",
                field=models.CharField(
                    blank=True,
                    max_length=255,
                    null=True,
                    db_column="factory_name",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="supplier_invoice_number",
                field=models.CharField(
                    blank=True,
                    max_length=100,
                    null=True,
                    db_column="supplier_invoice_number",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="installment_plan_enabled",
                field=models.BooleanField(
                    default=False,
                    db_column="installment_plan_enabled",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="current_installment_number",
                field=models.IntegerField(
                    blank=True,
                    null=True,
                    db_column="current_installment_number",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="remaining_amount",
                field=models.DecimalField(
                    decimal_places=2,
                    default=0.00,
                    max_digits=18,
                    db_column="remaining_amount",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="subtotal",
                field=models.DecimalField(
                    decimal_places=2,
                    default=0.00,
                    max_digits=18,
                    db_column="subtotal",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="tax_rate",
                field=models.DecimalField(
                    decimal_places=2,
                    default=0.00,
                    max_digits=5,
                    db_column="tax_rate",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="tax_amount",
                field=models.DecimalField(
                    decimal_places=2,
                    default=0.00,
                    max_digits=18,
                    db_column="tax_amount",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="tax_type",
                field=models.CharField(
                    choices=[("percentage", "percentage"), ("amount", "amount")],
                    default="percentage",
                    max_length=20,
                    db_column="tax_type",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="warranty_duration",
                field=models.IntegerField(
                    blank=True,
                    null=True,
                    db_column="warranty_duration",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="total_weight_kg",
                field=models.DecimalField(
                    blank=True,
                    null=True,
                    decimal_places=3,
                    default=0.0,
                    max_digits=10,
                    db_column="total_weight_kg",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="shipment_notes",
                field=models.TextField(
                    blank=True,
                    null=True,
                    db_column="shipment_notes",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="first_payment_date",
                field=models.DateField(
                    blank=True,
                    null=True,
                    db_column="first_payment_date",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="payment_date",
                field=models.DateField(
                    blank=True,
                    null=True,
                    db_column="payment_date",
                ),
            ),
            migrations.AddField(
                model_name="logisticsdeal",
                name="started_production_at",
                field=models.DateField(
                    blank=True,
                    null=True,
                    db_column="started_production_at",
                ),
            ),
            ],
        ),
    ]
