# Generated manually to fix DB/schema drift.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0006_add_missing_logistics_payment_posting_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsshipment",
            name="agent_shipment_number",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                db_column="agent_shipment_number",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="israeli_side_name",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=255,
                db_column="israeli_side_name",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="shipment_name",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=255,
                db_column="shipment_name",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="pricing_method",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=50,
                choices=[("total", "total"), ("unit", "unit")],
                db_column="pricing_method",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="unit_type",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=50,
                choices=[("cbm", "cbm"), ("weight", "weight"), ("container", "container")],
                db_column="unit_type",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="price_per_unit",
            field=models.DecimalField(
                blank=True,
                null=True,
                max_digits=18,
                decimal_places=2,
                db_column="price_per_unit",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="total_shipping_cost_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                max_digits=18,
                db_column="total_shipping_cost_usd",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="total_volume",
            field=models.DecimalField(
                decimal_places=3,
                default=0.000,
                max_digits=10,
                db_column="total_volume",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="total_weight_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=0.000,
                max_digits=10,
                db_column="total_weight_kg",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="remaining_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.00,
                max_digits=18,
                db_column="remaining_amount",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="installment_plan_enabled",
            field=models.BooleanField(
                default=False,
                db_column="installment_plan_enabled",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="shipping_type",
            field=models.CharField(
                default="sea",
                max_length=20,
                choices=[("sea", "sea"), ("air", "air")],
                db_column="shipping_type",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="ship_name",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=255,
                db_column="ship_name",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="international_shipping_company",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=255,
                db_column="international_shipping_company",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="bill_of_lading_file",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=500,
                db_column="bill_of_lading_file",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="flight_number",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                db_column="flight_number",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="airway_bill_number",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                db_column="airway_bill_number",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="airway_bill_file",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=500,
                db_column="airway_bill_file",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="from_term",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                db_column="from_term",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="to_term",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                db_column="to_term",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="imo_number",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                db_column="imo_number",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="mmsi_number",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                db_column="mmsi_number",
            ),
        ),
        migrations.AddField(
            model_name="logisticsshipment",
            name="tracking_link",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=500,
                db_column="tracking_link",
            ),
        ),
    ]

