# Generated by Django 6.0.3 on 2026-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_add_missing_logistics_shipment_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsdeal',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, db_column='total_weight_kg', decimal_places=3, max_digits=10, null=True),
        ),
    ]
