# Generated by Django 6.0.3 on 2026-04-11 19:20

import django.db.models.deletion
import logistics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_purchase_invoices'),
        ('inventory', '0001_stock_movements_and_product_qty'),
        ('logistics', '0015_logisticspayment_unique_deal_payment_number'),
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(db_column='PurchaseInvoiceID', primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_column='InvoiceNumber', max_length=50)),
                ('invoice_name', models.CharField(blank=True, db_column='InvoiceName', max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, db_column='InvoiceDate', null=True)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=18)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(db_column='DiscountAmount', decimal_places=2, default=0, max_digits=18)),
                ('tax_rate', models.DecimalField(db_column='TaxRate', decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, default=0, max_digits=18)),
                ('tax_type', models.CharField(choices=[('percentage', 'نسبة'), ('amount', 'مبلغ ثابت')], db_column='TaxType', default='percentage', max_length=20)),
                ('shipping_cost', models.DecimalField(db_column='ShippingCost', decimal_places=2, default=0, max_digits=18)),
                ('shipping_included', models.BooleanField(db_column='ShippingIncluded', default=False)),
                ('grand_total', models.DecimalField(db_column='GrandTotal', decimal_places=2, default=0, max_digits=18)),
                ('local_payments_json', models.JSONField(blank=True, db_column='LocalPaymentsJSON', null=True)),
                ('conversion_metadata_json', models.JSONField(blank=True, db_column='ConversionMetadataJSON', null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('incomplete', 'غير مكتملة'), ('completed', 'مكتملة'), ('deposit_paid', 'دفعة أولى'), ('partially_paid', 'مدفوعة جزئياً'), ('fully_paid', 'مدفوعة بالكامل'), ('archived', 'مؤرشفة')], db_column='Status', default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('supplier_invoice_number', models.CharField(blank=True, db_column='SupplierInvoiceNumber', max_length=100, null=True)),
                ('factory_name', models.CharField(blank=True, db_column='FactoryName', max_length=255, null=True)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('firestore_id', models.CharField(blank=True, db_column='FirestoreID', help_text='Legacy link to Firestore document id', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'purchase_invoices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.AutoField(db_column='InvoiceItemID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('total_price', models.DecimalField(db_column='TotalPrice', decimal_places=2, max_digits=18)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('hs_code', models.CharField(blank=True, db_column='HSCode', max_length=20, null=True)),
                ('landed_unit_price_ils', models.DecimalField(blank=True, db_column='LandedUnitPriceILS', decimal_places=4, max_digits=18, null=True)),
                ('landed_line_total_ils', models.DecimalField(blank=True, db_column='LandedLineTotalILS', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'purchase_invoice_items',
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='logisticspayment',
            name='unique_active_deal_payment_number',
        ),
        migrations.RenameIndex(
            model_name='logisticsclearancepayment',
            new_name='logistics_c_Clearan_d77196_idx',
            old_name='logistics_l_clearan_4d1c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='logisticsclearancepayment',
            new_name='logistics_c_TenantI_5e50c9_idx',
            old_name='logistics_l_tenant__24c8f5_idx',
        ),
        migrations.AlterField(
            model_name='logisticsclearance',
            name='cost_lines',
            field=models.JSONField(blank=True, db_column='cost_lines', default=logistics.models.default_clearance_cost_lines),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.ForeignKey(db_column='CurrencyID', default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='deal',
            field=models.ForeignKey(blank=True, db_column='DealID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='logistics.logisticsdeal'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='journal',
            field=models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='accounting.journalheader'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='partner',
            field=models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='ShipmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='logistics.logisticsshipment'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='invoice',
            field=models.ForeignKey(db_column='PurchaseInvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['tenant', 'invoice_number'], name='purchase_in_TenantI_788041_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['partner'], name='purchase_in_Partner_270f71_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['deal'], name='purchase_in_DealID_bc89e9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['status'], name='purchase_in_Status_def733_idx'),
        ),
    ]
