# Generated by Django 6.0.3 on 2026-04-11 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_purchase_invoices'),
        ('logistics', '0016_purchase_invoices'),
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsshipment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False),
        ),
        migrations.AlterField(
            model_name='logisticsshipment',
            name='shipment_number',
            field=models.CharField(db_column='ShipmentNumber', default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='logisticsdeal',
            constraint=models.UniqueConstraint(fields=('tenant', 'ref_number'), name='unique_tenant_deal_ref'),
        ),
    ]
