# Generated by Django 6.0.3 on 2026-04-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_phase5_cleanup_shipment_softdelete_deal_unique'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsclearancepayment',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='CurrencyID_ClearancePay', help_text='Payment amount currency; null = ILS (legacy)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clearance_payments', to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='logisticsshipmentdeal',
            name='allocated_shipping_cost',
            field=models.DecimalField(db_column='AllocatedShippingCostUSD', decimal_places=2, default=0.0, help_text='Share of international shipping (USD) allocated to this deal on the shipment', max_digits=18),
        ),
        migrations.AddField(
            model_name='logisticsshipmentdeal',
            name='extra_costs',
            field=models.DecimalField(db_column='ExtraCostsUSD', decimal_places=2, default=0.0, help_text='Additional shipment-side costs allocated to this deal (USD)', max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='clearance',
            field=models.ForeignKey(blank=True, db_column='ClearanceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='logistics.logisticsclearance'),
        ),
    ]
