# Generated by Django 6.0.3 on 2026-04-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_seed_import_accounts_and_fix_vat'),
        ('logistics', '0021_purchase_invoice_payment_type'),
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalShipment',
            fields=[
                ('id', models.AutoField(db_column='LocalShipmentID', primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(db_column='ShipmentNumber', default='', help_text='يولَّد تلقائياً LS-XXXX', max_length=50)),
                ('driver_name', models.CharField(blank=True, db_column='DriverName', help_text='اسم السائق (اختياري)', max_length=150, null=True)),
                ('vehicle_number', models.CharField(blank=True, db_column='VehicleNumber', help_text='رقم المركبة / الشاحنة', max_length=50, null=True)),
                ('origin', models.CharField(blank=True, db_column='Origin', help_text='نقطة الانطلاق (مخزن التخليص، الميناء، ...)', max_length=255, null=True)),
                ('destination', models.CharField(blank=True, db_column='Destination', help_text='الوجهة (المستودع، عنوان العميل)', max_length=255, null=True)),
                ('pickup_date', models.DateField(blank=True, db_column='PickupDate', null=True)),
                ('delivery_date', models.DateField(blank=True, db_column='DeliveryDate', null=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, default=0, help_text='قيمة الشحن المتفق عليها', max_digits=18)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1, max_digits=18)),
                ('payment_type', models.CharField(choices=[('credit', 'آجل'), ('cash', 'نقدي')], db_column='PaymentType', default='credit', max_length=10)),
                ('capitalize_to_inventory', models.BooleanField(db_column='CapitalizeToInventory', default=True, help_text='إن True يُضاف لتكلفة Landed Cost بدل أن يُسجَّل كمصروف فترة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغية')], db_column='Status', default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('carrier', models.ForeignKey(db_column='CarrierID', help_text='الناقل المحلي (شركة النقل أو السائق)', on_delete=django.db.models.deletion.PROTECT, related_name='local_shipments', to='partners.partner')),
                ('cash_or_bank_account', models.ForeignKey(blank=True, db_column='CashOrBankAccountID', help_text='الصندوق أو البنك (في الدفع النقدي)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_shipment_cash_payments', to='accounting.account')),
                ('clearance', models.ForeignKey(blank=True, db_column='ClearanceID', help_text='التخليص الجمركي المصدر — اختياري إن كانت البضاعة خارج دورة الاستيراد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_shipments', to='logistics.logisticsclearance')),
                ('currency', models.ForeignKey(db_column='CurrencyID', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='local_shipments', to='tenants.currency')),
                ('expense_account', models.ForeignKey(blank=True, db_column='ExpenseAccountID', help_text='حساب مصروف الشحن (مثلاً 5301 أو 5310 شحن محلي)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_shipment_expenses', to='accounting.account')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_shipments', to='accounting.journalheader')),
                ('purchase_invoice', models.ForeignKey(blank=True, db_column='PurchaseInvoiceID', help_text='الفاتورة التي نُقلت تكلفتها إليها (عند الاستيراد)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_shipments', to='logistics.purchaseinvoice')),
                ('shipment', models.ForeignKey(blank=True, db_column='InternationalShipmentID', help_text='الشحنة الدولية المرتبطة — يُملأ من التخليص تلقائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_shipments', to='logistics.logisticsshipment')),
                ('tenant', models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'logistics_local_shipments',
                'managed': True,
                'indexes': [models.Index(fields=['tenant', 'status'], name='logistics_l_TenantI_a53bdb_idx'), models.Index(fields=['carrier'], name='logistics_l_Carrier_ed836e_idx'), models.Index(fields=['clearance'], name='logistics_l_Clearan_822978_idx')],
            },
        ),
    ]
