# Generated by Django 6.0.3 on 2026-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_localshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsdeal',
            name='short_name',
            field=models.CharField(blank=True, db_column='short_name', default='', max_length=120),
        ),
    ]
