# Generated by Django 6.0.3 on 2026-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_t4_04_migrate_local_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsshipment',
            name='book_number',
            field=models.PositiveIntegerField(db_column='BookNumber', default=0, help_text='رقم الدفتر. 0 = يدوي. >0 = مسلسل لكل دفتر مستقل.'),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='licensed_dealer_no',
            field=models.CharField(blank=True, db_column='LicensedDealerNo', default='', help_text='رقم المشتغل المرخص للمورد/المستورد', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='second_date',
            field=models.DateField(blank=True, db_column='SecondDate', help_text='تاريخ ثاني لحركة الإرسالية', null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='shipment_type',
            field=models.CharField(choices=[('invoice', 'إرسالية فاتورة'), ('transport', 'إرسالية نقل')], db_column='ShipmentType', default='invoice', help_text='نوع الإرسالية (فاتورة → قابلة للتحويل لفاتورة شراء، أو نقل فقط)', max_length=20),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='supplier_address',
            field=models.CharField(blank=True, db_column='SupplierAddress', default='', help_text='عنوان المورد/المستورد (نصّي حر، لا يتعارض مع شريك)', max_length=500),
        ),
    ]
