# Generated by Django 6.0.3 on 2026-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_aseel_shipment_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsclearance',
            name='book_number',
            field=models.PositiveIntegerField(db_column='BookNumber', default=0, help_text='رقم الدفتر. 0 = يدوي. >0 = مسلسل لكل دفتر مستقل.'),
        ),
        migrations.AddField(
            model_name='logisticsdeal',
            name='book_number',
            field=models.PositiveIntegerField(db_column='BookNumber', default=0, help_text='رقم الدفتر. 0 = يدوي. >0 = مسلسل لكل دفتر مستقل.'),
        ),
    ]
