# Generated by Django 6.0.3 on 2026-05-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_n8_t5_add_book_number_deal_clearance'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localshipment',
            name='currency',
            field=models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='local_shipments', to='tenants.currency'),
        ),
        migrations.AlterField(
            model_name='localshipment',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticsclearance',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticsclearancepayment',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticsdeal',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticsexpense',
            name='currency',
            field=models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency'),
        ),
        migrations.AlterField(
            model_name='logisticsexpense',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='logisticsshipment',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoicefee',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
