# Generated by Django 6.0.3 on 2026-05-24 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_n8_t14_cheque_movement'),
        ('logistics', '0027_alter_localshipment_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsClearanceLine',
            fields=[
                ('id', models.AutoField(db_column='LineID', primary_key=True, serialize=False)),
                ('seq', models.PositiveSmallIntegerField(db_column='Seq', help_text='ترتيب البند')),
                ('line_type', models.CharField(choices=[('vat', 'ضريبة القيمة المضافة'), ('declaration_fee', 'رسوم البيان الجمركي'), ('terminal', 'محطة الشحن'), ('permits', 'معالجة التصاريح'), ('broker_commission', 'عمولة المخلص'), ('customs_system', 'نظام الجمارك «الجيل الجديد»'), ('other', 'أخرى')], db_column='LineType', default='other', max_length=32)),
                ('description', models.CharField(db_column='Description', max_length=255)),
                ('debit', models.DecimalField(db_column='Debit', decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(db_column='Credit', decimal_places=2, default=0, max_digits=18)),
                ('vat_percent', models.DecimalField(db_column='VATPercent', decimal_places=2, default=0, max_digits=5)),
                ('account', models.ForeignKey(blank=True, db_column='AccountID', help_text='الحساب المحاسبي', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('clearance', models.ForeignKey(db_column='ClearanceID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.logisticsclearance')),
                ('cost_center', models.ForeignKey(blank=True, db_column='CostCenterID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
            ],
            options={
                'db_table': 'logistics_clearance_lines',
                'ordering': ['seq'],
                'managed': True,
            },
        ),
    ]
