# Generated by Django 6.0.3 on 2026-05-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0029_backfill_clearance_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsclearance',
            name='cost_lines',
        ),
    ]
