# Generated by Django 6.0.3 on 2026-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0030_drop_cost_lines_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsclearancepayment',
            name='payment_purpose',
            field=models.CharField(choices=[('clearance_fee', 'رسوم تخليص'), ('shipping', 'شحن'), ('broker_fee', 'عمولة مخلص'), ('customs', 'رسوم جمركية'), ('vat', 'ضريبة'), ('other', 'أخرى')], db_column='PaymentPurpose', default='other', help_text='الغرض من الدفعة (رسوم تخليص، شحن، عمولة مخلص، ...)', max_length=32),
        ),
    ]
