# Generated by Django 6.0.3 on 2026-05-24 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_n8_t14_cheque_movement'),
        ('logistics', '0032_backfill_payment_purpose'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoicePayment',
            fields=[
                ('id', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1, max_digits=18)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('credit', 'آجل'), ('other', 'أخرى')], db_column='PaymentMethod', default='bank_transfer', max_length=32)),
                ('reference_number', models.CharField(blank=True, db_column='ReferenceNumber', default='', max_length=100)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('notes', models.TextField(blank=True, db_column='Notes', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('cash_or_bank_account', models.ForeignKey(db_column='CashBankAccountID', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_payments', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('invoice', models.ForeignKey(db_column='PurchaseInvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.purchaseinvoice')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalheader')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_invoice_payments',
                'ordering': ['-payment_date', '-id'],
                'managed': True,
            },
        ),
    ]
