# Generated by Django 6.0.3 on 2026-05-24 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0034_backfill_pi_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='conversion_metadata_json',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='local_payments_json',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='converted_at',
            field=models.DateTimeField(blank=True, db_column='ConvertedAt', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='converted_by',
            field=models.ForeignKey(blank=True, db_column='ConvertedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_purchase_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='converted_from_shipment',
            field=models.ForeignKey(blank=True, db_column='ConvertedFromShipmentID', help_text='الشحنة التي حوّلت إلى هذه الفاتورة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_invoices', to='logistics.logisticsshipment'),
        ),
    ]
