# Generated by Django 6.0.3 on 2026-05-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0035_drop_pi_json_fields'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsdealitem',
            name='batch_number',
            field=models.CharField(blank=True, db_column='BatchNumber', default='', help_text='رقم الدفعة', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='catalog_number',
            field=models.CharField(blank=True, db_column='CatalogNumber', default='', help_text='رقم الكتالوج', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='description_line',
            field=models.CharField(blank=True, db_column='DescriptionLine', default='', help_text='بيان السطر قابل للتعديل', max_length=500),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, db_column='DiscountAmount', decimal_places=2, help_text='قيمة الخصم على البند', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='discount_percent',
            field=models.DecimalField(blank=True, db_column='DiscountPercent', decimal_places=2, help_text='نسبة الخصم على البند', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='expiry_date',
            field=models.DateField(blank=True, db_column='ExpiryDate', help_text='تاريخ انتهاء الصلاحية', null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='extra_qty',
            field=models.DecimalField(blank=True, db_column='ExtraQty', decimal_places=4, help_text='الكمية الإضافية', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='is_taxable',
            field=models.BooleanField(db_column='IsTaxable', default=True, help_text='يخضع للضريبة'),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='line_currency',
            field=models.ForeignKey(blank=True, db_column='LineCurrencyID', help_text='عملة سعر البند', null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='line_exchange_rate',
            field=models.DecimalField(blank=True, db_column='LineExchangeRate', decimal_places=6, help_text='سعر صرف عملة البند', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='manufacture_number',
            field=models.CharField(blank=True, db_column='ManufactureNumber', default='', help_text='رقم التصنيع', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='name_snapshot',
            field=models.CharField(blank=True, db_column='NameSnapshot', default='', help_text='لقطة اسم المنتج وقت الإدخال', max_length=255),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='second_date',
            field=models.DateField(blank=True, db_column='SecondDate', help_text='تاريخ ثاني للبند', null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='seq',
            field=models.PositiveSmallIntegerField(blank=True, db_column='Seq', help_text='مسلسل البند', null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='serial_number',
            field=models.CharField(blank=True, db_column='SerialNumber', default='', help_text='الرقم المسلسل', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', default='', help_text='وحدة القياس (نص حر)', max_length=50),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='vat_percent',
            field=models.DecimalField(blank=True, db_column='VATPercent', decimal_places=2, help_text='نسبة الضريبة على البند', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='logisticsdealitem',
            name='warehouse',
            field=models.CharField(blank=True, db_column='Warehouse', default='', help_text='المخزن', max_length=100),
        ),
    ]
