# Generated by Django 6.0.3 on 2026-05-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0036_deal_item_enrichment'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='batch_number',
            field=models.CharField(blank=True, db_column='BatchNumber', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='catalog_number',
            field=models.CharField(blank=True, db_column='CatalogNumber', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='description_line',
            field=models.CharField(blank=True, db_column='DescriptionLine', default='', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, db_column='DiscountAmount', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='discount_percent',
            field=models.DecimalField(blank=True, db_column='DiscountPercent', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, db_column='ExpiryDate', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='extra_qty',
            field=models.DecimalField(blank=True, db_column='ExtraQty', decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='is_taxable',
            field=models.BooleanField(db_column='IsTaxable', default=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='line_currency',
            field=models.ForeignKey(blank=True, db_column='LineCurrencyID', null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='line_exchange_rate',
            field=models.DecimalField(blank=True, db_column='LineExchangeRate', decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='manufacture_number',
            field=models.CharField(blank=True, db_column='ManufactureNumber', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='name_snapshot',
            field=models.CharField(blank=True, db_column='NameSnapshot', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='second_date',
            field=models.DateField(blank=True, db_column='SecondDate', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='seq',
            field=models.PositiveSmallIntegerField(blank=True, db_column='Seq', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='serial_number',
            field=models.CharField(blank=True, db_column='SerialNumber', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='vat_percent',
            field=models.DecimalField(blank=True, db_column='VATPercent', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='warehouse',
            field=models.CharField(blank=True, db_column='Warehouse', default='', max_length=100),
        ),
    ]
