# Generated by Django 6.0.3 on 2026-05-24 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_n8_t14_cheque_movement'),
        ('logistics', '0038_backfill_line_fields'),
        ('sales', '0014_n8_t13_vat_statement'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsclearance',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='CurrencyID', help_text='عملة البيان', null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='editable',
            field=models.BooleanField(db_column='Editable', default=True, help_text='قابل للتعديل'),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='exchange_rate',
            field=models.DecimalField(blank=True, db_column='ExchangeRate', decimal_places=6, help_text='سعر الصرف', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='grand_total',
            field=models.DecimalField(blank=True, db_column='GrandTotal', decimal_places=2, help_text='مبلغ البيان الإجمالي', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='journal',
            field=models.ForeignKey(blank=True, db_column='JournalID', help_text='رقم القيد المباشر', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances', to='accounting.journalheader'),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='licensed_dealer_no',
            field=models.CharField(blank=True, db_column='LicensedDealerNo', default='', help_text='رقم المشتغل المرخص للمخلّص', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='second_date',
            field=models.DateField(blank=True, db_column='SecondDate', help_text='تاريخ ثاني', null=True),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='settlement_invoice_number',
            field=models.CharField(blank=True, db_column='SettlementInvoiceNumber', default='', help_text='رقم فاتورة المقاصة', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='subtotal_no_vat',
            field=models.DecimalField(blank=True, db_column='SubtotalNoVAT', decimal_places=2, help_text='المجموع بدون ضريبة', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='transaction_time',
            field=models.TimeField(blank=True, db_column='TransactionTime', help_text='ساعة التخليص', null=True),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='vat_statement',
            field=models.ForeignKey(blank=True, db_column='VatStatementID', help_text='كشف الضريبة', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.vatstatement'),
        ),
        migrations.AddField(
            model_name='logisticsclearance',
            name='vat_total',
            field=models.DecimalField(blank=True, db_column='VATTotal', decimal_places=2, help_text='مجموع الضريبة', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsdeal',
            name='editable',
            field=models.BooleanField(db_column='Editable', default=True, help_text='قابل للتعديل'),
        ),
        migrations.AddField(
            model_name='logisticsdeal',
            name='licensed_dealer_no',
            field=models.CharField(blank=True, db_column='LicensedDealerNo', default='', help_text='رقم المشتغل المرخص للمورد', max_length=100),
        ),
        migrations.AddField(
            model_name='logisticsdeal',
            name='second_date',
            field=models.DateField(blank=True, db_column='SecondDate', help_text='تاريخ ثاني للصفقة', null=True),
        ),
        migrations.AddField(
            model_name='logisticsdeal',
            name='transaction_time',
            field=models.TimeField(blank=True, db_column='TransactionTime', help_text='ساعة الصفقة', null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='editable',
            field=models.BooleanField(db_column='Editable', default=True, help_text='قابل للتعديل'),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='grand_total',
            field=models.DecimalField(blank=True, db_column='GrandTotal', decimal_places=2, help_text='إجمالي الإرسالية', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='journal_no_display',
            field=models.CharField(blank=True, db_column='JournalNoDisplay', default='', help_text='رقم القيد للعرض (read-only computed)', max_length=50),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='subtotal',
            field=models.DecimalField(blank=True, db_column='Subtotal', decimal_places=2, help_text='المجموع بدون شحن', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='transaction_time',
            field=models.TimeField(blank=True, db_column='TransactionTime', help_text='ساعة الإرسالية', null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='transit_journal',
            field=models.ForeignKey(blank=True, db_column='TransitJournalID', help_text='رقم القيد الناشئ من ترحيل الإرسالية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_shipments', to='accounting.journalheader'),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='vat_statement',
            field=models.ForeignKey(blank=True, db_column='VatStatementID', help_text='كشف الضريبة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='sales.vatstatement'),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='vat_total',
            field=models.DecimalField(blank=True, db_column='VATTotal', decimal_places=2, help_text='مجموع الضريبة', max_digits=18, null=True),
        ),
    ]
