# Generated by Django 6.0.3 on 2026-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0040_pf4_backfill_deal_status_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='attached_cash_amount',
            field=models.DecimalField(db_column='AttachedCashAmount', decimal_places=2, default=0, help_text='مبلغ نقدي مرفق عبر السند المالي (P-H-1)', max_digits=18),
        ),
    ]
