# Generated by Django 6.0.3 on 2026-05-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0041_purchaseinvoice_attached_cash_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='firestore_id',
        ),
    ]
