# Generated by Django 6.0.3 on 2026-06-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0042_remove_purchaseinvoice_firestore_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='receipt_status',
            field=models.CharField(choices=[('not_received', 'غير مستلمة'), ('partially_received', 'مستلمة جزئياً'), ('received', 'مستلمة')], db_column='ReceiptStatus', default='not_received', help_text='هل انعكست بنود الفاتورة على المخزن؟', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='received_quantity',
            field=models.DecimalField(db_column='ReceivedQuantity', decimal_places=4, default=0, help_text='الكمية المستلمة فعلياً للمخزن من هذا البند', max_digits=18),
        ),
    ]
