# Generated by Django 6.0.3 on 2026-06-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_cheque_status'),
        ('logistics', '0043_purchaseinvoice_receipt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='expense_account',
            field=models.ForeignKey(blank=True, db_column='ExpenseAccountID', help_text='حساب المصروف المخصص لهذا البند (إن وُجد) — يتخطى حساب المخزون الافتراضي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_item_expenses', to='accounting.account'),
        ),
    ]
