# Generated by Django 6.0.1 on 2026-06-17 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0044_purchaseinvoiceitem_expense_account'),
        ('tenants', '0009_operational_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSettings',
            fields=[
                ('id', models.AutoField(db_column='PurchaseSettingsID', primary_key=True, serialize=False)),
                ('purchase_default_price_strategy', models.CharField(choices=[('LAST_PURCHASE', 'آخر سعر شراء (أحدث فاتورة مرحَّلة)'), ('LOWEST_PURCHASE', 'أقل سعر شراء (الأدنى تاريخياً)')], db_column='PurchaseDefaultPriceStrategy', default='LAST_PURCHASE', help_text='استراتيجية تعبئة سعر الوحدة تلقائياً عند اختيار صنف في بند الشراء', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('tenant', models.OneToOneField(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_module_settings',
                'managed': True,
            },
        ),
    ]
