# Generated by Django 6.0.3 on 2026-06-20 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_voidedjournal'),
        ('logistics', '0045_purchasesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesettings',
            name='default_cash_account',
            field=models.ForeignKey(blank=True, db_column='DefaultCashAccountID', help_text='حساب الصندوق الافتراضي للدفعات النقدية في فواتير الشراء', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_settings_cash', to='accounting.account'),
        ),
    ]
