# Generated by Django 6.0.1 on 2026-07-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0048_purchaseinvoice_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='import_deal_remaining_rate',
            field=models.DecimalField(blank=True, db_column='ImportDealRemainingRate', decimal_places=6, help_text='سعر صرف المتبقي (الصفقة) المختار عند الاستيراد من التخليص', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='import_shipment_remaining_rate',
            field=models.DecimalField(blank=True, db_column='ImportShipmentRemainingRate', decimal_places=6, help_text='سعر صرف المتبقي (الشحن) المختار عند الاستيراد من التخليص', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='import_use_cost_lines',
            field=models.BooleanField(blank=True, db_column='ImportUseCostLines', help_text='أساس حوض التخليص عند الاستيراد: بنود التكلفة (True) أو الدفعات', null=True),
        ),
    ]
