# Generated by Django 6.0.3 on 2026-07-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0049_purchaseinvoice_import_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsdeal',
            name='stage',
            field=models.CharField(blank=True, choices=[('draft', 'مسودة'), ('ready_to_ship', 'جاهزة للشحن'), ('in_shipment', 'ضمن شحنة'), ('at_clearance', 'في التخليص'), ('in_transport', 'نقل محلي'), ('invoiced', 'محوّلة إلى فاتورة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة')], db_column='Stage', help_text='المرحلة القانونية الموحّدة لمسار الاستيراد (M0). تُدار عبر خدمة الانتقالات.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='chargeable_unit',
            field=models.CharField(blank=True, choices=[('cbm', 'متر مكعب (CBM)'), ('kg', 'كيلوجرام (KG)')], db_column='ChargeableUnit', help_text='وحدة تسعير الشحن المختارة يدوياً: CBM أو KG (أساس توزيع الشحن على الصفقات)', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='freight_rate',
            field=models.DecimalField(blank=True, db_column='FreightRate', decimal_places=4, help_text='سعر الشحن لكل وحدة (CBM أو KG). الإجمالي = السعر × مجموع الوحدة المختارة', max_digits=18, null=True),
        ),
    ]
