# Generated by Django 6.0.3 on 2026-07-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0052_remove_logisticsexpense_logistics_e_related_0fbc5d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsshipment',
            name='journal_no_display',
        ),
        migrations.RemoveField(
            model_name='logisticsshipment',
            name='supplier_address',
        ),
    ]
