# Generated by Django 6.0.3 on 2026-07-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_journal_indexes'),
        ('logistics', '0053_remove_logisticsshipment_journal_no_display_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalShipmentPayment',
            fields=[
                ('id', models.AutoField(db_column='LocalShipmentPaymentID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1, max_digits=18)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('cash_box_external_id', models.CharField(db_column='CashBoxExternalID', max_length=128)),
                ('notes', models.TextField(blank=True, db_column='Notes', default='')),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_local_shipment_payments', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='local_shipment_payments', to='tenants.currency')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_shipment_payments', to='accounting.journalheader')),
                ('local_shipment', models.ForeignKey(db_column='LocalShipmentID', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.localshipment')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'logistics_local_shipment_payments',
                'ordering': ['-payment_date', '-id'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='localshipmentpayment',
            index=models.Index(fields=['local_shipment', 'payment_date'], name='lg_lspay_shipment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='localshipmentpayment',
            index=models.Index(fields=['tenant', 'cash_box_external_id'], name='lg_lspay_tenant_box_idx'),
        ),
    ]
