# Generated by Django 6.0.3 on 2026-07-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_journal_indexes'),
        ('logistics', '0056_fix_logistics_payment_partner_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsshipment',
            name='freight_exchange_rate',
            field=models.DecimalField(blank=True, db_column='FreightExchangeRate', decimal_places=6, help_text='سعر صرف الدولار للشيكل المعتمد لاستحقاق شحن الوكيل', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='freight_is_posted',
            field=models.BooleanField(db_column='FreightIsPosted', default=False, help_text='هل رُحّل قيد استحقاق شحن الوكيل؟'),
        ),
        migrations.AddField(
            model_name='logisticsshipment',
            name='freight_journal',
            field=models.ForeignKey(blank=True, db_column='FreightJournalID', help_text='قيد استحقاق شحن الوكيل (Dr مصاريف الشحن الدولي / Cr ذمم الوكيل)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_shipments', to='accounting.journalheader'),
        ),
    ]
