# Generated by Django 6.0.3 on 2026-07-26 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_variant_group'),
        ('logistics', '0057_shipment_freight_accrual'),
        ('partners', '0008_partnerbankaccount_defaults'),
        ('tenants', '0016_tenantsettings_dashboard_month_start_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('id', models.AutoField(db_column='SupplierQuotationID', primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(db_column='QuotationNumber', max_length=50)),
                ('scope', models.CharField(choices=[('local', 'Local purchase'), ('import', 'Import')], db_column='Scope', default='local', max_length=10)),
                ('quotation_date', models.DateField(db_column='QuotationDate')),
                ('valid_until', models.DateField(blank=True, db_column='ValidUntil', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('converted', 'Converted')], db_column='Status', default='draft', max_length=20)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1, max_digits=18)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(db_column='DiscountAmount', decimal_places=2, default=0, max_digits=18)),
                ('tax_rate', models.DecimalField(db_column='TaxRate', decimal_places=4, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(db_column='GrandTotal', decimal_places=2, default=0, max_digits=18)),
                ('shipping_cost_estimate', models.DecimalField(db_column='ShippingCostEstimate', decimal_places=2, default=0, max_digits=18)),
                ('is_shipping_included', models.BooleanField(db_column='IsShippingIncluded', default=False)),
                ('incoterms', models.CharField(db_column='Incoterms', default='FOB', max_length=10)),
                ('shipping_method', models.CharField(db_column='ShippingMethod', default='Sea', max_length=50)),
                ('payment_method', models.CharField(db_column='PaymentMethod', default='T/T', max_length=50)),
                ('production_days', models.PositiveIntegerField(db_column='ProductionDays', default=0)),
                ('delivery_days', models.PositiveIntegerField(db_column='DeliveryDays', default=0)),
                ('total_cbm', models.DecimalField(db_column='TotalCBM', decimal_places=3, default=0, max_digits=10)),
                ('total_weight_kg', models.DecimalField(db_column='TotalWeightKg', decimal_places=3, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, db_column='Notes', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_quotations', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotations', to='tenants.currency')),
                ('supplier', models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotations', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'supplier_quotations',
                'ordering': ['-quotation_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='logisticsdeal',
            name='source_quotation',
            field=models.OneToOneField(blank=True, db_column='SourceQuotationID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_deal', to='logistics.supplierquotation'),
        ),
        migrations.CreateModel(
            name='SupplierQuotationLine',
            fields=[
                ('id', models.AutoField(db_column='SupplierQuotationLineID', primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(db_column='Seq', default=1)),
                ('name_snapshot', models.CharField(blank=True, db_column='NameSnapshot', default='', max_length=255)),
                ('description_line', models.TextField(blank=True, db_column='DescriptionLine', default='')),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('line_total', models.DecimalField(db_column='LineTotal', decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_quotation_lines', to='inventory.product')),
                ('quotation', models.ForeignKey(db_column='SupplierQuotationID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.supplierquotation')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotation_lines', to='tenants.tenant')),
            ],
            options={
                'db_table': 'supplier_quotation_lines',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.UniqueConstraint(fields=('tenant', 'scope', 'quotation_number'), name='uniq_supplier_quote_no_scope'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='supplier_quote_rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='supplier_quote_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='supplier_quote_tax_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotation',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_cost_estimate__gte', 0)), name='supplier_quote_shipping_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.UniqueConstraint(fields=('quotation', 'seq'), name='uniq_supplier_quote_line_seq'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supplier_quote_line_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='supplierquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='supplier_quote_line_price_gte_zero'),
        ),
    ]
