# Generated by Django 6.0.3 on 2026-07-26 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_variant_group'),
        ('logistics', '0058_supplierquotation_logisticsdeal_source_quotation_and_more'),
        ('partners', '0008_partnerbankaccount_defaults'),
        ('tenants', '0016_tenantsettings_dashboard_month_start_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('id', models.AutoField(db_column='PurchaseOrderID', primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_column='OrderNumber', max_length=50)),
                ('order_date', models.DateField(db_column='OrderDate')),
                ('expected_delivery_date', models.DateField(blank=True, db_column='ExpectedDeliveryDate', null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكدة'), ('converted', 'محوّلة إلى فاتورة'), ('cancelled', 'ملغاة')], db_column='Status', default='draft', max_length=20)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1, max_digits=18)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(db_column='DiscountAmount', decimal_places=2, default=0, max_digits=18)),
                ('tax_rate', models.DecimalField(db_column='TaxRate', decimal_places=4, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(db_column='GrandTotal', decimal_places=2, default=0, max_digits=18)),
                ('shipping_cost', models.DecimalField(db_column='ShippingCost', decimal_places=2, default=0, max_digits=18)),
                ('is_shipping_included', models.BooleanField(db_column='IsShippingIncluded', default=False)),
                ('shipping_method', models.CharField(blank=True, db_column='ShippingMethod', default='', max_length=50)),
                ('payment_method', models.CharField(blank=True, db_column='PaymentMethod', default='', max_length=50)),
                ('delivery_days', models.PositiveIntegerField(db_column='DeliveryDays', default=0)),
                ('notes', models.TextField(blank=True, db_column='Notes', default='')),
                ('cancel_reason', models.TextField(blank=True, db_column='CancelReason', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tenants.currency')),
                ('invoice', models.OneToOneField(blank=True, db_column='PurchaseInvoiceID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_purchase_order', to='logistics.purchaseinvoice')),
                ('quotation', models.OneToOneField(blank=True, db_column='SupplierQuotationID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_order', to='logistics.supplierquotation')),
                ('supplier', models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(db_column='PurchaseOrderLineID', primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(db_column='Seq', default=1)),
                ('name_snapshot', models.CharField(blank=True, db_column='NameSnapshot', default='', max_length=255)),
                ('description_line', models.TextField(blank=True, db_column='DescriptionLine', default='')),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('line_total', models.DecimalField(db_column='LineTotal', decimal_places=2, default=0, max_digits=18)),
                ('order', models.ForeignKey(db_column='PurchaseOrderID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.purchaseorder')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_lines', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_order_lines',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='uniq_purchase_order_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='purchase_order_rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='purchase_order_discount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='purchase_order_tax_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_cost__gte', 0)), name='purchase_order_shipping_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'seq'), name='uniq_purchase_order_line_seq'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_order_line_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_order_line_price_gte_zero'),
        ),
    ]
