# Generated by Django 6.0.3 on 2026-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0060_migrate_legacy_procurement_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesettings',
            name='receive_on_post',
            field=models.BooleanField(db_column='ReceiveOnPost', default=True, help_text='إدخال بضاعة الفاتورة للمستودع تلقائياً عند الترحيل'),
        ),
    ]
