# Generated by Django 6.0.3 on 2026-07-29 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_cheque_bank_snapshot'),
        ('inventory', '0012_product_variant_group'),
        ('logistics', '0061_purchasesettings_receive_on_post'),
        ('tenants', '0016_tenantsettings_dashboard_month_start_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.AutoField(db_column='GoodsReceiptID', primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_column='ReceiptNumber', max_length=50)),
                ('receipt_date', models.DateField(db_column='ReceiptDate')),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=500)),
                ('auto_created', models.BooleanField(db_column='AutoCreated', default=False, help_text='أُنشئت تلقائياً مع ترحيل الفاتورة (إعداد الاستلام مع الترحيل)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('branch', models.ForeignKey(blank=True, db_column='BranchID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='tenants.branch')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(db_column='PurchaseInvoiceID', help_text='الفاتورة المرتبطة — بنود الإرسالية تُختار من بنودها حصراً', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='logistics.purchaseinvoice')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='accounting.journalheader')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_module_goods_receipts',
                'ordering': ['-receipt_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.AutoField(db_column='GoodsReceiptLineID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('item', models.ForeignKey(db_column='InvoiceItemID', on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='logistics.purchaseinvoiceitem')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.product')),
                ('receipt', models.ForeignKey(db_column='GoodsReceiptID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.goodsreceipt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_lines', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, db_column='WarehouseID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'purchase_module_goods_receipt_lines',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('tenant', 'receipt_number'), name='uniq_goods_receipt_number_per_tenant'),
        ),
    ]
