# Generated by Django 6.0.3 on 2026-07-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_variant_group'),
        ('logistics', '0062_goodsreceipt_goodsreceiptline_and_more'),
        ('partners', '0009_customer_note_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='PartnerID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier_ref',
            field=models.CharField(blank=True, db_column='SupplierRef', default='', help_text='رقم/مرجع المورد لهذا الاستلام (بوليصة، إشعار تسليم…)', max_length=100),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='movement',
            field=models.ForeignKey(blank=True, db_column='MovementID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_lines', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='unit_price',
            field=models.DecimalField(db_column='UnitPrice', decimal_places=4, default=0, help_text='تكلفة الوحدة — تُدخَل في السند المستقل، وتُشتق من الفاتورة عند ربطها', max_digits=18),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='allow_edit_receipt',
            field=models.BooleanField(db_column='AllowEditReceipt', default=True, help_text='السماح بتعديل/إلغاء الإرسالية بعد حفظها (يعكس أثرها ويعيد تطبيقه)'),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='allow_standalone_receipt',
            field=models.BooleanField(db_column='AllowStandaloneReceipt', default=True, help_text='السماح بإنشاء سند استلام بلا فاتورة مرتبطة (بضاعة وصلت قبل فاتورتها)'),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='receipt_doc_label',
            field=models.CharField(db_column='ReceiptDocLabel', default='إرسالية شراء', help_text='اسم مستند الاستلام المرتبط بفاتورة كما يظهر في الشاشات والطباعة', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='standalone_receipt_label',
            field=models.CharField(db_column='StandaloneReceiptLabel', default='سند استلام', help_text='اسم مستند الاستلام بلا فاتورة مرتبطة', max_length=50),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='PurchaseInvoiceID', help_text='الفاتورة المرتبطة — بنود الإرسالية تُختار من بنودها حصراً. فارغة = «سند استلام» مستقل (بضاعة وصلت بلا فاتورة بعد).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='logistics.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='item',
            field=models.ForeignKey(blank=True, db_column='InvoiceItemID', help_text='بند الفاتورة المرتبطة — فارغ في سند الاستلام المستقل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='logistics.purchaseinvoiceitem'),
        ),
    ]
