# Generated by Django 6.0.3 on 2026-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0063_goodsreceipt_partner_goodsreceipt_supplier_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotation',
            name='alibaba_link',
            field=models.CharField(blank=True, db_column='AlibabaLink', default='', help_text='رابط المنتج/المورد على علي بابا أو منصّة المصدر', max_length=500),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='attachments',
            field=models.JSONField(blank=True, db_column='Attachments', default=list, help_text='[{name,url,type,size}] لملفات عرض السعر المرفوعة'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='decision_reason',
            field=models.CharField(blank=True, db_column='DecisionReason', default='', help_text='سبب اعتبار العرض غير ملائم', max_length=500),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='supplier_contact',
            field=models.CharField(blank=True, db_column='SupplierContact', default='', help_text='رقم التواصل مع مندوب المورد لهذا العرض', max_length=100),
        ),
    ]
