# Generated by Django 6.0.3 on 2026-08-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0064_supplierquotation_alibaba_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='source_quotation',
            field=models.OneToOneField(blank=True, db_column='SourceSupplierQuotationID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_invoice', to='logistics.supplierquotation'),
        ),
    ]
