# Generated by Django 6.0.3 on 2026-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0065_purchaseinvoice_source_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotation',
            name='notes_log',
            field=models.JSONField(blank=True, db_column='NotesLog', default=list, help_text='[{text,at,by}] ملاحظات العرض المؤرَّخة، الأقدم أولاً'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='decision_reason',
            field=models.CharField(blank=True, db_column='DecisionReason', default='', help_text='تفصيل الحالة: سبب عدم الملاءمة أو ما يُنتظَر وصوله', max_length=500),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending_info', 'Pending info'), ('under_discussion', 'Under discussion'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('converted', 'Converted')], db_column='Status', default='draft', max_length=20),
        ),
    ]
