# Generated by Django 6.0.3 on 2026-08-11 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_phase5_p0_indexes'),
        ('logistics', '0070_purchaseinvoiceitem_serials_and_more'),
        ('partners', '0013_general_note_targets'),
        ('sales', '0034_salesinvoiceline_serials_and_more'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logisticsclearance',
            index=models.Index(fields=['tenant', 'status', '-clearance_date'], name='idx_clearance_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='logisticsdeal',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_deal_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='logisticsshipment',
            index=models.Index(fields=['tenant', 'status', '-arrival_date'], name='idx_shipment_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_pi_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['tenant', 'is_posted', 'is_return'], name='idx_pi_tenant_posted_return'),
        ),
    ]
