# Generated by Django 6.0.3 on 2026-08-11 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_phase5_p0_indexes'),
        ('logistics', '0071_logisticsclearance_idx_clearance_tenant_status_and_more'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticspayment',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='TenantID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_payments', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='logisticspayment',
            index=models.Index(fields=['tenant', 'status'], name='idx_lpay_tenant_status'),
        ),
    ]
