# Generated by Django 6.0.3 on 2026-08-11 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0073_backfill_logistics_payment_tenant'),
        ('partners', '0014_partner_idx_partner_tenant_type'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'status', '-order_date'], name='idx_po_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='supplierquotation',
            index=models.Index(fields=['tenant', 'status', '-quotation_date'], name='idx_sq_tenant_status'),
        ),
    ]
