# Generated by Django 5.1.15 on 2026-08-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0074_purchaseorder_idx_po_tenant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='due_date',
            field=models.DateField(blank=True, db_column='DueDate', help_text='تاريخ استحقاق الدفع — يُشتقّ من مهلة السداد إن تُركت فارغة.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, db_column='PaymentTermsDays', help_text='مهلة السداد بالأيام من تاريخ الفاتورة (0 = عند الاستلام).', null=True),
        ),
    ]
