# Generated by Django 5.1.15 on 2026-08-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0075_purchaseinvoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesettings',
            name='default_lead_time_days',
            field=models.PositiveSmallIntegerField(db_column='DefaultLeadTimeDays', default=14, help_text='مهلة التوريد الافتراضية حين لا يكفي سجلّ الطلبيات لاشتقاقها (بالأيام)'),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='replenishment_window_days',
            field=models.PositiveSmallIntegerField(db_column='ReplenishmentWindowDays', default=90, help_text='نافذة تحليل المبيعات لحساب معدّل الصرف اليومي (بالأيام)'),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='review_period_days',
            field=models.PositiveSmallIntegerField(db_column='ReviewPeriodDays', default=30, help_text='كل كم يوماً تراجع الطلب — تحدّد الحدّ الأقصى المقترَح فوق نقطة الطلب'),
        ),
    ]
