# Generated by Django 5.1.15 on 2026-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0077_purchaseinvoice_attached_cash_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesettings',
            name='purchase_default_price_strategy',
            field=models.CharField(choices=[('LAST_PURCHASE', 'آخر سعر شراء (أحدث فاتورة مرحَّلة)'), ('LOWEST_PURCHASE', 'أقل سعر شراء (الأدنى تاريخياً)')], db_column='PurchaseDefaultPriceStrategy', default='LAST_PURCHASE', help_text='استراتيجية تعبئة سعر الوحدة تلقائياً عند اختيار منتج في بند الشراء', max_length=20),
        ),
    ]
