# Generated by Django 5.1.15 on 2026-09-01 19:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0078_alter_purchasesettings_purchase_default_price_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesettings',
            name='forecast_alpha',
            field=models.DecimalField(db_column='ForecastAlpha', decimal_places=2, default=Decimal('0.25'), help_text='حساسية النظام للجديد — لو حسّيته بطيء بالتفاعل زِدها، ولو بيقفز مع كل طلبية شاذّة قلّلها', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('0.99'))]),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='forecast_beta',
            field=models.DecimalField(db_column='ForecastBeta', decimal_places=2, default=Decimal('0.15'), help_text='حساسية الاتجاه — نفس فكرة حساسية الجديد لكن لسرعة تغيّر الاتجاه نفسه', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('0.99'))]),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='forecast_history_weeks',
            field=models.PositiveSmallIntegerField(db_column='ForecastHistoryWeeks', default=26, help_text='كم أسبوعاً للوراء يبني عليها الاتجاه — أقصر من ستة أسابيع لا يكفي ليستقرّ', validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='forecast_safety_factor',
            field=models.DecimalField(db_column='ForecastSafetyFactor', decimal_places=2, default=Decimal('1.28'), help_text='حجم هامش الأمان — كلّما زاد اتّسع مخزون الأمان مقابل تذبذب دقّة التوقّعات', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='purchasesettings',
            name='forecast_trend_cap_ratio',
            field=models.DecimalField(db_column='ForecastTrendCapRatio', decimal_places=2, default=Decimal('0.33'), help_text='سقف الزيادة الأسبوعية كنسبة من البيع الأسبوعي — يمنع بيعة شاذّة من مضاعفة الحدّ', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
