# Generated by Django 5.1.15 on 2026-09-03 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docshare', '0002_share_types_and_decision_note'),
        ('inventory', '0029_supplierproduct_min_order_qty'),
        ('logistics', '0079_purchasesettings_forecast_alpha_and_more'),
        ('partners', '0015_partner_engagement_partner_managed_tenant_and_more'),
        ('tenants', '0031_alter_tenantbook_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='source_quotation',
            field=models.ForeignKey(blank=True, db_column='SourceSupplierQuotationID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_invoice', to='logistics.supplierquotation'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(blank=True, db_column='SupplierQuotationID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_order', to='logistics.supplierquotation'),
        ),
        migrations.CreateModel(
            name='PurchaseRFQ',
            fields=[
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('id', models.AutoField(db_column='PurchaseRFQID', primary_key=True, serialize=False)),
                ('rfq_number', models.CharField(blank=True, db_column='RfqNumber', default=None, max_length=50, null=True)),
                ('scope', models.CharField(choices=[('local', 'Local purchase'), ('import', 'Import')], db_column='Scope', default='local', max_length=10)),
                ('rfq_date', models.DateField(db_column='RfqDate')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسَلة'), ('awarded', 'مُرساة'), ('cancelled', 'ملغاة')], db_column='Status', default='draft', max_length=20)),
                ('reply_deadline', models.DateField(blank=True, db_column='ReplyDeadline', help_text='مهلة ردّ الموردين — اختيارية', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_rfqs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_rfqs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_rfqs',
                'ordering': ['-rfq_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='rfq',
            field=models.ForeignKey(blank=True, db_column='PurchaseRFQID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='logistics.purchaserfq'),
        ),
        migrations.CreateModel(
            name='PurchaseRFQLine',
            fields=[
                ('id', models.AutoField(db_column='PurchaseRFQLineID', primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(db_column='Seq', default=1)),
                ('name_snapshot', models.CharField(blank=True, db_column='NameSnapshot', default='', max_length=255)),
                ('specs', models.TextField(blank=True, db_column='Specs', default='')),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=3, max_digits=18)),
                ('unit_of_measure', models.CharField(blank=True, db_column='UnitOfMeasure', default='', help_text='وحدة قياس البند — حبّة/صندوق/كرتون… كي يعرف المورد ما يُسعّره', max_length=20)),
                ('estimated_price', models.DecimalField(blank=True, db_column='EstimatedPrice', decimal_places=4, help_text='سعرٌ تقديريٌّ داخليّ — لا يُرسَل للمورّد أبداً', max_digits=18, null=True)),
                ('product', models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_rfq_lines', to='inventory.product')),
                ('rfq', models.ForeignKey(db_column='PurchaseRFQID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.purchaserfq')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_rfq_lines', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_rfq_lines',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRFQRecipient',
            fields=[
                ('id', models.AutoField(db_column='PurchaseRFQRecipientID', primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(blank=True, db_column='SentAt', null=True)),
                ('replied_at', models.DateTimeField(blank=True, db_column='RepliedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('quotation', models.OneToOneField(blank=True, db_column='SupplierQuotationID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_recipient', to='logistics.supplierquotation')),
                ('rfq', models.ForeignKey(db_column='PurchaseRFQID', on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='logistics.purchaserfq')),
                ('share', models.ForeignKey(blank=True, db_column='DocumentShareID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_recipients', to='docshare.documentshare')),
                ('supplier', models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.PROTECT, related_name='rfq_recipients', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_rfq_recipients', to='tenants.tenant')),
            ],
            options={
                'db_table': 'purchase_rfq_recipients',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserfq',
            index=models.Index(fields=['tenant', 'status', '-rfq_date'], name='idx_rfq_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='purchaserfq',
            constraint=models.UniqueConstraint(fields=('tenant', 'rfq_number'), name='uniq_purchase_rfq_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaserfqline',
            constraint=models.UniqueConstraint(fields=('rfq', 'seq'), name='uniq_purchase_rfq_line_seq'),
        ),
        migrations.AddConstraint(
            model_name='purchaserfqline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_rfq_line_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaserfqline',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_price__isnull', True), ('estimated_price__gte', 0), _connector='OR'), name='purchase_rfq_line_est_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='purchaserfqline',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), models.Q(('name_snapshot', ''), _negated=True), _connector='OR'), name='purchase_rfq_line_named'),
        ),
        migrations.AddConstraint(
            model_name='purchaserfqrecipient',
            constraint=models.UniqueConstraint(fields=('rfq', 'supplier'), name='uniq_purchase_rfq_recipient_supplier'),
        ),
    ]
