# Generated by Django 5.1.15 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0080_alter_purchaseinvoice_source_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesettings',
            name='use_purchase_orders',
            field=models.BooleanField(db_column='UsePurchaseOrders', default=False, help_text='تفعيل خطوة «أمر الشراء» بين عرض السعر والفاتورة في سلسلة الشراء المحلي'),
        ),
    ]
