# Generated by Django 5.1.15 on 2026-09-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0082_backfill_use_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotationline',
            name='unit_of_measure',
            field=models.CharField(blank=True, db_column='UnitOfMeasure', default='', help_text='وحدة قياس البند — حبّة/صندوق/كرتون… كي يعرف المورد ما يُسعّره', max_length=20),
        ),
    ]
