# Generated by Django 5.1.15 on 2026-09-05 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0084_entry_source_and_quote_line_rfq_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquotation',
            name='general_note',
            field=models.TextField(blank=True, db_column='GeneralNote', default=''),
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='internal_note',
            field=models.TextField(blank=True, db_column='InternalNote', default=''),
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='internal_note_at',
            field=models.DateTimeField(blank=True, db_column='InternalNoteAt', null=True),
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='internal_note_by',
            field=models.ForeignKey(blank=True, db_column='InternalNoteBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquotationline',
            name='supplier_note',
            field=models.TextField(blank=True, db_column='SupplierNote', default=''),
        ),
    ]
