# Generated by Django 5.1.15 on 2026-09-06 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docshare', '0003_add_purchase_rfq_doc_type'),
        ('logistics', '0085_supplier_quotation_notes'),
        ('partners', '0015_partner_engagement_partner_managed_tenant_and_more'),
        ('tenants', '0032_seed_purchase_rfq_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierquotation',
            name='entry_source',
            field=models.CharField(choices=[('supplier_link', 'سعّره المورّد'), ('manual', 'أُدخل عنه'), ('public_link', 'من رابط عام')], db_column='EntrySource', default='manual', help_text='مصدر إدخال العرض: سعّره المورّد على رابطه، أم أُدخل عنه', max_length=20),
        ),
        migrations.CreateModel(
            name='PublicSupplierQuoteRequest',
            fields=[
                ('id', models.AutoField(db_column='PublicSupplierQuoteRequestID', primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(db_column='SupplierName', max_length=200)),
                ('supplier_email', models.EmailField(db_column='SupplierEmail', max_length=100)),
                ('supplier_phone', models.CharField(blank=True, db_column='SupplierPhone', default='', max_length=20)),
                ('email_verified_at', models.DateTimeField(blank=True, db_column='EmailVerifiedAt', null=True)),
                ('general_note', models.TextField(blank=True, db_column='GeneralNote', default='')),
                ('submitted_ip', models.CharField(blank=True, db_column='SubmittedIP', default='', max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='SubmittedAt')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], db_column='Status', default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, db_column='DecidedAt', null=True)),
                ('approved_partner', models.ForeignKey(blank=True, db_column='ApprovedPartnerID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_public_quote_requests', to='partners.partner')),
                ('approved_quotation', models.ForeignKey(blank=True, db_column='ApprovedSupplierQuotationID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born_from_public_request', to='logistics.supplierquotation')),
                ('currency', models.ForeignKey(blank=True, db_column='CurrencyID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_supplier_quote_requests', to='tenants.currency')),
                ('decided_by', models.ForeignKey(blank=True, db_column='DecidedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_public_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(db_column='PurchaseRFQID', on_delete=django.db.models.deletion.CASCADE, related_name='public_quote_requests', to='logistics.purchaserfq')),
                ('share', models.ForeignKey(blank=True, db_column='DocumentShareID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_quote_requests', to='docshare.documentshare')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='public_supplier_quote_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'public_supplier_quote_requests',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublicSupplierQuoteRequestLine',
            fields=[
                ('id', models.AutoField(db_column='PublicSupplierQuoteRequestLineID', primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(db_column='NameSnapshot', max_length=255)),
                ('seq_snapshot', models.PositiveIntegerField(db_column='SeqSnapshot')),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('supplier_note', models.TextField(blank=True, db_column='SupplierNote', default='')),
                ('request', models.ForeignKey(db_column='PublicSupplierQuoteRequestID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.publicsupplierquoterequest')),
                ('rfq_line', models.ForeignKey(blank=True, db_column='PurchaseRFQLineID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_quote_lines', to='logistics.purchaserfqline')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='public_supplier_quote_request_lines', to='tenants.tenant')),
            ],
            options={
                'db_table': 'public_supplier_quote_request_lines',
                'ordering': ['seq_snapshot', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='publicsupplierquoterequest',
            index=models.Index(fields=['tenant', 'rfq', 'status'], name='idx_pubqr_tenant_rfq_status'),
        ),
        migrations.AddConstraint(
            model_name='publicsupplierquoterequestline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='pub_qr_line_price_gte_zero'),
        ),
    ]
