# Generated by Django 6.1.1 on 2026-09-24 18:30
# سعر الدولار بلا قيمة افتراضية (كانت 3.5 تُحفظ صامتةً): الدفعة الجديدة بلا سعر = NULL
# والترحيل يرفضها. المخطط وحده — القيم المخزّنة (ومنها المرحّلة) لا تُمسّ.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0090_untag_local_shipment_expense_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticspayment',
            name='usd_to_ils',
            field=models.DecimalField(blank=True, db_column='usd_to_ils', decimal_places=6, max_digits=18, null=True),
        ),
    ]
