# Generated by Django 6.1.1 on 2026-09-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0091_payment_usd_rate_nullable_no_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsdeal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='logisticsdeal',
            name='currency_rate',
        ),
    ]
