# Generated by Django 6.1.1 on 2026-09-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0092_remove_deal_currency'),
        ('sales', '0044_updated_at_stamp'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsAccrualAllocation',
            fields=[
                ('id', models.AutoField(db_column='AccrualAllocationID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, help_text='بعملة السند', max_digits=18)),
                ('amount_base', models.DecimalField(db_column='AmountBase', decimal_places=2, help_text='بالعملة الأساسية = المبلغ × سعر صرف السند — يُطرح من متبقّي المستحق', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('clearance', models.ForeignKey(blank=True, db_column='ClearanceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_allocations', to='logistics.logisticsclearance')),
                ('local_shipment', models.ForeignKey(blank=True, db_column='LocalShipmentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_allocations', to='logistics.localshipment')),
                ('payment', models.ForeignKey(db_column='SupplierPaymentID', on_delete=django.db.models.deletion.CASCADE, related_name='logistics_allocations', to='sales.supplierpayment')),
                ('shipment', models.ForeignKey(blank=True, db_column='ShipmentID', help_text='استحقاق الشحن الدولي (freight_journal) لوكيل الشحن', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_voucher_allocations', to='logistics.logisticsshipment')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'logistics_accrual_allocations',
                'indexes': [models.Index(fields=['tenant', 'payment'], name='accr_alloc_tenant_pay_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('clearance__isnull', False), ('local_shipment__isnull', True), ('shipment__isnull', True)), models.Q(('clearance__isnull', True), ('local_shipment__isnull', True), ('shipment__isnull', False)), models.Q(('clearance__isnull', True), ('local_shipment__isnull', False), ('shipment__isnull', True)), _connector='OR'), name='accrual_allocation_one_target')],
            },
        ),
    ]
