# Generated by Django 6.1.1 on 2026-09-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0093_logistics_accrual_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsclearance',
            name='broker_claim_number',
            field=models.CharField(blank=True, db_column='BrokerClaimNumber', default='', help_text='رقم مطالبة المخلّص', max_length=100),
        ),
    ]
