# Generated by Django 6.1.1 on 2026-09-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_journalline_amount_currency'),
        ('logistics', '0094_clearance_broker_claim_number'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceItemType',
            fields=[
                ('id', models.AutoField(db_column='ClearanceItemTypeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=120)),
                ('legacy_type', models.CharField(choices=[('vat', 'ضريبة القيمة المضافة'), ('declaration_fee', 'رسوم البيان الجمركي'), ('terminal', 'محطة الشحن'), ('permits', 'معالجة التصاريح'), ('broker_commission', 'عمولة المخلص'), ('customs_system', 'نظام الجمارك «الجيل الجديد»'), ('other', 'أخرى')], db_column='LegacyType', default='other', max_length=32)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_column='SortOrder', default=0)),
                ('account', models.ForeignKey(blank=True, db_column='AccountID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='clearance_item_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'logistics_clearance_item_types',
                'ordering': ['sort_order', 'id'],
                'managed': True,
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='logisticsclearanceline',
            name='item_type',
            field=models.ForeignKey(blank=True, db_column='ClearanceItemTypeID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='logistics.clearanceitemtype'),
        ),
    ]
