# Generated by Django 6.1.1 on 2026-09-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0095_clearance_item_types'),
        ('sales', '0045_credit_debit_note_any_partner'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsaccrualallocation',
            name='note',
            field=models.ForeignKey(blank=True, db_column='CreditDebitNoteID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accrual_allocations', to='sales.creditdebitnote'),
        ),
        migrations.AlterField(
            model_name='logisticsaccrualallocation',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='SupplierPaymentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_allocations', to='sales.supplierpayment'),
        ),
        migrations.AddConstraint(
            model_name='logisticsaccrualallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', True), ('payment__isnull', False)), models.Q(('note__isnull', False), ('payment__isnull', True)), _connector='OR'), name='accrual_allocation_one_source'),
        ),
    ]
