# Generated by Django 6.1.1 on 2026-10-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_cash_box_fx_consumption'),
        ('logistics', '0096_note_allocations'),
        ('partners', '0017_partner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoicefee',
            name='credit_account',
            field=models.ForeignKey(blank=True, db_column='CreditAccountID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_purchase_fees', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='purchaseinvoicefee',
            name='credit_partner',
            field=models.ForeignKey(blank=True, db_column='CreditPartnerID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_purchase_fees', to='partners.partner'),
        ),
    ]
