# Generated by Django 6.1.1 on 2026-10-07 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_cash_box_fx_consumption'),
        ('logistics', '0097_purchase_invoice_fee_credit_party'),
        ('tenants', '0035_grant_import_procurement_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualLineSnapshot',
            fields=[
                ('id', models.AutoField(db_column='AccrualSnapshotID', primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('clearance', 'تخليص'), ('freight', 'شحن الوكيل'), ('local', 'نقل محلي')], db_column='Kind', max_length=16)),
                ('role', models.CharField(choices=[('original', 'الاستحقاق الأصلي'), ('adjustment', 'تعديل استحقاق')], db_column='Role', max_length=16)),
                ('lines', models.JSONField(db_column='Lines', default=list, help_text='[{label, type, amount}] بالعملة الأساسية')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=18)),
                ('detailed', models.BooleanField(db_column='Detailed', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('clearance', models.ForeignKey(blank=True, db_column='ClearanceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accrual_snapshots', to='logistics.logisticsclearance')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal', models.OneToOneField(db_column='JournalID', on_delete=django.db.models.deletion.CASCADE, related_name='accrual_snapshot', to='accounting.journalheader')),
                ('local_shipment', models.ForeignKey(blank=True, db_column='LocalShipmentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accrual_snapshots', to='logistics.localshipment')),
                ('shipment', models.ForeignKey(blank=True, db_column='ShipmentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_accrual_snapshots', to='logistics.logisticsshipment')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'logistics_accrual_line_snapshots',
                'indexes': [models.Index(fields=['tenant', 'kind'], name='accr_snap_tenant_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('clearance__isnull', False), ('local_shipment__isnull', True), ('shipment__isnull', True)), models.Q(('clearance__isnull', True), ('local_shipment__isnull', True), ('shipment__isnull', False)), models.Q(('clearance__isnull', True), ('local_shipment__isnull', False), ('shipment__isnull', True)), _connector='OR'), name='accrual_snapshot_one_document')],
            },
        ),
    ]
