# Generated by Django 6.1.1 on 2026-10-09 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_product_is_active'),
        ('logistics', '0098_accrual_line_snapshot'),
        ('partners', '0018_customernote_is_pinned'),
        ('tenants', '0035_grant_import_procurement_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBoard',
            fields=[
                ('id', models.AutoField(db_column='PriceBoardID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('notes', models.TextField(blank=True, db_column='Notes', default='')),
                ('is_archived', models.BooleanField(db_column='IsArchived', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_boards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='price_boards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'price_boards',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceBoardItem',
            fields=[
                ('id', models.AutoField(db_column='PriceBoardItemID', primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(db_column='Seq', default=1)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('unit_of_measure', models.CharField(blank=True, db_column='UnitOfMeasure', default='', max_length=20)),
                ('quantity', models.DecimalField(blank=True, db_column='Quantity', decimal_places=3, max_digits=18, null=True)),
                ('note', models.TextField(blank=True, db_column='Note', default='')),
                ('board', models.ForeignKey(db_column='PriceBoardID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.priceboard')),
                ('product', models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_board_items', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='price_board_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'price_board_items',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceBoardSupplier',
            fields=[
                ('id', models.AutoField(db_column='PriceBoardSupplierID', primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(db_column='Seq', default=1)),
                ('supplier_name', models.CharField(db_column='SupplierName', max_length=200)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, max_digits=18)),
                ('offer_date', models.DateField(blank=True, db_column='OfferDate', null=True)),
                ('terms', models.TextField(blank=True, db_column='Terms', default='')),
                ('attachments', models.JSONField(blank=True, db_column='Attachments', default=list, help_text='[{name,url,type,size}] مرفقات عرض المورد')),
                ('board', models.ForeignKey(db_column='PriceBoardID', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='logistics.priceboard')),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='price_board_suppliers', to='tenants.currency')),
                ('supplier', models.ForeignKey(blank=True, db_column='SupplierID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_board_suppliers', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='price_board_suppliers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'price_board_suppliers',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceBoardPrice',
            fields=[
                ('id', models.AutoField(db_column='PriceBoardPriceID', primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('note', models.TextField(blank=True, db_column='Note', default='')),
                ('board_item', models.ForeignKey(db_column='PriceBoardItemID', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='logistics.priceboarditem')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='price_board_prices', to='tenants.tenant')),
                ('board_supplier', models.ForeignKey(db_column='PriceBoardSupplierID', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='logistics.priceboardsupplier')),
            ],
            options={
                'db_table': 'price_board_prices',
            },
        ),
        migrations.AddIndex(
            model_name='priceboard',
            index=models.Index(fields=['tenant', 'is_archived', '-updated_at'], name='idx_pb_tenant_archived'),
        ),
        migrations.AddConstraint(
            model_name='priceboarditem',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='price_board_item_named'),
        ),
        migrations.AddConstraint(
            model_name='priceboardsupplier',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='price_board_supplier_rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='priceboardprice',
            constraint=models.UniqueConstraint(fields=('board_item', 'board_supplier'), name='uniq_price_board_cell'),
        ),
        migrations.AddConstraint(
            model_name='priceboardprice',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='price_board_price_gte_zero'),
        ),
    ]
