# Generated by Django 6.1.1 on 2026-10-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0099_price_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsclearancepayment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, db_column='ExchangeRate_ClearancePay', decimal_places=6, help_text='سعر صرف الدفعة كما أدخله المستخدم (1 للشيكل)؛ null = دفعة قديمة قبل الحقل', max_digits=18, null=True),
        ),
    ]
