# Generated by Django 6.0.3 on 2026-08-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0017_phase5_p0_indexes'),
        ('tenants', '0019_tenant_store_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(db_column='ViewDate')),
                ('count', models.PositiveIntegerField(db_column='Count', default=0)),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='store_views', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_product_views', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_product_views',
                'managed': True,
                'unique_together': {('tenant', 'product', 'view_date')},
            },
        ),
    ]
