# Generated by Django 6.0.3 on 2026-08-17 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_product_allow_preorder'),
        ('store', '0001_initial'),
        ('tenants', '0020_membership_ui_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('slug', models.CharField(db_column='Slug', max_length=100)),
                ('description', models.TextField(blank=True, db_column='Description', default='')),
                ('banner_image_url', models.CharField(blank=True, db_column='BannerImageUrl', max_length=500, null=True)),
                ('badge_text', models.CharField(blank=True, db_column='BadgeText', default='', max_length=100)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('sort_order', models.PositiveIntegerField(db_column='SortOrder', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('featured_product', models.ForeignKey(blank=True, db_column='FeaturedProductID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_store_collections', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_collections', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_collections',
                'ordering': ['sort_order', 'id'],
                'managed': True,
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StoreProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(db_column='ImageUrl', max_length=500)),
                ('sort_order', models.PositiveIntegerField(db_column='SortOrder', default=0)),
                ('is_cover', models.BooleanField(db_column='IsCover', default=False)),
                ('caption', models.CharField(blank=True, db_column='Caption', default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='store_custom_images', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_product_images', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_product_images',
                'ordering': ['sort_order', 'id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, db_column='HeroTitle', default='', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, db_column='HeroSubtitle', default='')),
                ('announcement_bar', models.CharField(blank=True, db_column='AnnouncementBar', default='', max_length=255)),
                ('show_announcement', models.BooleanField(db_column='ShowAnnouncement', default=True)),
                ('theme_preset', models.CharField(db_column='ThemePreset', default='default', max_length=50)),
                ('primary_color', models.CharField(db_column='PrimaryColor', default='#2563eb', max_length=30)),
                ('accent_color', models.CharField(db_column='AccentColor', default='#f59e0b', max_length=30)),
                ('background_color', models.CharField(db_column='BackgroundColor', default='#f8fafc', max_length=30)),
                ('background_image_url', models.CharField(blank=True, db_column='BackgroundImageUrl', max_length=500, null=True)),
                ('background_style', models.CharField(db_column='BackgroundStyle', default='cover', max_length=50)),
                ('banner_image_url', models.CharField(blank=True, db_column='BannerImageUrl', max_length=500, null=True)),
                ('instagram_url', models.CharField(blank=True, db_column='InstagramUrl', max_length=300, null=True)),
                ('tiktok_url', models.CharField(blank=True, db_column='TiktokUrl', max_length=300, null=True)),
                ('facebook_url', models.CharField(blank=True, db_column='FacebookUrl', max_length=300, null=True)),
                ('snapchat_url', models.CharField(blank=True, db_column='SnapchatUrl', max_length=300, null=True)),
                ('whatsapp_number', models.CharField(blank=True, db_column='WhatsappNumber', max_length=50, null=True)),
                ('catalog_mode_default', models.CharField(db_column='CatalogModeDefault', default='grid', max_length=30)),
                ('allow_cart', models.BooleanField(db_column='AllowCart', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('tenant', models.OneToOneField(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_theme_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_column='SortOrder', default=0)),
                ('collection', models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storecollection')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='store_collection_memberships', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_collection_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_collection_items',
                'ordering': ['sort_order', 'id'],
                'managed': True,
                'unique_together': {('collection', 'product')},
            },
        ),
    ]
