# Generated by Django 6.0.3 on 2026-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storecollection_storeproductimage_storesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductimage',
            name='overlay_color',
            field=models.CharField(db_column='OverlayColor', default='red_fire', max_length=50),
        ),
        migrations.AddField(
            model_name='storeproductimage',
            name='overlay_style',
            field=models.CharField(db_column='OverlayStyle', default='diagonal_ribbon', max_length=50),
        ),
        migrations.AddField(
            model_name='storeproductimage',
            name='overlay_text',
            field=models.CharField(blank=True, db_column='OverlayText', default='', max_length=200),
        ),
    ]
