# Generated by Django 5.1.15 on 2026-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeproductimage_overlay_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_prices',
            field=models.BooleanField(db_column='ShowPrices', default=True),
        ),
    ]
