# Generated by Django 5.1.15 on 2026-09-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_product_reference_image'),
        ('store', '0004_storesettings_show_prices'),
        ('tenants', '0032_seed_purchase_rfq_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecollection',
            name='discount_percent',
            field=models.DecimalField(db_column='DiscountPercent', decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='storecollection',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_column='EndsAt', null=True),
        ),
        migrations.AddField(
            model_name='storecollection',
            name='priority',
            field=models.IntegerField(db_column='Priority', default=0),
        ),
        migrations.AddField(
            model_name='storecollection',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_column='StartsAt', null=True),
        ),
        migrations.CreateModel(
            name='StoreBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('sort_order', models.PositiveIntegerField(db_column='SortOrder', default=0)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_brands', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_brands',
                'ordering': ['sort_order', 'id'],
                'managed': True,
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('slug', models.CharField(db_column='Slug', max_length=140)),
                ('sort_order', models.PositiveIntegerField(db_column='SortOrder', default=0)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageUrl', default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('parent', models.ForeignKey(blank=True, db_column='ParentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.storecategory')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_categories', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_categories',
                'ordering': ['sort_order', 'id'],
                'managed': True,
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(db_column='NameAr', max_length=200)),
                ('name_en', models.CharField(blank=True, db_column='NameEn', default='', max_length=200)),
                ('slug', models.CharField(db_column='Slug', max_length=220)),
                ('unit', models.CharField(blank=True, db_column='Unit', default='', max_length=50)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=18, null=True)),
                ('sale_price', models.DecimalField(blank=True, db_column='SalePrice', decimal_places=2, max_digits=18, null=True)),
                ('stock_state', models.CharField(choices=[('in_stock', 'متوفر'), ('out_of_stock', 'غير متوفر'), ('preorder', 'طلب مسبق')], db_column='StockState', default='in_stock', max_length=20)),
                ('description', models.TextField(blank=True, db_column='Description', default='')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('sort_order', models.PositiveIntegerField(db_column='SortOrder', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('imported_from_product_id', models.PositiveIntegerField(blank=True, db_column='ImportedFromProductID', db_index=True, null=True)),
                ('brand', models.ForeignKey(blank=True, db_column='BrandID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.storebrand')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='store.storecategory')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_products',
                'ordering': ['sort_order', 'id'],
                'managed': True,
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StorePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=18, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='ChangedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_price_history', to='tenants.tenant')),
                ('store_product', models.ForeignKey(db_column='StoreProductID', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='store.storeproduct')),
            ],
            options={
                'db_table': 'store_price_history',
                'ordering': ['-changed_at', '-id'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='storecollectionitem',
            unique_together={('collection', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='storeproductview',
            unique_together={('tenant', 'product', 'view_date')},
        ),
        migrations.AddField(
            model_name='storecollectionitem',
            name='store_product',
            field=models.ForeignKey(blank=True, db_column='StoreProductID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='store.storeproduct'),
        ),
        migrations.AddField(
            model_name='storeproductimage',
            name='store_product',
            field=models.ForeignKey(blank=True, db_column='StoreProductID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.storeproduct'),
        ),
        migrations.AddField(
            model_name='storeproductview',
            name='store_product',
            field=models.ForeignKey(blank=True, db_column='StoreProductID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='store.storeproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='storecollectionitem',
            unique_together={('collection', 'product'), ('collection', 'store_product')},
        ),
        migrations.AlterUniqueTogether(
            name='storeproductview',
            unique_together={('tenant', 'product', 'view_date'), ('tenant', 'store_product', 'view_date')},
        ),
    ]
