# Generated by Django 5.1.15 on 2026-09-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_product_reference_image'),
        ('store', '0006_migrate_catalog_to_store_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecollectionitem',
            name='product',
            field=models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_collection_memberships', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='storeproductimage',
            name='product',
            field=models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_custom_images', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='storeproductview',
            name='product',
            field=models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_views', to='inventory.product'),
        ),
    ]
