# Generated by Django 5.1.15 on 2026-09-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_m2_product_fk_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecollection',
            name='featured_store_product',
            field=models.ForeignKey(blank=True, db_column='FeaturedStoreProductID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_collections', to='store.storeproduct'),
        ),
    ]
