# Generated by Django 5.1.15 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_populate_featured_store_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='new_product_days',
            field=models.PositiveIntegerField(db_column='NewProductDays', default=30),
        ),
    ]
