# Generated by Django 5.1.15 on 2026-09-07 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storesettings_new_product_days'),
        ('tenants', '0033_grant_store_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(db_column='Items', default=list)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('collection', models.ForeignKey(blank=True, db_column='CollectionID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_intents', to='store.storecollection')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_order_intents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_order_intents',
                'ordering': ['-created_at', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreCollectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(db_column='ViewDate')),
                ('count', models.PositiveIntegerField(db_column='Count', default=0)),
                ('collection', models.ForeignKey(db_column='CollectionID', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='store.storecollection')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='store_collection_views', to='tenants.tenant')),
            ],
            options={
                'db_table': 'store_collection_views',
                'managed': True,
                'unique_together': {('tenant', 'collection', 'view_date')},
            },
        ),
    ]
