ALTER TABLE products 
ADD COLUMN ImageURL VARCHAR(512) NULL,
ADD COLUMN ImagePublicID VARCHAR(255) NULL;

ALTER TABLE partners 
ADD COLUMN DocumentURL VARCHAR(512) NULL,
ADD COLUMN DocumentPublicID VARCHAR(255) NULL;
