[pytest]
DJANGO_SETTINGS_MODULE = core.test_settings
python_files = test_*.py
testpaths = accounting/tests inventory/tests logistics/tests sales/tests core/tests tenants/tests
addopts = --nomigrations
