
-- Comprehensive Sync for Logistics Deals table
ALTER TABLE `logistics_deals`
ADD COLUMN IF NOT EXISTS `pi_number` VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS `description` VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS `shipping_method` VARCHAR(50) DEFAULT 'Sea',
ADD COLUMN IF NOT EXISTS `incoterms` VARCHAR(10) DEFAULT 'FOB',
ADD COLUMN IF NOT EXISTS `payment_method` VARCHAR(50) DEFAULT 'T/T',
ADD COLUMN IF NOT EXISTS `production_days` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `delivery_days` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `total_cbm` DECIMAL(10,3) DEFAULT 0.000,
ADD COLUMN IF NOT EXISTS `total_weight` DECIMAL(10,3) DEFAULT 0.000,
ADD COLUMN IF NOT EXISTS `certificates` VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS `shipping_cost_estimate` DECIMAL(18,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS `discount_amount` DECIMAL(18,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS `fees_percentage` DECIMAL(5,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS `is_shipping_included` TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS `alibaba_link` VARCHAR(500) NULL,
ADD COLUMN IF NOT EXISTS `IsPosted` TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS `JournalID` INT NULL;

-- Ensure constraints match model if possible (Manual check recommended)
