# Generated by Django 6.0.3 on 2026-08-10 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0032_cheques_align_nullable_columns'),
        ('inventory', '0016_product_supplier_warranty_months_and_more'),
        ('partners', '0013_general_note_targets'),
        ('sales', '0034_salesinvoiceline_serials_and_more'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_labour_product', models.ForeignKey(blank=True, help_text='صنف خدمة «أجرة صيانة» الافتراضي في الفاتورة المولَّدة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_labour_settings', to='inventory.product')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_settings', to='tenants.tenant')),
                ('warranty_expense_account', models.ForeignKey(blank=True, help_text='حساب «مصاريف صيانة الكفالة» — مدين صرف القطع المغطاة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_warranty_expense_settings', to='accounting.account')),
            ],
            options={
                'db_table': 'after_sales_settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, default='', max_length=30)),
                ('order_date', models.DateField()),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('serial', models.CharField(blank=True, default='', max_length=100)),
                ('device_description', models.CharField(blank=True, default='', max_length=300)),
                ('received_condition', models.TextField(blank=True, default='')),
                ('accessories', models.CharField(blank=True, default='', max_length=300)),
                ('complaint', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('warranty_covered', models.BooleanField(default=False)),
                ('supplier_claim', models.BooleanField(default=False)),
                ('supplier_claim_note', models.CharField(blank=True, default='', max_length=300)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'مُستلَم'), ('in_diagnosis', 'قيد التشخيص'), ('awaiting_approval', 'بانتظار الموافقة'), ('in_repair', 'قيد الإصلاح'), ('ready', 'جاهز للتسليم'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغى')], default='received', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('repaired', 'تم الإصلاح'), ('unrepaired', 'تعذّر الإصلاح'), ('rejected_estimate', 'رفض الزبون التقدير'), ('no_fault', 'لا عطل')], default='', max_length=20)),
                ('covered_posted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('billing_waived_reason', models.CharField(blank=True, default='', max_length=300)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_orders', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='partners.partner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='inventory.product')),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='sales.salesinvoice')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_assigned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'service_orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('billing', models.CharField(choices=[('billable', 'مفوترة على الزبون'), ('covered', 'مغطاة بالكفالة')], default='billable', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('materialized_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='after_sales.serviceorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_order_parts', to='inventory.product')),
                ('sales_invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_parts', to='sales.salesinvoiceline')),
            ],
            options={
                'db_table': 'service_order_parts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, default='', max_length=200)),
                ('serial', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('start_date', models.DateField()),
                ('duration_months', models.PositiveSmallIntegerField(default=0)),
                ('end_date', models.DateField()),
                ('source', models.CharField(choices=[('auto_sale', 'تلقائية من فاتورة بيع'), ('manual', 'يدوية')], default='manual', max_length=20)),
                ('supplier_warranty_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warranty_cards', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_cards', to='partners.partner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_cards', to='inventory.product')),
                ('product_serial', models.ForeignKey(blank=True, help_text='الوحدة المُرقَّمة التي تغطّيها البطاقة، إن كانت من بضاعتنا', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_cards', to='inventory.productserial')),
                ('sales_invoice_line', models.ForeignKey(blank=True, help_text='بند فاتورة البيع الذي وَلَّد البطاقة — مرساة حذفها عند إلغاء الترحيل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_cards', to='sales.salesinvoiceline')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_warranty_cards', to='partners.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_cards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'warranty_cards',
                'ordering': ['-end_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='warranty_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='after_sales.warrantycard'),
        ),
        migrations.CreateModel(
            name='ServiceOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status', 'تغيير حالة'), ('note', 'ملاحظة'), ('part', 'قطع غيار'), ('posting', 'ترحيل'), ('invoice', 'فوترة'), ('approval', 'موافقة')], default='note', max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='after_sales.serviceorder')),
            ],
            options={
                'db_table': 'service_order_events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='svcevent_order_new_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='warrantycard',
            index=models.Index(fields=['tenant', 'serial'], name='warranty_tenant_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantycard',
            index=models.Index(fields=['tenant', 'end_date'], name='warranty_tenant_end_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['tenant', 'status'], name='svcorder_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['tenant', 'serial'], name='svcorder_tenant_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['tenant', '-created_at'], name='svcorder_tenant_new_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['tenant', 'order_number'], name='svcorder_tenant_num_idx'),
        ),
    ]
