# Generated by Django 5.1.15 on 2026-08-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0001_initial'),
        ('inventory', '0024_alter_product_allow_preorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersalessettings',
            name='default_labour_product',
            field=models.ForeignKey(blank=True, help_text='منتج خدمة «أجرة صيانة» الافتراضي في الفاتورة المولَّدة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_labour_settings', to='inventory.product'),
        ),
    ]
