# Generated by Django 6.1.1 on 2026-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0003_warranty_card_end_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderpart',
            name='issued_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderpart',
            name='serials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
