# Generated by Django 6.1.1 on 2026-09-28 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0004_serviceorderpart_issued_cost_and_more'),
        ('tenants', '0035_grant_import_procurement_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyCardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('void', 'إلغاء كفالة التاجر'), ('unvoid', 'تراجع عن الإلغاء'), ('extend', 'تمديد'), ('ended', 'انتهاء'), ('revived', 'إحياء'), ('issued', 'إصدار (طباعة/مشاركة)'), ('referred', 'إحالة لمركز الوكيل'), ('coverage_refused', 'رفض الكفالة لهذا العطل'), ('coverage_restored', 'استعادة الكفالة لهذا العطل'), ('replacement', 'استبدال الجهاز')], max_length=20)),
                ('reason_code', models.CharField(blank=True, default='', max_length=30)),
                ('text', models.TextField(blank=True, default='')),
                ('old_end_date', models.DateField(blank=True, null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_card_events', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='after_sales.warrantycard')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_card_events', to='after_sales.serviceorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_card_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'warranty_card_events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['card', 'created_at'], name='warrantyevent_card_new_idx')],
            },
        ),
    ]
