# Generated by Django 6.1.1 on 2026-09-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0005_warrantycardevent'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersalessettings',
            name='default_terms',
            field=models.TextField(blank=True, default='', help_text='شروط كفالة الشركة — تُنسخ إلى `terms_text` على كل بطاقة عند إنشائها'),
        ),
        migrations.AddField(
            model_name='aftersalessettings',
            name='extend_for_shop_days',
            field=models.BooleanField(default=True, help_text='تمديد كفالة التاجر تلقائياً بعدد أيام بقاء الجهاز المغطّى عندنا'),
        ),
        migrations.AddField(
            model_name='aftersalessettings',
            name='repair_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aftersalessettings',
            name='repair_warranty_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='مدة كفالة الإصلاح بالأيام — صفرٌ يطفئها، وإلا فمن 1 إلى 730'),
        ),
        migrations.CreateModel(
            name='ManufacturerWarrantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('service_center_address', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_warrantors', to='tenants.tenant')),
            ],
            options={
                'db_table': 'manufacturer_warrantors',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='manufacturer_warrantor_tenant_name_uniq')],
            },
        ),
    ]
