# Generated by Django 6.1.1 on 2026-09-28 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0006_aftersalessettings_default_terms_and_more'),
        ('inventory', '0038_productserial_issued_to_alter_productserial_status'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycard',
            name='terms_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='WarrantyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('serial', 'برقم تسلسلي'), ('invoice', 'على الفاتورة')], default='serial', max_length=10)),
                ('dealer_months', models.PositiveSmallIntegerField(default=0, help_text='مدة كفالة التاجر بالأشهر', validators=[django.core.validators.MaxValueValidator(600)])),
                ('manufacturer_months', models.PositiveSmallIntegerField(default=0, help_text='مدة كفالة المصنع بالأشهر — أكبر من صفر إن وُجدت الجهة، وإلا صفر', validators=[django.core.validators.MaxValueValidator(600)])),
                ('supplier_months', models.PositiveSmallIntegerField(default=0, help_text='مدة كفالة المورّد (داخلية) بالأشهر', validators=[django.core.validators.MaxValueValidator(600)])),
                ('terms_override', models.TextField(blank=True, default='', help_text='شروطٌ خاصة بهذا البراند — تحلّ محلّ شروط الشركة على بطاقاته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_warrantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_policies', to='after_sales.manufacturerwarrantor')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_policy', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_policies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'warranty_policies',
                'ordering': ['product_id'],
            },
        ),
    ]
