# Generated by Django 6.1.1 on 2026-09-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0008_backfill_warranty_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycard',
            name='manufacturer_duration_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='manufacturer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='manufacturer_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='manufacturer_warrantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_cards', to='after_sales.manufacturerwarrantor'),
        ),
    ]
