# Generated by Django 6.1.1 on 2026-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0009_warrantycard_manufacturer_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycard',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
