# Generated by Django 6.1.1 on 2026-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0010_warrantycard_invoice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantycardevent',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
