# Generated by Django 6.1.1 on 2026-09-28 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0011_warrantycardevent_quantity_widen'),
        ('logistics', '0096_note_allocations'),
        ('tenants', '0035_grant_import_procurement_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLineWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_months', models.PositiveSmallIntegerField(default=0, help_text='مدة كفالة المصنع بالأشهر — أكبر من صفر إن وُجدت الجهة، وإلا صفر', validators=[django.core.validators.MaxValueValidator(600)])),
                ('supplier_months', models.PositiveSmallIntegerField(blank=True, help_text='مدة كفالة المورّد بالأشهر لهذا السطر — الفارغ يأخذ من السياسة', null=True, validators=[django.core.validators.MaxValueValidator(600)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_warrantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_line_warranties', to='after_sales.manufacturerwarrantor')),
                ('purchase_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_warranty', to='logistics.purchaseinvoiceitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_line_warranties', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_line_warranties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_line_warranties',
            },
        ),
    ]
