# Generated by Django 6.1.1 on 2026-09-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0012_purchaselinewarranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycard',
            name='void_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='void_reason',
            field=models.CharField(blank=True, choices=[('physical_damage', 'ضرر مادي'), ('liquid', 'تعرّض لسوائل'), ('opened_outside', 'فُتح خارج المركز'), ('tampered', 'عبث بالأختام أو البرمجيات'), ('misuse', 'سوء استخدام'), ('other', 'أخرى')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='void_service_order',
            field=models.ForeignKey(blank=True, help_text='أمر الصيانة الذي أُلغيت الكفالة من داخله، إن وُجد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_warranty_cards', to='after_sales.serviceorder'),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_warranty_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceorderevent',
            name='event_type',
            field=models.CharField(choices=[('status', 'تغيير حالة'), ('note', 'ملاحظة'), ('part', 'قطع غيار'), ('posting', 'ترحيل'), ('invoice', 'فوترة'), ('approval', 'موافقة'), ('warranty', 'كفالة')], default='note', max_length=20),
        ),
    ]
