# Generated by Django 6.1.1 on 2026-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0016_warrantycard_verify_token_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantycard',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('returned', 'أُرجع الجهاز'), ('invoice_unposted', 'أُلغي ترحيل الفاتورة'), ('sale_cancelled', 'أُلغي البيع'), ('superseded', 'حلّت محلّها بطاقة أحدث'), ('withdrawn', 'سُحبت البطاقة')], default='', max_length=20),
        ),
    ]
