# Generated by Django 6.1.1 on 2026-09-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0020_warrantycard_repair_source_and_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderpart',
            name='replaces_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='replacement_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_warranty_cards', to='after_sales.serviceorder'),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='replaces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='after_sales.warrantycard'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='outcome',
            field=models.CharField(blank=True, choices=[('repaired', 'تم الإصلاح'), ('unrepaired', 'تعذّر الإصلاح'), ('rejected_estimate', 'رفض الزبون التقدير'), ('no_fault', 'لا عطل'), ('replaced', 'استُبدل الجهاز')], default='', max_length=20),
        ),
    ]
