# Generated by Django 6.1.1 on 2026-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0021_replacement_slice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='returned_unit_state',
            field=models.CharField(blank=True, choices=[('held', 'محجوز عندنا'), ('with_supplier', 'عند المورد'), ('restocked', 'عاد للمخزن'), ('disposed', 'أُتلف')], default='', max_length=20),
        ),
    ]
