# Generated by Django 6.0.1 on 2026-07-09 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_tenantsettings_appearance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAttachment',
            fields=[
                ('id', models.AutoField(db_column='AttachmentID', primary_key=True, serialize=False)),
                ('related_table', models.CharField(db_column='RelatedTable', max_length=50)),
                ('related_id', models.IntegerField(db_column='RelatedID')),
                ('file_type', models.CharField(blank=True, db_column='FileType', max_length=50, null=True)),
                ('file_path', models.CharField(db_column='FilePath', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='UploadedAt')),
                # `tenant` كان غائباً عن هذه الهجرة رغم وجوده في النموذج منذ
                # البداية: مُكتشِف الهجرات لا يتتبّع حقول النماذج غير المُدارة،
                # فقلبُ managed وحده كان سيُنشئ جدولاً بلا عمود TenantID (P0-14).
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'system_attachments',
                # آمن على الإنتاج: هذه الهجرة مسجَّلة في django_migrations فلا
                # تُنفَّذ ثانيةً — الأثر محصور في البناء من صفر. نفس النمط
                # المطبَّق سلفاً على partners و tenants.
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('post', 'ترحيل'), ('unpost', 'إلغاء ترحيل'), ('duplicate', 'نسخ'), ('payment', 'دفعة'), ('view', 'عرض'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج')], max_length=20)),
                ('is_view', models.BooleanField(db_index=True, default=False)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'managed': True,
                'indexes': [models.Index(fields=['tenant', '-timestamp'], name='act_tenant_ts_idx'), models.Index(fields=['tenant', 'user', '-timestamp'], name='act_tenant_user_ts_idx'), models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='act_tenant_entity_idx')],
            },
        ),
    ]
