# Generated by Django 6.0.1 on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("partners", "0007_customer_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogPartner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.ForeignKey(
                    db_column="ActivityLogID",
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="partner_links",
                    to="core.activitylog",
                )),
                ("partner", models.ForeignKey(
                    db_column="PartnerID",
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="activity_links",
                    to="partners.partner",
                )),
            ],
            options={
                "db_table": "activity_log_partners",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "partner"),
                        name="uniq_activity_log_partner",
                    ),
                ],
            },
        ),
    ]
