# Generated by Django 6.0.3 on 2026-07-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylogpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assistant_lessons',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
