# Generated by Django 5.1.15 on 2026-08-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_developmentnote'),
        ('tenants', '0017_example_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_key', models.CharField(db_column='ModuleKey', max_length=40)),
                ('enabled', models.BooleanField(db_column='Enabled', default=False)),
                ('enabled_at', models.DateTimeField(blank=True, db_column='EnabledAt', null=True)),
                ('plan_note', models.CharField(blank=True, db_column='PlanNote', default='', max_length=120)),
                ('enabled_by', models.ForeignKey(blank=True, db_column='EnabledBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_tenant_modules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='module_licenses', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_modules',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module_key'), name='uniq_tenant_module')],
            },
        ),
    ]
