# Generated by Django 6.0.3 on 2026-08-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenantlimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentnote',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
