# Generated by Django 6.0.3 on 2026-08-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_development_note_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentnote',
            name='position',
        ),
    ]
