# Generated by Django 6.0.3 on 2026-08-15 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_development_note_completion_and_comments'),
        ('tenants', '0020_membership_ui_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=191, unique=True)),
                ('bytes', models.BigIntegerField(default=0)),
                ('resource_type', models.CharField(blank=True, default='', max_length=20)),
                ('folder', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('upload', 'رفع'), ('backfill', 'استرجاع أثري')], default='upload', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, db_column='TenantID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='UploadedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_assets',
                'managed': True,
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='asset_tenant_created_idx')],
            },
        ),
    ]
