# Generated by Django 5.1.15 on 2026-09-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenantasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_key', models.CharField(db_column='PlanKey', max_length=40)),
                ('monthly_price', models.DecimalField(db_column='MonthlyPrice', decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, db_column='Note', default='', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('updated_by', models.ForeignKey(blank=True, db_column='UpdatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plan_pricing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plan_pricing',
                'constraints': [models.UniqueConstraint(fields=('plan_key',), name='uniq_plan_pricing_key')],
            },
        ),
    ]
