# Generated by Django 6.1.1 on 2026-09-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_planpricing'),
        ('tenants', '0035_grant_import_procurement_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تنبيه'), ('high', 'خطورة عالية')], db_index=True, default='info', max_length=10)),
                ('actor_label', models.CharField(blank=True, default='', max_length=150)),
                ('tenant_label', models.CharField(blank=True, default='', max_length=200)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, db_column='ActorID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, db_column='TargetUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_targets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_column='TenantID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'platform_audit_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='paudit_tenant_ts_idx'), models.Index(fields=['action', '-created_at'], name='paudit_action_ts_idx')],
            },
        ),
    ]
