# Generated by Django 6.1.1 on 2026-09-27 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_platform_audit_log'),
        ('tenants', '0035_grant_import_procurement_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAccessGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('requested_scope', models.CharField(choices=[('read_only', 'قراءة فقط'), ('full', 'كامل (قراءة وتعديل)')], default='read_only', max_length=10)),
                ('requested_hours', models.PositiveSmallIntegerField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'بانتظار موافقة الشركة'), ('active', 'ساري'), ('rejected', 'مرفوض'), ('revoked', 'مسحوب'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=10)),
                ('scope', models.CharField(blank=True, choices=[('read_only', 'قراءة فقط'), ('full', 'كامل (قراءة وتعديل)')], default='', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_access_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_access_requests', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_access_revocations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='support_access_grants', to='tenants.tenant')),
            ],
            options={
                'db_table': 'support_access_grants',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'requested_by', 'status'], name='sagrant_lookup_idx')],
            },
        ),
    ]
