# Generated by Django 6.0.1 on 2026-02-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('PartnerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150, verbose_name='Name')),
                ('LegalName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal Name')),
                ('StreetAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address')),
                ('City', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('StateOrProvince', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province')),
                ('PostalCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('Country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('Type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('FreightForwarder', 'FreightForwarder'), ('CustomsBroker', 'CustomsBroker'), ('LocalTransporter', 'LocalTransporter')], max_length=50, verbose_name='Partner Type')),
                ('TaxNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Number')),
                ('Phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('OpeningBalance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Opening Balance')),
                ('OpeningBalanceDate', models.DateField(blank=True, null=True, verbose_name='Opening Balance Date')),
                ('is_deleted', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'partners',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('PartnerBankAccountID', models.AutoField(primary_key=True, serialize=False)),
                ('BankName', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('AccountNumber', models.CharField(max_length=50, verbose_name='Account Number')),
                ('IBAN', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
                ('SwiftCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='SWIFT Code')),
                ('BankAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Address')),
                ('BeneficiaryName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Beneficiary Name')),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'partner_bank_accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('Type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier')], max_length=50)),
            ],
            options={
                'db_table': 'partner_groups',
                'managed': True,
            },
        ),
    ]
