# Generated by Django 6.0.1 on 2026-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='partnerbankaccount',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='partnergroup',
            options={'managed': True},
        ),
    ]
