# Generated by Django 6.0.1 on 2026-03-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_account_parent_account_tenant_and_more'),
        ('partners', '0002_alter_partner_options_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt'),
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='partner',
            name='PartnerID',
            field=models.AutoField(db_column='PartnerID', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='PartnerID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='partnerbankaccount',
            name='PartnerBankAccountID',
            field=models.AutoField(db_column='PartnerBankAccountID', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='partnerbankaccount',
            old_name='PartnerBankAccountID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='partnerbankaccount',
            name='IsActive',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
        migrations.RenameField(
            model_name='partnerbankaccount',
            old_name='IsActive',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='partnergroup',
            name='GroupID',
            field=models.AutoField(db_column='GroupID', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='partnergroup',
            old_name='GroupID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='City',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='LegalName',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='OpeningBalance',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='OpeningBalanceDate',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='PostalCode',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='StateOrProvince',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='StreetAddress',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='TaxNumber',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='partnergroup',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='partnergroup',
            name='Type',
        ),
        # تُحذف الأعمدة القديمة قبل إعادة استخدام نفس db_column في الحقول الجديدة.
        migrations.RemoveField(
            model_name='partnerbankaccount',
            name='AccountNumber',
        ),
        migrations.RemoveField(
            model_name='partnerbankaccount',
            name='BankAddress',
        ),
        migrations.RemoveField(
            model_name='partnerbankaccount',
            name='BankName',
        ),
        migrations.RemoveField(
            model_name='partnerbankaccount',
            name='BeneficiaryName',
        ),
        migrations.RemoveField(
            model_name='partnerbankaccount',
            name='IBAN',
        ),
        migrations.RemoveField(
            model_name='partnerbankaccount',
            name='SwiftCode',
        ),
        migrations.AddField(
            model_name='partner',
            name='credit_limit',
            field=models.DecimalField(blank=True, db_column='CreditLimit', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='CurrencyID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='partner',
            name='group',
            field=models.ForeignKey(blank=True, db_column='GroupID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partners.partnergroup'),
        ),
        migrations.AddField(
            model_name='partner',
            name='image_path',
            field=models.CharField(blank=True, db_column='ImagePath', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='legal_name',
            field=models.CharField(blank=True, db_column='LegalName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='linked_account',
            field=models.ForeignKey(blank=True, db_column='LinkedAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_partners', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='partner',
            name='opening_balance',
            field=models.DecimalField(db_column='OpeningBalance', decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='partner',
            name='opening_balance_date',
            field=models.DateField(blank=True, db_column='OpeningBalanceDate', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('FreightForwarder', 'FreightForwarder'), ('CustomsBroker', 'CustomsBroker'), ('LocalTransporter', 'LocalTransporter')], db_column='Type', default='Customer', max_length=50),
        ),
        migrations.AddField(
            model_name='partner',
            name='postal_code',
            field=models.CharField(blank=True, db_column='PostalCode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='state_or_province',
            field=models.CharField(blank=True, db_column='StateOrProvince', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='street_address',
            field=models.CharField(blank=True, db_column='StreetAddress', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tax_number',
            field=models.CharField(blank=True, db_column='TaxNumber', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='account_number',
            field=models.CharField(db_column='AccountNumber', default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='bank_address',
            field=models.CharField(blank=True, db_column='BankAddress', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='bank_name',
            field=models.CharField(db_column='BankName', default='Bank', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='beneficiary_name',
            field=models.CharField(blank=True, db_column='BeneficiaryName', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='currency',
            field=models.ForeignKey(db_column='CurrencyID', default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='partner',
            field=models.ForeignKey(db_column='PartnerID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='swift_code',
            field=models.CharField(blank=True, db_column='SwiftCode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='account_payable',
            field=models.ForeignKey(blank=True, db_column='AccountPayableID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_groups', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='account_receivable',
            field=models.ForeignKey(blank=True, db_column='AccountReceivableID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_groups', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='group_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier')], db_column='Type', default='Customer', max_length=50),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(blank=True, db_column='Country', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(db_column='Name', default='New Partner', max_length=150),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partnergroup',
            name='name',
            field=models.CharField(db_column='Name', default='Group', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='iban',
            field=models.CharField(blank=True, db_column='IBAN', max_length=50, null=True),
        ),
        # يجب أن يأتي بعد إضافة الحقول التي يشير إليها (tenant/partner/account_number).
        migrations.AlterUniqueTogether(
            name='partnerbankaccount',
            unique_together={('tenant', 'partner', 'account_number')},
        ),
    ]
