# Generated by Django 6.0.3 on 2026-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_partner_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='source_discount_amount',
            field=models.DecimalField(db_column='SourceDiscountAmount', decimal_places=2, default=0, help_text='مبلغ خصم مصدر افتراضي على مستوى العميل', max_digits=18),
        ),
        migrations.AddField(
            model_name='partner',
            name='source_discount_percent',
            field=models.DecimalField(db_column='SourceDiscountPercent', decimal_places=2, default=0, help_text='نسبة خصم مصدر افتراضية على مستوى العميل (0-100)', max_digits=5),
        ),
    ]
