# Generated by Django 6.0.3 on 2026-05-23 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_n8_t7_account_default_cost_center'),
        ('partners', '0004_add_source_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='assigned_price_tier',
            field=models.PositiveSmallIntegerField(blank=True, db_column='AssignedPriceTier', help_text='شريحة الأسعار المخصصة (1-5) — تُستخدم في فواتير المبيعات', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='default_cost_center',
            field=models.ForeignKey(blank=True, db_column='DefaultCostCenterID', help_text='مركز التكلفة الافتراضي للشريك', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_with_default', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='partner',
            name='end_of_dealing_date',
            field=models.DateField(blank=True, db_column='EndOfDealingDate', help_text='تاريخ انتهاء التعامل — تحذير عند إضافة معاملات بعد هذا التاريخ', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='password_for_invoices',
            field=models.CharField(blank=True, db_column='PasswordForInvoices', help_text='كلمة مرور للفاتورة — يُتحقَّق منها عند إنشاء فاتورة', max_length=50, null=True),
        ),
    ]
