# Generated by Django 6.0.3 on 2026-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_n8_t8_partner_enrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='row_color',
            field=models.CharField(blank=True, db_column='RowColor', help_text='لون HEX (مثل #ff0000) لتلوين صف الشريك في الجداول', max_length=7, null=True),
        ),
    ]
