# Generated by Django 6.0.3 on 2026-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_customer_note_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='supplier_scope',
            field=models.CharField(blank=True, choices=[('local', 'مورد محلي'), ('international', 'مورد دولي (استيراد)')], db_column='SupplierScope', default='', help_text='نطاق المورد: محلي أو دولي (استيراد). فارغ = غير مصنَّف.', max_length=20),
        ),
    ]
