# Generated by Django 6.0.3 on 2026-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_classify_supplier_scope_from_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('FreightForwarder', 'FreightForwarder'), ('CustomsBroker', 'CustomsBroker'), ('LocalTransporter', 'LocalTransporter'), ('Carrier', 'Carrier')], db_column='Type', default='Customer', max_length=50),
        ),
    ]
