# Generated by Django 6.0.3 on 2026-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_phase5_p0_indexes'),
        ('partners', '0013_general_note_targets'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'partner_type', '-created_at'], name='idx_partner_tenant_type'),
        ),
    ]
