# Generated by Django 5.1.15 on 2026-09-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_portal', '0005_practicedocument_partner_practiceprogram_partner_and_more'),
        ('partners', '0014_partner_idx_partner_tenant_type'),
        ('tenants', '0029_alter_tenantbook_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='engagement',
            field=models.ForeignKey(blank=True, db_column='AccountantEngagementID', help_text='ارتباط مكتب محاسبة بشركة هذا الطرف على المنصة — بإذنها.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_clients', to='accountant_portal.accountantengagement'),
        ),
        migrations.AddField(
            model_name='partner',
            name='managed_tenant',
            field=models.ForeignKey(blank=True, db_column='ManagedTenantID', help_text='دفترٌ مُدار يملكه مكتب محاسبة لهذا الطرف (`Tenant.managed_by`).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by_partner_clients', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='partner',
            name='mobile',
            field=models.CharField(blank=True, db_column='Mobile', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='sector',
            field=models.CharField(blank=True, db_column='Sector', help_text='قطاع نشاط الطرف — يُستعمل في سجلّ عملاء مكتب المحاسبة.', max_length=120, null=True),
        ),
    ]
