# Generated by Django 5.1.15 on 2026-09-17 14:42

from django.db import migrations, models
from django.db.models import F


def copy_created_at_into_updated_at(apps, schema_editor):
    """الصفوف القائمة: «آخر تعديل» = لحظة الإنشاء — لا لحظة الهجرة.

    `AddField` لحقل `auto_now` يملأ الصفوف القائمة بلحظة تشغيل الهجرة (عمودٌ
    NOT NULL بقيمةٍ افتراضيّة تُحذف فوراً). هذا يستبدلها بـ`created_at` في
    `UPDATE` واحد، على MySQL وSQLite معاً.
    """
    apps.get_model('partners', 'Partner').objects.update(updated_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_partner_engagement_partner_managed_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt'),
        ),
        migrations.RunPython(copy_created_at_into_updated_at, migrations.RunPython.noop),
    ]
