# Generated by Django 6.1.1 on 2026-09-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_updated_at_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True, help_text='موقوف ⇒ مخفيٌّ من القوائم والمنتقيات (?include_inactive=1 يظهره)'),
        ),
    ]
