# Generated by Django 6.0.1 on 2026-02-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyID', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=3)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('IsBaseCurrency', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'currencies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('TenantID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=150)),
                ('SubscriptionPlan', models.CharField(choices=[('Basic', 'Basic'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], max_length=50)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Trial', 'Trial')], default='Trial', max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('DomainName', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tenants',
                'managed': True,
            },
        ),
    ]
