# Generated by Django 6.0.1 on 2026-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'managed': True},
        ),
    ]
