# Generated by Django 6.0.3 on 2026-05-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_cheque_invoice_links'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_primary', models.CharField(blank=True, db_column='CompanyNamePrimary', max_length=200, null=True)),
                ('company_name_sub', models.CharField(blank=True, db_column='CompanyNameSub', max_length=200, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('po_box', models.CharField(blank=True, db_column='POBox', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('licensed_dealer_no', models.CharField(blank=True, db_column='LicensedDealerNo', max_length=50, null=True)),
                ('income_tax_file_no', models.CharField(blank=True, db_column='IncomeTaxFileNo', max_length=50, null=True)),
                ('default_vat_rate', models.DecimalField(db_column='DefaultVatRate', decimal_places=2, default=16.0, max_digits=5)),
                ('default_source_discount_rate', models.DecimalField(db_column='DefaultSourceDiscountRate', decimal_places=2, default=0.0, max_digits=5)),
                ('fiscal_period_label', models.CharField(blank=True, db_column='FiscalPeriodLabel', max_length=100, null=True)),
                ('fiscal_period_start', models.DateField(blank=True, db_column='FiscalPeriodStart', null=True)),
                ('fiscal_period_end', models.DateField(blank=True, db_column='FiscalPeriodEnd', null=True)),
                ('mixture_auto_fill_enabled', models.BooleanField(db_column='MixtureAutoFillEnabled', default=False)),
                ('barcode_action', models.CharField(db_column='BarcodeAction', default='index', help_text="'index' = يفتح فهرس الأصناف, 'cashier' = يفتح فاتورة كاشير", max_length=20)),
                ('currency', models.ForeignKey(blank=True, db_column='CurrencyID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_settings', to='tenants.currency')),
                ('default_freight_credit_account', models.ForeignKey(blank=True, db_column='DefaultFreightCreditAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_settings_freight', to='accounting.account')),
                ('tenant', models.OneToOneField(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TenantBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('purchase_invoice', 'فاتورة شراء'), ('sales_return', 'مرجع بيع'), ('purchase_return', 'مرجع شراء'), ('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف'), ('multi_receipt', 'إيصال قبض متعدد'), ('multi_payment', 'سند صرف متعدد'), ('credit_note', 'إشعار دائن'), ('debit_note', 'إشعار مدين'), ('quotation', 'عرض سعر'), ('journal_entry', 'قيد محاسبة'), ('deal', 'صفقة'), ('shipment', 'شحنة'), ('clearance', 'تخليص جمركي')], db_column='DocumentType', max_length=30)),
                ('book_number', models.IntegerField(db_column='BookNumber', default=0)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('last_used_number', models.IntegerField(db_column='LastUsedNumber', default=0)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_books',
                'managed': True,
                'unique_together': {('tenant', 'document_type', 'book_number')},
            },
        ),
    ]
