# Generated by Django 6.0.3 on 2026-06-09 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_n0_tenant_settings_and_books'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('staff', 'موظف (Staff)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', default='staff', max_length=20)),
                ('is_default', models.BooleanField(db_column='IsDefault', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_company_memberships',
                'managed': True,
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
