# Generated by Django 6.0.3 on 2026-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_backfill_default_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='logo_url',
            field=models.CharField(blank=True, db_column='LogoUrl', max_length=500, null=True),
        ),
    ]
