# Generated by Django 6.0.3 on 2026-06-10 17:16

import django.db.models.deletion
from django.db import migrations, models


def create_main_branches(apps, schema_editor):
    """task11 M4 — كل شركة قائمة تحصل على فرع رئيسي تلقائياً."""
    Tenant = apps.get_model('tenants', 'Tenant')
    Branch = apps.get_model('tenants', 'Branch')
    for tenant in Tenant.objects.all():
        if not Branch.objects.filter(tenant=tenant, is_main=True).exists():
            Branch.objects.create(
                tenant=tenant, name='الفرع الرئيسي', code='MAIN',
                is_main=True, is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenantsettings_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('code', models.CharField(db_column='Code', help_text='رمز قصير يدخل في بادئة ترقيم المستندات، مثل MAIN أو NAB', max_length=20)),
                ('is_main', models.BooleanField(db_column='IsMain', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.tenant')),
            ],
            options={
                'db_table': 'branches',
                'managed': True,
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tenantbook',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantbook',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='BranchID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='tenants.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantbook',
            unique_together={('tenant', 'branch', 'document_type', 'book_number')},
        ),
        migrations.RunPython(create_main_branches, migrations.RunPython.noop),
    ]
