# Generated by Django 6.0.3 on 2026-07-24 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenantsettings_idle_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_column='PhoneNumber', help_text='أرقام فقط بصيغة دولية بلا +، مثل 972501234567', max_length=20, unique=True)),
                ('label', models.CharField(blank=True, db_column='Label', default='', help_text='اسم توضيحي اختياري (مثال: أشرف — مدير المبيعات)', max_length=100)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'whatsapp_contacts',
                'managed': True,
            },
        ),
    ]
