# Generated by Django 6.0.3 on 2026-07-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_whatsappcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanymembership',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', max_length=20)),
                ('permission_key', models.CharField(db_column='PermissionKey', max_length=64)),
                ('allowed', models.BooleanField(db_column='Allowed', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_role_permissions',
                'managed': True,
                'unique_together': {('tenant', 'role', 'permission_key')},
            },
        ),
    ]
