# Generated by Django 6.0.3 on 2026-07-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_usercompanymembership_role_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(db_column='PermissionKey', max_length=64)),
                ('allowed', models.BooleanField(db_column='Allowed', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('membership', models.ForeignKey(db_column='MembershipID', on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='tenants.usercompanymembership')),
            ],
            options={
                'db_table': 'member_permissions',
                'managed': True,
                'unique_together': {('membership', 'permission_key')},
            },
        ),
    ]
