# Generated by Django 5.1.15 on 2026-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_example_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('legal_accountant', 'محاسب قانوني خارجي'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercompanymembership',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('legal_accountant', 'محاسب قانوني خارجي'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', default='staff', max_length=20),
        ),
    ]
