# Generated by Django 6.0.3 on 2026-08-13 15:04

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_alter_rolepermission_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='store_slug',
            field=models.CharField(blank=True, db_column='StoreSlug', help_text='معرّف المتجر العام في الرابط /store/<slug> — فارغ يعني أن المتجر مقفل', max_length=40, null=True, unique=True, validators=[tenants.models.validate_store_slug]),
        ),
    ]
