# Generated by Django 6.0.3 on 2026-08-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenant_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompanymembership',
            name='ui_mode',
            field=models.CharField(choices=[('simple', 'الوضع السهل'), ('advanced', 'الواجهة المتقدمة')], db_column='UiMode', default='advanced', max_length=10),
        ),
    ]
