# Generated by Django 5.1.15 on 2026-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_membership_ui_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_ends_at',
            field=models.DateField(blank=True, db_column='SubscriptionEndsAt', help_text='آخر يوم يُسمح فيه بالكتابة — فارغ يعني اشتراكاً بلا تاريخ انتهاء', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='SubscriptionPlan',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Basic', 'Basic'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], max_length=50),
        ),
    ]
