# Generated by Django 5.1.15 on 2026-08-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_tenant_status_varchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='hr_absence_requires_shift',
            field=models.BooleanField(db_column='HrAbsenceRequiresShift', default=True, help_text='لا يُحتسب غياب إلا في يومٍ للموظف فيه وردية مُسنَدة'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('legal_accountant', 'محاسب قانوني خارجي'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('ess', 'موظف خدمة ذاتية (ESS)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='barcode_action',
            field=models.CharField(db_column='BarcodeAction', default='index', help_text="'index' = يفتح فهرس المنتجات, 'cashier' = يفتح فاتورة كاشير", max_length=20),
        ),
        migrations.AlterField(
            model_name='usercompanymembership',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('legal_accountant', 'محاسب قانوني خارجي'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('ess', 'موظف خدمة ذاتية (ESS)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', default='staff', max_length=20),
        ),
    ]
