# Generated by Django 5.1.15 on 2026-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_hr_settings_and_ess_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='template',
            field=models.CharField(db_column='Template', default='general', help_text='مفتاح قالب الشركة — يحدّد بذرة الحسابات والدفاتر عند الإنشاء', max_length=32),
        ),
    ]
