# Generated by Django 5.1.15 on 2026-09-02 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_alter_tenantbook_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHandoverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('expired', 'منتهي'), ('cancelled', 'ملغى')], db_column='Status', default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(db_column='ExpiresAt')),
                ('accepted_at', models.DateTimeField(blank=True, db_column='AcceptedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('book', models.ForeignKey(db_column='BookTenantID', help_text='الدفتر المُدار محلّ التسليم', on_delete=django.db.models.deletion.CASCADE, related_name='handover_requests', to='tenants.tenant')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(db_column='InvitedUserID', help_text='مستخدم العميل المدعوّ للقبول — هو وحده مَن يملك قبول هذا الطلب', on_delete=django.db.models.deletion.CASCADE, related_name='book_handover_requests', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(db_column='OfficeTenantID', help_text='مكتب المحاسبة المُرسِل — كما كان وقت إنشاء الطلب', on_delete=django.db.models.deletion.CASCADE, related_name='sent_handover_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_book_handover_requests',
                'managed': True,
                'indexes': [models.Index(fields=['book', 'status'], name='idx_bhr_book_status')],
            },
        ),
    ]
