# Generated by Django 5.1.15 on 2026-09-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_bookhandoverrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbook',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('purchase_invoice', 'فاتورة شراء'), ('sales_return', 'مرجع بيع'), ('purchase_return', 'مرجع شراء'), ('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف'), ('expense_voucher', 'سند مصروف'), ('revenue_voucher', 'سند إيراد'), ('multi_receipt', 'إيصال قبض متعدد'), ('multi_payment', 'سند صرف متعدد'), ('credit_note', 'إشعار دائن'), ('debit_note', 'إشعار مدين'), ('quotation', 'عرض سعر'), ('journal_entry', 'قيد محاسبة'), ('deal', 'صفقة'), ('shipment', 'شحنة'), ('clearance', 'تخليص جمركي')], db_column='DocumentType', max_length=30),
        ),
    ]
