# Generated by Django 5.1.15 on 2026-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_alter_tenantbook_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='voucher_account_entry_mode',
            field=models.CharField(choices=[('free', 'نصّ حرّ — يُنشأ الحساب إن لم يوجد'), ('linked', 'حساب من الشجرة إلزاماً')], db_column='VoucherAccountEntryMode', default='free', help_text='سندا المصروف والإيراد: نصّ حرّ يُنشئ حساباً، أم ربطٌ بحسابٍ قائم', max_length=10),
        ),
    ]
