# Generated by Django 5.1.15 on 2026-09-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_grant_store_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('legal_accountant', 'محاسب قانوني خارجي'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('ess', 'موظف خدمة ذاتية (ESS)'), ('field_staff', 'موظف ميداني (Field staff)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercompanymembership',
            name='role',
            field=models.CharField(choices=[('manager', 'مدير (Manager)'), ('accountant', 'محاسب (Accountant)'), ('legal_accountant', 'محاسب قانوني خارجي'), ('sales', 'موظف مبيعات (Sales)'), ('procurement', 'موظف مشتريات (Procurement)'), ('staff', 'موظف (Staff)'), ('ess', 'موظف خدمة ذاتية (ESS)'), ('field_staff', 'موظف ميداني (Field staff)'), ('viewer', 'مستعرض (Viewer)')], db_column='Role', default='staff', max_length=20),
        ),
    ]
