# Generated by Django 6.0.3 on 2026-07-26 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('food', 'طعام وشراب'), ('transport', 'مواصلات'), ('bills', 'فواتير واشتراكات'), ('health', 'صحة'), ('shopping', 'تسوّق'), ('family', 'أسرة وتعليم'), ('entertainment', 'ترفيه'), ('other', 'أخرى')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_personal_expenses',
                'indexes': [models.Index(fields=['user', '-date'], name='hrpe_user_date'), models.Index(fields=['user', 'is_paid'], name='hrpe_user_paid')],
            },
        ),
    ]
