# Generated by Django 6.0.3 on 2026-08-02 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def file_existing_expenses_into_a_first_sheet(apps, schema_editor):
    """المصاريف السابقة تسكن «الورقة 1» لصاحبها — لا صفوف بلا تبويب."""
    Expense = apps.get_model('hr', 'PersonalExpense')
    Sheet = apps.get_model('hr', 'PersonalExpenseSheet')
    user_ids = Expense.objects.filter(sheet__isnull=True).values_list('user_id', flat=True)
    for user_id in set(user_ids):
        sheet, _ = Sheet.objects.get_or_create(
            user_id=user_id, name='الورقة 1', defaults={'position': 0})
        Expense.objects.filter(user_id=user_id, sheet__isnull=True).update(sheet=sheet)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_personal_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalexpense',
            name='category',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='PersonalExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('position', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_expense_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_personal_expense_categories',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalExpenseSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_expense_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_personal_expense_sheets',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='hr.personalexpensesheet'),
        ),
        migrations.AddIndex(
            model_name='personalexpense',
            index=models.Index(fields=['user', 'sheet'], name='hrpe_user_sheet'),
        ),
        migrations.AlterUniqueTogether(
            name='personalexpensecategory',
            unique_together={('user', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='personalexpensesheet',
            unique_together={('user', 'name')},
        ),
        migrations.RunPython(
            file_existing_expenses_into_a_first_sheet,
            migrations.RunPython.noop,
        ),
    ]
