# Generated by Django 6.0.3 on 2026-08-08 08:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_cheques_align_nullable_columns'),
        ('hr', '0003_alter_personalexpense_category_and_more'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('pay_type', models.CharField(choices=[('monthly', 'دائم — راتب شهري'), ('hourly', 'جزئي — أجر بالساعة')], default='monthly', max_length=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('standard_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=5)),
                ('working_days_per_month', models.DecimalField(decimal_places=2, default=Decimal('26'), max_digits=5)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('national_id', models.CharField(blank=True, default='', max_length=40)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='حساب الموظف في الشجرة تحت «رواتب مستحقة للموظفين»', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_employees', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='ربط اختياري بمستخدم النظام — لا يلزم لكل موظف', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAdjustment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('absence', 'غياب'), ('late', 'تأخير')], default='absence', max_length=10)),
                ('days', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='أيام الغياب (0.5 = نصف يوم) — للنوع «غياب»', max_digits=5)),
                ('minutes', models.IntegerField(default=0, help_text='دقائق التأخير — للنوع «تأخير»')),
                ('is_deductible', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_adjustments', to='tenants.tenant')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_adjustments', to='hr.employee')),
            ],
            options={
                'db_table': 'hr_attendance_adjustments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_type', models.CharField(choices=[('monthly', 'دائم — راتب شهري'), ('hourly', 'جزئي — أجر بالساعة')], default='monthly', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='الراتب الشهري أو أجر الساعة وقت الاحتساب', max_digits=15)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('absence_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('late_minutes', models.IntegerField(default=0)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payslips', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_payslips',
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(blank=True, help_text='مصدر الدفع — صندوق أو بنك؛ الصندوق الافتراضي إن تُرك فارغاً', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='tenants.tenant')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hr.payslip')),
            ],
            options={
                'db_table': 'hr_payroll_payments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_work_logs',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='hremp_tenant_active'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='attendanceadjustment',
            index=models.Index(fields=['tenant', 'employee', '-date'], name='hraa_tenant_emp_date'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', '-period_start'], name='hrps_tenant_period'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['tenant', 'status'], name='hrps_tenant_status'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('employee', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['tenant', '-date'], name='hrpp_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['tenant', 'employee', '-date'], name='hrwl_tenant_emp_date'),
        ),
        migrations.AlterUniqueTogether(
            name='worklog',
            unique_together={('employee', 'date')},
        ),
    ]
