# Generated by Django 5.1.15 on 2026-08-26 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_attendanceadjustment_payslip_payrollpayment_and_more'),
        ('tenants', '0023_tenant_status_varchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employees', to='tenants.branch'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_departments', to='tenants.branch')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_departments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department'),
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_job_titles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_job_titles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title_ref',
            field=models.ForeignKey(blank=True, help_text='مسمّى وظيفي معرَّف — يتقدّم على الحقل النصّي حين يُختار', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.jobtitle'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'is_active'], name='hrdept_tenant_active'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('tenant', 'name')},
        ),
    ]
