# Generated by Django 5.1.15 on 2026-08-26 22:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_org_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('start1', models.TimeField(help_text='بداية الفترة الأولى')),
                ('end1', models.TimeField(help_text='نهاية الفترة الأولى')),
                ('start2', models.TimeField(blank=True, help_text='بداية الفترة الثانية (اختيارية)', null=True)),
                ('end2', models.TimeField(blank=True, null=True)),
                ('grace_minutes', models.PositiveIntegerField(default=0, help_text='دقائق سماحٍ قبل احتساب التأخير')),
                ('overtime_after_minutes', models.PositiveIntegerField(default=0, help_text='دقائق بعد الدوام المقرّر لا تُحتسب إضافياً')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='مضاعف أجر الساعة الإضافية', max_digits=4)),
                ('weekly_off_days', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_shifts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_shifts',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_m', models.PositiveIntegerField(default=150, help_text='نصف القطر المقبول حول الموقع بالأمتار')),
                ('require_geo', models.BooleanField(default=True, help_text='ارفض البصمة بلا موقع جغرافي داخل النطاق')),
                ('require_photo', models.BooleanField(default=False, help_text='ألزِم بصورةٍ لحظة التسجيل')),
                ('allow_ip_fallback', models.BooleanField(default=True, help_text='اقبل البصمة من عنوان IP مسموح حتى لو تعذّر الموقع')),
                ('ip_allowlist', models.TextField(blank=True, default='', help_text='عناوين IP أو نطاقات CIDR، واحدٌ في كل سطر أو مفصولةٌ بفاصلة')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_work_locations', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_work_locations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_work_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('in', 'دخول'), ('out', 'خروج')], max_length=4)),
                ('ts', models.DateTimeField(help_text='لحظة البصمة — واعيةٌ بالمنطقة الزمنية')),
                ('attendance_date', models.DateField(help_text='اليوم الذي تُنسب إليه — يوم بداية الوردية لا يوم الساعة')),
                ('source', models.CharField(choices=[('ess', 'الخدمة الذاتية'), ('manual', 'إدخال يدوي'), ('import', 'استيراد')], default='ess', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_m', models.PositiveIntegerField(blank=True, help_text='المسافة المحسوبة إلى موقع العمل وقت البصمة', null=True)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('accepted', models.BooleanField(default=True)),
                ('reject_reason', models.CharField(blank=True, choices=[('out_of_range', 'خارج نطاق موقع العمل'), ('no_location', 'لا يوجد موقع عمل مُعرَّف'), ('no_geo', 'لم يصل الموقع الجغرافي'), ('ip_blocked', 'الشبكة غير مسموحة'), ('photo_required', 'الصورة مطلوبة')], default='', max_length=20)),
                ('is_voided', models.BooleanField(default=False, help_text='أُبطلت إدارياً — تبقى في السجل ولا تدخل الحساب')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_check_events', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_events', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_check_events', to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_voided_checks', to=settings.AUTH_USER_MODEL)),
                ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_events', to='hr.worklocation')),
            ],
            options={
                'db_table': 'hr_check_events',
                'ordering': ['-ts', '-id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.ForeignKey(blank=True, help_text='موقع بصمته — فارغاً تُقبل بصمته عند أي موقع نشط', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.worklocation'),
        ),
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخّر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('holiday', 'عطلة رسمية'), ('off', 'عطلة أسبوعية'), ('unscheduled', 'بلا وردية')], default='absent', max_length=12)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_leave_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('scheduled_minutes', models.PositiveIntegerField(default=0)),
                ('absence_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('first_in', models.DateTimeField(blank=True, null=True)),
                ('last_out', models.DateTimeField(blank=True, null=True)),
                ('is_manual_override', models.BooleanField(default=False, help_text='صُحّح بيد مشرف — إعادة الحساب لا تكتسحه')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_attendance_days', to='tenants.tenant')),
                ('shift', models.ForeignKey(blank=True, help_text='لقطة الوردية المُسنَدة يوم الحساب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='hr.shift')),
            ],
            options={
                'db_table': 'hr_attendance_days',
                'ordering': ['-date', 'employee_id'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='hrad_tenant_date'), models.Index(fields=['tenant', 'employee', '-date'], name='hrad_tenant_emp_date')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.shift')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_shift_assignments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_shift_assignments',
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'employee', '-start_date'], name='hrsa_tenant_emp_start')],
            },
        ),
        migrations.AddIndex(
            model_name='worklocation',
            index=models.Index(fields=['tenant', 'is_active'], name='hrwloc_tenant_active'),
        ),
        migrations.AlterUniqueTogether(
            name='worklocation',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='checkevent',
            index=models.Index(fields=['tenant', 'employee', '-ts'], name='hrce_tenant_emp_ts'),
        ),
        migrations.AddIndex(
            model_name='checkevent',
            index=models.Index(fields=['tenant', 'attendance_date'], name='hrce_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='checkevent',
            index=models.Index(fields=['employee', 'attendance_date', 'accepted'], name='hrce_emp_date_ok'),
        ),
    ]
