# Generated by Django 5.1.15 on 2026-08-26 23:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_attendance_engine'),
        ('tenants', '0024_hr_settings_and_ess_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('open', 'قائمة'), ('settled', 'مسدَّدة'), ('cancelled', 'ملغاة')], default='open', max_length=10)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_advances', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_advances',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='advance',
            field=models.ForeignKey(blank=True, help_text='السلفة التي يصرفها هذا السند — فارغ في صرف الراتب المعتاد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hr.advance'),
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('leave', 'إجازة'), ('advance', 'سلفة'), ('expense', 'تسوية مصروف'), ('other', 'طلب آخر')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'مسودّة'), ('pending', 'قيد المراجعة'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='draft', max_length=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('installments', models.PositiveSmallIntegerField(blank=True, help_text='عدد أقساط سداد السلفة', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('attachment_url', models.URLField(blank=True, default='', max_length=500)),
                ('execution_date', models.DateField(blank=True, help_text='تاريخ تنفيذ الطلب بعد اعتماده', null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_requests_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_employee_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_employee_requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='advance',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance', to='hr.employeerequest'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_holidays', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_holidays',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=True, help_text='غير المدفوعة تُسجَّل إجازةً في السجل ويوماً مخصوماً في المال')),
                ('annual_grant', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='أيام تُمنح دفعةً واحدة مع بداية كل سنة', max_digits=6)),
                ('monthly_accrual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='أيام تُستحقّ عن كل شهر خدمة', max_digits=6)),
                ('max_days_per_request', models.PositiveIntegerField(default=0, help_text='صفر = بلا حدّ')),
                ('requires_balance', models.BooleanField(default=True, help_text='امنع الطلب حين لا يكفي الرصيد')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_leave_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_leave_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalanceAdjustment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, help_text='موجبٌ يمنح وسالبٌ يخصم', max_digits=6)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_leave_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_adjustments', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_leave_adjustments', to='tenants.tenant')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='hr.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_balance_adjustments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype'),
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, default='', max_length=10)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='ترتيب المستوى — 1 أولاً ثم 2 وهكذا')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_user', models.ForeignKey(blank=True, help_text='فارغاً = أي مستخدم يملك صلاحية اعتماد الطلبات', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_approval_rules', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_approval_rules', to='tenants.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_approval_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_approval_rules',
                'ordering': ['level', 'id'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='hrar_tenant_active')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'بانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=10)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approver_user', models.ForeignKey(blank=True, help_text='فارغاً = أي حاملٍ لصلاحية الاعتماد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hr.employeerequest')),
            ],
            options={
                'db_table': 'hr_approval_steps',
                'ordering': ['level', 'id'],
                'unique_together': {('request', 'level')},
            },
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['tenant', 'status'], name='hradv_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['tenant', 'employee'], name='hradv_tenant_emp'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['tenant', 'date'], name='hrhol_tenant_date'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('tenant', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='leavebalanceadjustment',
            index=models.Index(fields=['tenant', 'employee'], name='hrlba_tenant_emp'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['tenant', 'status'], name='hrer_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['tenant', 'employee', '-id'], name='hrer_tenant_emp'),
        ),
    ]
