# Generated by Django 5.1.15 on 2026-08-26 23:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_leave_requests_advances'),
        ('tenants', '0024_hr_settings_and_ess_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='advance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payslip',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='فارغ = عقد غير محدّد المدة', null=True)),
                ('pay_type', models.CharField(choices=[('monthly', 'دائم — راتب شهري'), ('hourly', 'جزئي — أجر بالساعة')], default='monthly', max_length=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('overtime_multiplier', models.DecimalField(blank=True, decimal_places=2, help_text='يتقدّم على مضاعف الوردية — فارغاً تسري قاعدة الوردية', max_digits=4, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودّة'), ('active', 'نشط'), ('expired', 'منتهٍ'), ('terminated', 'مُنهىً')], default='draft', max_length=12)),
                ('job_title', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('document_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_contracts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_contracts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_contracts',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('earning', 'استحقاق'), ('deduction', 'خصم')], default='earning', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.contract')),
            ],
            options={
                'db_table': 'hr_contract_components',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'مسودّة'), ('computed', 'محتسَب'), ('posted', 'مرحَّل')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_runs', to='tenants.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='hr.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_payroll_runs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'hr_payroll_runs',
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='hr.payrollrun'),
        ),
        migrations.CreateModel(
            name='PayslipAdvance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_links', to='hr.advance')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_links', to='hr.payslip')),
            ],
            options={
                'db_table': 'hr_payslip_advances',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='hrct_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employee', '-start_date'], name='hrct_emp_start'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['tenant', '-period_start'], name='hrrun_tenant_period'),
        ),
        migrations.AlterUniqueTogether(
            name='payslipadvance',
            unique_together={('payslip', 'advance')},
        ),
    ]
