# Generated by Django 6.0.3 on 2026-09-14 15:51

"""جهازٌ أساسيٌّ واحدٌ لكلّ مستخدم — قيدٌ تفرضه MySQL فعلاً.

‏**العمودُ المولَّدُ المخزَّنُ يعيد بناء الجدول في MySQL** (`ALGORITHM=COPY`)،
فالجدولُ مقفولٌ للكتابة طوال البناء. الجداولُ الثلاثةُ صغيرةٌ على الإنتاج
(قِيست يوم كتابة الهجرة: صفرُ حاضرين · ٣٩ جهازاً · ٢٤ مستودعاً) فلا أثرَ عمليّ.

والمكرّراتُ تُفحَص **قبل** البناء وتُرفع برسالةٍ تسمّي الصفوف، لا أن تسقط
الهجرةُ بـ`IntegrityError` عارٍ بعد نسخ الجدول كلِّه.
"""

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def refuse_existing_duplicates(apps, schema_editor):
    UserDevice = apps.get_model("hr", "UserDevice")
    clashes = (
        UserDevice.objects.filter(is_primary=True)
        .values("user_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .order_by("user_id")
    )
    offenders = [f"user={row['user_id']} ({row['n']} أجهزة)" for row in clashes]
    if offenders:
        raise RuntimeError(
            "‏لا يمكن فرضُ «جهازٌ أساسيٌّ واحدٌ لكلّ مستخدم»: يوجد مستخدمون "
            "بأكثر من جهازٍ أساسيّ — " + " · ".join(offenders) + ". "
            "أنزِل `is_primary` عن الزائد ثمّ أعِد تشغيل الهجرة."
        )



class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_migrate_tokens_to_user_devices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            refuse_existing_duplicates, migrations.RunPython.noop, elidable=False
        ),
        migrations.RemoveConstraint(
            model_name='userdevice',
            name='unique_primary_device_per_user',
        ),
        migrations.AddField(
            model_name='userdevice',
            name='primary_user_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(is_primary=True, then=models.F('user')), output_field=models.IntegerField()), output_field=models.IntegerField(), verbose_name='مفتاحُ الجهاز الأساسي'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('primary_user_key',), name='unique_primary_device_per_user'),
        ),
    ]
