# Generated by Django 5.1.15 on 2026-09-09 16:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, default='', max_length=100, verbose_name='التخصص')),
                ('capacity_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مستهدف السعة الموزون')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('on_leave', 'في إجازة'), ('offboarded', 'خارج الخدمة')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_employee', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موظف عمليات المنصة',
                'verbose_name_plural': 'موظفو عمليات المنصة',
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'معلق'), ('cancelled', 'ملغى')], default='active', max_length=20, verbose_name='حالة الاشتراك')),
                ('plan', models.CharField(default='standard', max_length=50, verbose_name='الباقة')),
                ('included_quota', models.PositiveIntegerField(default=0, verbose_name='العمليات المشمولة')),
                ('consumed_quota', models.PositiveIntegerField(default=0, verbose_name='العمليات المستهلكة')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='بداية الدورة')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='نهاية الدورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscription', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'اشتراك خدمة المتابعة',
                'verbose_name_plural': 'اشتراكات خدمة المتابعة',
            },
        ),
    ]
