# Generated by Django 5.1.15 on 2026-09-09 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0001_initial'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'معلق'), ('revoked', 'ملغى')], default='active', max_length=20, verbose_name='الحالة')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد')),
                ('created_membership', models.BooleanField(default=False, help_text='هل أنشأ هذا الارتباط عضوية المستخدم في الشركة أم كانت قائمة قبله؟', verbose_name='أنشأ العضوية')),
                ('previous_role', models.CharField(blank=True, default='', max_length=50, verbose_name='الدور السابق للعضوية المدارة')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التعليق')),
                ('suspension_reason', models.TextField(blank=True, default='', verbose_name='سبب التعليق')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('revocation_reason', models.TextField(blank=True, default='', verbose_name='سبب الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_platform_engagements', to=settings.AUTH_USER_MODEL, verbose_name='المُسنِد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='platform_ops.platformemployee', verbose_name='موظف العمليات')),
                ('managed_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_platform_engagements', to='tenants.usercompanymembership', verbose_name='العضوية المدارة')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_platform_engagements', to=settings.AUTH_USER_MODEL, verbose_name='مُلغي الارتباط')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_engagements', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'ارتباط موظف المنصة',
                'verbose_name_plural': 'ارتباطات موظفي المنصة',
            },
        ),
        migrations.CreateModel(
            name='AgentGrantedMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user_id', models.PositiveIntegerField(blank=True, help_text='يبقى ثابتاً ومقروءاً حتى لو حُذف المستخدم أو العضوية', null=True, verbose_name='معرف المستخدم الأصلي')),
                ('identity_snapshot', models.JSONField(blank=True, default=dict, help_text='لقطة ثابتة لبيانات المستخدم (الاسم، البريد، اسم المستخدم) وقت المنح', verbose_name='لقطة هوية المستخدم')),
                ('role_before', models.CharField(blank=True, default='', max_length=50, verbose_name='الدور السابق')),
                ('role_after', models.CharField(max_length=50, verbose_name='الدور الجديد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('acting_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_memberships', to='platform_ops.platformemployee', verbose_name='موظف المنصة الفاعل')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_granted_records', to='tenants.usercompanymembership', verbose_name='العضوية')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_granted_memberships', to='tenants.tenant', verbose_name='الشركة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_agent_granted_memberships', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المتأثر')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_memberships', to='platform_ops.engagement', verbose_name='الارتباط الفاعل')),
            ],
            options={
                'verbose_name': 'سجل عضوية ممنوحة من وكيل',
                'verbose_name_plural': 'سجلات العضويات الممنوحة من وكلاء',
            },
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['employee', 'status'], name='platform_op_employe_0cc282_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['tenant', 'status'], name='platform_op_tenant__b7a1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentgrantedmembership',
            index=models.Index(fields=['tenant', 'created_at'], name='platform_op_tenant__cdb615_idx'),
        ),
        migrations.AddIndex(
            model_name='agentgrantedmembership',
            index=models.Index(fields=['acting_employee', 'created_at'], name='platform_op_acting__62462d_idx'),
        ),
    ]
