# Generated by Django 5.1.15 on 2026-09-09 21:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0002_engagement_agentgrantedmembership_and_more'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان أمر العمل')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('kind', models.CharField(choices=[('data_entry', 'إدخال بيانات'), ('review', 'مراجعة'), ('sales', 'مبيعات'), ('service', 'خدمة'), ('inquiry', 'استفسار'), ('admin_directive', 'توجيه إداري')], default='data_entry', max_length=30, verbose_name='نوع أمر العمل')),
                ('source', models.CharField(choices=[('channel', 'قناة'), ('staff', 'موظف'), ('admin', 'إدارة')], default='staff', max_length=20, verbose_name='المصدر')),
                ('status', models.CharField(choices=[('received', 'مستلم'), ('screening', 'فرز وفحص'), ('data_entry', 'إدخال بيانات'), ('review', 'مراجعة'), ('approval', 'اعتماد'), ('closed', 'مغلق'), ('waiting_customer', 'بانتظار العميل'), ('cancelled', 'ملغى')], default='received', max_length=30, verbose_name='الحالة')),
                ('return_status', models.CharField(blank=True, choices=[('received', 'مستلم'), ('screening', 'فرز وفحص'), ('data_entry', 'إدخال بيانات'), ('review', 'مراجعة'), ('approval', 'اعتماد'), ('closed', 'مغلق'), ('waiting_customer', 'بانتظار العميل'), ('cancelled', 'ملغى')], default='', help_text='الحالة التي كان عليها أمر العمل قبل دخوله في انتظار العميل', max_length=30, verbose_name='حالة العودة بعد الانتظار')),
                ('waiting_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت دخول فترة الانتظار الحالية')),
                ('waiting_seconds_total', models.PositiveIntegerField(default=0, help_text='مجموع فترات انتظار رد العميل المحسومة من حساب الأجل', verbose_name='إجمالي ثواني الانتظار المتراكمة')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='نقطة بداية قياس الأجل (SLA)', verbose_name='وقت الاستلام')),
                ('approved_at', models.DateTimeField(blank=True, help_text='نقطة نهاية قياس الأجل (SLA)', null=True, verbose_name='وقت الاعتماد')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, help_text='نسخة ثابتة من سياسة الأجل السارية وقت الإنشاء', verbose_name='لقطة سياسة الأجل')),
                ('deadline_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الأجل النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assignee', models.ForeignKey(blank=True, help_text='مسؤول واحد فقط عن أمر العمل (يقبل فارغاً = في الطابور)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='platform_ops.platformemployee', verbose_name='المسؤول')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_work_orders', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'أمر عمل',
                'verbose_name_plural': 'أوامر العمل',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('internal', 'داخلي'), ('client_visible', 'مرئي للزبون')], help_text='إلزامي: داخلي لموظفي المنصة أو مرئي للزبون', max_length=20, verbose_name='مستوى الظهور')),
                ('content', models.TextField(verbose_name='نص التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_work_order_comments', to='tenants.tenant', verbose_name='الشركة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='platform_ops.workorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'تعليق أمر العمل',
                'verbose_name_plural': 'تعليقات أوامر العمل',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'ملاحظة'), ('structured_report', 'تقرير هيكلي'), ('attachment', 'مرفق')], default='note', max_length=30, verbose_name='نوع المُسلَّم')),
                ('review_status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة المراجعة')),
                ('content', models.TextField(blank=True, default='', verbose_name='المحتوى النصي')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='البيانات الهيكلية')),
                ('file_url', models.CharField(blank=True, default='', max_length=500, verbose_name='رابط المرفق')),
                ('content_snapshot', models.JSONField(blank=True, default=dict, help_text='لقطة محتوى التسليم وقت التقديم لا تتغير بتحرير المصدر لاحقاً', verbose_name='لقطة التسليم الثابتة')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='سبب الرفض')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المُسلِّم')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_work_order_deliverables', to='tenants.tenant', verbose_name='الشركة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='platform_ops.workorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'مُسلَّم أمر العمل',
                'verbose_name_plural': 'مُسلَّمات أوامر العمل',
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'status'], name='platform_op_tenant__119a57_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'kind'], name='platform_op_tenant__68052b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assignee', 'status'], name='platform_op_assigne_24ec97_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'created_at'], name='platform_op_tenant__69b837_idx'),
        ),
        migrations.AddIndex(
            model_name='workordercomment',
            index=models.Index(fields=['work_order', 'visibility', 'created_at'], name='platform_op_work_or_037657_idx'),
        ),
        migrations.AddIndex(
            model_name='workordercomment',
            index=models.Index(fields=['tenant', 'created_at'], name='platform_op_tenant__eaa543_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderdeliverable',
            index=models.Index(fields=['work_order', 'review_status'], name='platform_op_work_or_a78e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderdeliverable',
            index=models.Index(fields=['tenant', 'created_at'], name='platform_op_tenant__51af3e_idx'),
        ),
    ]
