# Generated by Django 5.1.15 on 2026-09-09 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0003_workorder_workordercomment_workorderdeliverable_and_more'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='attachment_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='معرفات المرفقات'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'واتساب'), ('telegram', 'تيليجرام'), ('email', 'بريد إلكتروني'), ('api', 'واجهة برمجية (API)'), ('webhook', 'ويب هوك'), ('portal', 'بوابة')], default='', max_length=50, verbose_name='قناة الاستقبال'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, help_text='معرف فريد للرسالة/الطلب من القناة الخارجية لضمان idempotency', max_length=128, null=True, verbose_name='المرجع الخارجي'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intake_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='حمولة الاستقبال الأصلية'),
        ),
        migrations.CreateModel(
            name='IntegrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'واتساب'), ('telegram', 'تيليجرام'), ('email', 'بريد إلكتروني'), ('api', 'واجهة برمجية (API)'), ('webhook', 'ويب هوك'), ('portal', 'بوابة')], default='whatsapp', max_length=50, verbose_name='القناة')),
                ('token_hash', models.CharField(db_index=True, help_text='تجزئة SHA-256 للرمز الخام؛ الرمز الأصلي لا يُحفظ في القاعدة أبداً', max_length=64, unique=True, verbose_name='مهشر الرمز')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('revoked', 'مبطل')], default='active', max_length=20, verbose_name='الحالة')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='تسمية المفتاح')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإبطال')),
                ('revocation_reason', models.TextField(blank=True, default='', verbose_name='سبب الإبطال')),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التدوير')),
                ('revocation_history', models.JSONField(blank=True, default=list, help_text='كل إبطال سابق لهذا الصف: متى وبأمر من ولماذا. الفرادة على (شركة، قناة) غير مشروطة فالصف واحد، ولولا هذا السجل لمحا إصدارُ مفتاحٍ جديد سببَ إبطال سابقه.', verbose_name='سجل الإبطالات السابقة')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر استخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مُبطِل المفتاح')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_integration_keys', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مفتاح قناة الاستقبال',
                'verbose_name_plural': 'مفاتيح قنوات الاستقبال',
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='integration_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='platform_ops.integrationkey', verbose_name='مفتاح التكامل'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['channel', 'external_ref'], name='platform_op_channel_2cc3c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel', 'external_ref'), name='platform_ops_workorder_tenant_channel_extref_uniq'),
        ),
        migrations.AddIndex(
            model_name='integrationkey',
            index=models.Index(fields=['tenant', 'status'], name='platform_op_tenant__c6654f_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationkey',
            index=models.Index(fields=['channel', 'status'], name='platform_op_channel_8c1dff_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationkey',
            constraint=models.UniqueConstraint(fields=('tenant', 'channel'), name='platform_ops_integrationkey_tenant_channel_uniq'),
        ),
    ]
