# Generated by Django 5.1.15 on 2026-09-10 00:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0004_workorder_attachment_ids_workorder_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(db_index=True, help_text='تخصص موظفي المنصة المطبق عليه هذا الملف التعريفي', max_length=100, unique=True, verbose_name='التخصص')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='تسمية السياسة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('weights', models.JSONField(blank=True, default=dict, help_text='أوزان المحاور الخمسة: quality, sla_compliance, productivity, speed_efficiency, sales_value', verbose_name='أوزان المحاور الخمسة')),
                ('targets', models.JSONField(blank=True, default=dict, help_text='المستهدفات الرقمية للمقاييس (مثل مستهدف السعة، مستهدف المبيعات، إلخ)', verbose_name='مستهدفات المقاييس')),
                ('sla_hours_by_kind', models.JSONField(blank=True, default=dict, help_text='خريطة ساعات الأجل الافتراضية لكل نوع أمر عمل', verbose_name='ساعات الأجل حسب نوع أمر العمل')),
                ('min_sample_size', models.PositiveIntegerField(default=5, help_text='الحد الأدنى لحجم العينة لتوليد درجة مركبة وترتيب رسمي', verbose_name='الحد الأدنى لحجم العينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف سياسة الأداء',
                'verbose_name_plural': 'ملفات سياسات الأداء',
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='طابعُ حدثٍ ثابت. ومعدّلُ إعادة العمل كان يُنسَب للشهر عبر `updated_at` وهو `auto_now`: لمسةٌ لاحقةٌ للصفّ تنقله بين الشهور فيتغيّر رقمُ شهرٍ التُقط.', null=True, verbose_name='وقت الإلغاء'),
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سنة التقييم')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='شهر التقييم')),
                ('status', models.CharField(choices=[('calculated', 'محسوبة'), ('insufficient_data', 'بيانات غير كافية')], default='calculated', max_length=30, verbose_name='حالة اللقطة')),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, help_text='الدرجة المركبة الرسمية من 100؛ تكون NULL إذا كانت البيانات غير كافية', max_digits=5, null=True, verbose_name='الدرجة المركبة')),
                ('sample_size', models.PositiveIntegerField(default=0, help_text='عدد أوامر العمل المعتمدة الداخلة في التقييم', verbose_name='حجم العينة الفعلي')),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, help_text='لقطة مجمدة من أوزان المحاور ومستهدفاتها السارية وقت الالتقاط', verbose_name='لقطة السياسة والأوزان')),
                ('metrics_data', models.JSONField(blank=True, default=dict, help_text='تفاصيل المقاييس الستة مع البسط والمقام المعلن وحجم العينة', verbose_name='بيانات المقاييس الستة ومقاماتها')),
                ('axes_data', models.JSONField(blank=True, default=dict, help_text='تفاصيل المحاور الخمسة ودرجاتها وأوزانها بعد إعادة التوزيع', verbose_name='بيانات المحاور وتوزيع الأوزان')),
                ('rework_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='نسبة أوامر العمل الملغاة كرقم تشخيصي منفصل لا يُخصم من الدرجة المركبة', max_digits=5, verbose_name='معدل إعادة العمل')),
                ('processed_sales_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='مجموع مبيعات أوامر العمل المعتمدة كمؤشر عرض لا استحقاق', max_digits=14, verbose_name='قيمة مبيعات عالجها')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الالتقاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ملتقط التقرير')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='platform_ops.platformemployee', verbose_name='موظف العمليات')),
                ('policy_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='platform_ops.policyprofile', verbose_name='ملف السياسة المعتمد')),
            ],
            options={
                'verbose_name': 'لقطة أداء موظف المنصة',
                'verbose_name_plural': 'لقطات أداء موظفي المنصة',
                'indexes': [models.Index(fields=['employee', 'period_year', 'period_month'], name='platform_op_employe_150884_idx'), models.Index(fields=['period_year', 'period_month'], name='platform_op_period__361a92_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_year', 'period_month'), name='platform_ops_perfsnapshot_employee_period_uniq')],
            },
        ),
    ]
