# Generated by Django 6.0.3 on 2026-09-10 01:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0005_policyprofile_workorder_cancelled_at_and_more'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('work_order_transition', 'تغيير حالة أمر العمل'), ('deliverable_submit', 'تقديم مُسلَّم'), ('deliverable_review', 'مراجعة مُسلَّم'), ('comment_added', 'إضافة تعليق'), ('engagement_assigned', 'إسناد ارتباط'), ('engagement_suspended', 'تعليق ارتباط'), ('engagement_revoked', 'إلغاء ارتباط'), ('snapshot_captured', 'التقاط لقطة أداء'), ('other', 'أخرى')], max_length=50, verbose_name='نوع النشاط')),
                ('entity_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرف الكيان')),
                ('description', models.TextField(blank=True, default='', verbose_name='وصف النشاط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل إضافية')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ ووقت النشاط')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='platform_ops.platformemployee', verbose_name='موظف العمليات')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_activity_logs', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'سجل نشاط عمليات المنصة',
                'verbose_name_plural': 'سجلات أنشطة عمليات المنصة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='platform_op_employe_c3afa8_idx'), models.Index(fields=['-created_at'], name='platform_op_created_39871a_idx'), models.Index(fields=['tenant', '-created_at'], name='platform_op_tenant__50c277_idx'), models.Index(fields=['action', '-created_at'], name='platform_op_action_e0e6d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sla_breach', 'تجاوز أجل'), ('low_score', 'تقييم منخفض'), ('quota_exceeded', 'تجاوز باقة')], max_length=50, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='نص الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_notifications', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'إشعار عمليات المنصة',
                'verbose_name_plural': 'إشعارات عمليات المنصة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='platform_op_recipie_056bce_idx'), models.Index(fields=['recipient', '-created_at'], name='platform_op_recipie_688400_idx')],
            },
        ),
    ]
