# Generated by Django 5.1.15 on 2026-09-10 03:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0006_platformactivitylog_platformnotification'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True, help_text='حقل تاريخ صريح ليوم العمل المُقيَّم', verbose_name='تاريخ الخدمة')),
                ('stars', models.PositiveSmallIntegerField(help_text='من 1 إلى 5 نجوم', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم بالنجوم')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظة التقييم')),
                ('edited_once', models.BooleanField(default=False, help_text='يسمح بالتعديل مرة واحدة فقط وتُرفض المحاولة الثانية', verbose_name='عُدّل مرة واحدة')),
                ('source', models.CharField(choices=[('token', 'رابط يومي'), ('in_app', 'داخل التطبيق')], default='in_app', max_length=20, verbose_name='مصدر التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ratings', to='platform_ops.platformemployee', verbose_name='موظف العمليات')),
                ('rated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المقيِّم')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ratings', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'تقييم يومي',
                'verbose_name_plural': 'تقييمات يومية',
            },
        ),
        migrations.CreateModel(
            name='DailyRatingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True, verbose_name='تاريخ الخدمة')),
                ('token_hash', models.CharField(db_index=True, help_text='تجزئة SHA-256 للرمز الخام؛ الرمز الأصلي لا يُحفظ في القاعدة أبداً', max_length=64, unique=True, verbose_name='مهشر الرمز')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='تاريخ الانتهاء')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإبطال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rating_tokens', to='platform_ops.platformemployee', verbose_name='موظف العمليات')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='platform_ops.dailyrating', verbose_name='التقييم المرتبط')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rating_tokens', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'رمز التقييم اليومي',
                'verbose_name_plural': 'رموز التقييم اليومي',
            },
        ),
        migrations.AddIndex(
            model_name='dailyrating',
            index=models.Index(fields=['tenant', 'service_date'], name='platform_op_tenant__1c2631_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyrating',
            index=models.Index(fields=['employee', 'service_date'], name='platform_op_employe_c1396d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyrating',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'service_date'), name='platform_ops_dailyrating_tenant_employee_date_uniq'),
        ),
        migrations.AddIndex(
            model_name='dailyratingtoken',
            index=models.Index(fields=['tenant', 'service_date'], name='platform_op_tenant__6d6b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyratingtoken',
            index=models.Index(fields=['employee', 'service_date'], name='platform_op_employe_3c1ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyratingtoken',
            index=models.Index(fields=['expires_at'], name='platform_op_expires_53fb88_idx'),
        ),
    ]
