# Generated by Django 5.1.15 on 2026-09-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0007_dailyrating_dailyratingtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancesnapshot',
            name='axes_data',
            field=models.JSONField(blank=True, default=dict, help_text='تفاصيل المحاور ودرجاتها وأوزانها بعد إعادة التوزيع', verbose_name='بيانات المحاور وتوزيع الأوزان'),
        ),
        migrations.AlterField(
            model_name='policyprofile',
            name='weights',
            field=models.JSONField(blank=True, default=dict, help_text='أوزان المحاور الرسمية الخمسة: kpi_results, quality, customer_rating, sla_compliance, attendance_regularity. المحور غير المنطبق يُسقط ويُعاد توزيع وزنه بالتناسب، فلا يلزم أن يجمع المكتوب هنا مئةً بالضبط.', verbose_name='أوزان محاور التقييم'),
        ),
    ]
