# Generated by Django 5.1.15 on 2026-09-10 22:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_partner_engagement_partner_managed_tenant_and_more'),
        ('platform_ops', '0008_axis_weights_help_text'),
        ('sales', '0043_customerpayment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='billing_customer',
            field=models.ForeignKey(blank=True, help_text='سجل العميل التابع لشركة المنصة المفوترة الذي تصدر باسمه فواتير الخدمة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_service_subscriptions', to='partners.partner', verbose_name='عميل الفوترة في شركة المنصة'),
        ),
        migrations.CreateModel(
            name='SubscriptionBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='بداية دورة الفوترة')),
                ('period_end', models.DateField(verbose_name='نهاية دورة الفوترة')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الرسم الشهري الثابت')),
                ('included_quota', models.PositiveIntegerField(default=0, verbose_name='العمليات المشمولة')),
                ('consumed_quota', models.PositiveIntegerField(default=0, verbose_name='العمليات المستهلكة')),
                ('overage_units', models.PositiveIntegerField(default=0, verbose_name='العمليات الزائدة')),
                ('overage_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر العملية الزائدة')),
                ('overage_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='رسوم العمليات الزائدة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_billing_records', to='sales.salesinvoice', verbose_name='فاتورة المبيعات')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='platform_ops.servicesubscription', verbose_name='اشتراك الخدمة')),
            ],
            options={
                'verbose_name': 'سجل فوترة اشتراك',
                'verbose_name_plural': 'سجلات فوترة الاشتراكات',
                'indexes': [models.Index(fields=['subscription', 'period_start', 'period_end'], name='platform_op_subscri_9ece6b_idx'), models.Index(fields=['invoice'], name='platform_op_invoice_aadc9e_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'period_start', 'period_end'), name='platform_ops_sub_billing_sub_period_uniq')],
            },
        ),
    ]
