# Generated by Django 5.1.15 on 2026-09-10 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0009_servicesubscription_billing_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوظيفة')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('requirements', models.TextField(blank=True, default='', verbose_name='المتطلبات')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='المكان')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد'), ('temporary', 'مؤقت')], default='', max_length=30, verbose_name='نوع الدوام')),
                ('salary_range', models.CharField(blank=True, default='', max_length=120, verbose_name='نطاق الراتب')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='مفتاح الرابط العام')),
                ('is_open', models.BooleanField(db_index=True, default=True, verbose_name='مفتوحة للتقديم')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ انتهاء الرابط')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مُنشئ الإعلان')),
            ],
            options={
                'verbose_name': 'إعلان وظيفة منصي',
                'verbose_name_plural': 'إعلانات الوظائف المنصية',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المتقدم')),
                ('phone', models.CharField(max_length=40, verbose_name='رقم التواصل')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('about', models.TextField(blank=True, default='', verbose_name='نبذة عن المتقدم')),
                ('cv_url', models.URLField(blank=True, default='', max_length=500, verbose_name='رابط السيرة')),
                ('cv_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم ملف السيرة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('screening', 'فرز أولي'), ('interview', 'مقابلة'), ('offered', 'عرض عمل'), ('hired', 'مقبول'), ('rejected', 'مرفوض')], db_index=True, default='new', max_length=30, verbose_name='الحالة')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='التقييم')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات مسؤول التوظيف')),
                ('reference_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hired_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_ops.platformemployee', verbose_name='سجل موظف المنصة')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='platform_ops.jobposting', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'متقدم على وظيفة منصية',
                'verbose_name_plural': 'المتقدمون على الوظائف المنصية',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRecruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_recruiter', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مسؤول توظيف المنصة',
                'verbose_name_plural': 'مسؤولو توظيف المنصة',
            },
        ),
        migrations.CreateModel(
            name='JobApplicantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='تجزئة SHA-256 للرمز الخام؛ الرمز الأصلي لا يُحفظ في القاعدة أبداً', max_length=64, unique=True, verbose_name='مهشر الرمز')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='تاريخ الانتهاء')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإبطال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='platform_ops.jobapplicant', verbose_name='المتقدم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مُرسل الدعوة')),
            ],
            options={
                'verbose_name': 'دعوة توظيف منصية',
                'verbose_name_plural': 'دعوات التوظيف المنصية',
                'indexes': [models.Index(fields=['expires_at'], name='platform_op_expires_b1f8d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_open', '-created_at'], name='platform_op_is_open_8c49c2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicant',
            index=models.Index(fields=['job', 'status', '-created_at'], name='platform_op_job_id_caf44f_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplicant',
            constraint=models.UniqueConstraint(fields=('reference_code',), name='platform_ops_jobapplicant_ref_uniq'),
        ),
    ]
