# Generated by Django 5.1.15 on 2026-09-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0010_jobposting_jobapplicant_platformrecruiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='specialty',
            field=models.CharField(blank=True, default='', help_text='يجب أن يطابق تخصصاً في ملفات السياسة (PolicyProfile.specialty) ليُحتسب الأداء بسياسته', max_length=100, verbose_name='التخصص المنصي'),
        ),
    ]
