# Generated by Django 5.1.15 on 2026-09-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0011_jobposting_specialty'),
        ('sales', '0043_customerpayment_kind_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplicant',
            name='platform_ops_jobapplicant_ref_uniq',
        ),
        migrations.RemoveIndex(
            model_name='jobapplicantinvitation',
            name='platform_op_expires_b1f8d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionbillingrecord',
            name='platform_op_subscri_9ece6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscriptionbillingrecord',
            name='platform_op_invoice_aadc9e_idx',
        ),
        migrations.AlterField(
            model_name='subscriptionbillingrecord',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_billing_records', to='sales.salesinvoice', verbose_name='فاتورة المبيعات'),
        ),
    ]
