# Generated by Django 5.1.15 on 2026-09-11 21:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_product_reference_image'),
        ('platform_ops', '0012_remove_jobapplicant_platform_ops_jobapplicant_ref_uniq_and_more'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='billing_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_service_billing_subscriptions', to='tenants.tenant', verbose_name='شركة فوترة المنصة الملتقطة'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='سبب الإلغاء'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='fixed_fee_product',
            field=models.ForeignKey(blank=True, help_text='يُلتقط من السياسة لحظة بدء التجربة أو التفعيل؛ الفوترة الشهرية تقرؤه ما لم يُمرَّر تجاوز صريح.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product', verbose_name='صنف الرسم الشهري الملتقط'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='overage_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product', verbose_name='صنف العمليات الزائدة الملتقط'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='pre_suspension_status',
            field=models.CharField(blank=True, default='', help_text='تحفظ لحظة التعليق كي يعيدها الاستئناف؛ لا تُقرأ إلا من خدمة الاستئناف.', max_length=20, verbose_name='الحالة قبل التعليق'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='scheduled_cancellation_date',
            field=models.DateField(blank=True, help_text='نهاية الدورة أو التجربة الحالية؛ يُطبَّق تلقائياً بأمر الفوترة الشهري.', null=True, verbose_name='تاريخ الإلغاء المجدول'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='subscription_policy_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='نسخة سياسة الاشتراك الملتقطة'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='أيام التجربة الملتقطة'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='نهاية التجربة'),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='بداية التجربة'),
        ),
        migrations.AlterField(
            model_name='servicesubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'تجربة'), ('active', 'نشط'), ('suspended', 'معلق'), ('cancelled', 'ملغى')], default='active', max_length=20, verbose_name='حالة الاشتراك'),
        ),
        migrations.CreateModel(
            name='ServiceSubscriptionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='رقم النسخة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('retired', 'منتهية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('plan', models.CharField(blank=True, default='', help_text='فارغ = نسخة عامة لكل الخطط؛ اسم خطة = نسخة خاصة بها تغلب العامة.', max_length=50, verbose_name='نطاق الخطة')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الرسم الشهري الافتراضي')),
                ('included_quota', models.PositiveIntegerField(default=300, verbose_name='الحصة الافتراضية المشمولة')),
                ('trial_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='أيام التجربة الافتراضية')),
                ('overage_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر العملية الزائدة الافتراضي')),
                ('activation_reason', models.CharField(blank=True, default='', help_text='إلزامي لحظة تفعيل المسودة؛ يبقى في الصف بعد التفعيل.', max_length=500, verbose_name='سبب التفعيل')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة من')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة إلى')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_platform_subscription_policies', to=settings.AUTH_USER_MODEL, verbose_name='فعّلها')),
                ('billing_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_subscription_policies', to='tenants.tenant', verbose_name='شركة فوترة المنصة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_subscription_policies', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('fixed_fee_product', models.ForeignKey(blank=True, help_text='صنف خدمي في شركة فوترة المنصة؛ إلزامي لحظة التفعيل.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product', verbose_name='صنف الرسم الشهري')),
                ('overage_product', models.ForeignKey(blank=True, help_text='صنف خدمي في شركة فوترة المنصة؛ إلزامي عند سعر تجاوز أكبر من صفر.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product', verbose_name='صنف العمليات الزائدة')),
            ],
            options={
                'verbose_name': 'سياسة اشتراك خدمة المنصة',
                'verbose_name_plural': 'سياسات اشتراك خدمة المنصة',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('trial_started', 'بدء تجربة'), ('activated', 'تفعيل مدفوع'), ('trial_converted', 'تحويل التجربة إلى مدفوع'), ('settings_updated', 'تعديل إعدادات تجارية'), ('suspended', 'تعليق'), ('resumed', 'استئناف'), ('cancellation_scheduled', 'جدولة إلغاء'), ('cancellation_withdrawn', 'سحب جدولة الإلغاء'), ('cancelled', 'إلغاء')], max_length=30, verbose_name='الإجراء')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='من حالة')),
                ('to_status', models.CharField(blank=True, default='', max_length=20, verbose_name='إلى حالة')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='السبب')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل بلا بيانات شخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_subscription_events', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform_ops.servicesubscription', verbose_name='اشتراك الخدمة')),
            ],
            options={
                'verbose_name': 'حدث اشتراك خدمة المنصة',
                'verbose_name_plural': 'أحداث اشتراك خدمة المنصة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', '-created_at'], name='platform_op_subscri_3751e0_idx'), models.Index(fields=['correlation_id'], name='platform_op_correla_537217_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscriptionPolicyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء مسودة'), ('updated', 'تعديل مسودة'), ('cloned', 'استنساخ مسودة'), ('activated', 'تفعيل سياسة'), ('retired', 'إنهاء سياسة')], max_length=20, verbose_name='الإجراء')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل بلا بيانات شخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_subscription_policy_events', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform_ops.servicesubscriptionpolicy', verbose_name='سياسة الاشتراك')),
            ],
            options={
                'verbose_name': 'حدث سياسة اشتراك خدمة المنصة',
                'verbose_name_plural': 'أحداث سياسات اشتراك خدمة المنصة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy', '-created_at'], name='platform_op_policy__889a3e_idx'), models.Index(fields=['correlation_id'], name='platform_op_correla_bd35c4_idx')],
            },
        ),
    ]
