# Generated by Django 5.1.15 on 2026-09-11 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0013_service_subscription_lifecycle'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='capacity_override_reason',
            field=models.CharField(blank=True, default='', help_text='يُملأ فقط حين يُسند/يُنقل الموظف رغم تجاوز `capacity_target`.', max_length=500, verbose_name='سبب تجاوز الطاقة'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='end_reason',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='سبب الانتهاء'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='طابعُ نهاية الارتباط العامّ (إلغاءً كان أو نقلاً) — يرافق `end_reason` دوماً.', null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='kind',
            field=models.CharField(choices=[('standard', 'عادي'), ('onboarding', 'تهيئة مؤقتة')], default='standard', help_text='onboarding يتخطّى شرط الأساس المعتمد لفترة محدودة موسومة ومؤرَّخة.', max_length=20, verbose_name='نوع الارتباط'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='onboarding_expires_at',
            field=models.DateTimeField(blank=True, help_text='إلزامي لـkind=onboarding — أقصاه MAX_ONBOARDING_DAYS من الإسناد.', null=True, verbose_name='انتهاء التهيئة المؤقتة'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='predecessor',
            field=models.ForeignKey(blank=True, help_text='الارتباط الذي حلّ هذا محلّه عبر `transfer_engagement` — تاريخ النقل يبقى مقروءاً.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='platform_ops.engagement', verbose_name='الارتباط السابق'),
        ),
        migrations.CreateModel(
            name='CompanyHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('baseline', 'تأسيسي'), ('monthly', 'شهري')], default='baseline', max_length=20, verbose_name='نوع الفحص')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد')], default='draft', max_length=20, verbose_name='الحالة')),
                ('period', models.DateField(help_text='أول يوم في الشهر للفحص الشهري، أو تاريخ الفحص نفسه للتأسيسي.', verbose_name='الفترة')),
                ('complexity', models.CharField(blank=True, choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع')], default='', help_text='تقدير السوبر أدمن لحمل الشركة — إلزامي قبل الاعتماد.', max_length=10, verbose_name='تقدير التعقيد')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_health_checks', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فحص صحة الشركة',
                'verbose_name_plural': 'فحوص صحة الشركات',
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyHealthCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='رمز البند')),
                ('status', models.CharField(choices=[('healthy', 'سليم'), ('follow_up', 'يحتاج متابعة'), ('risk', 'خطر'), ('not_applicable', 'لا ينطبق')], default='follow_up', max_length=20, verbose_name='حالة البند')),
                ('evidence_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='قيمة الدليل الرقمي')),
                ('evidence_note', models.CharField(blank=True, default='', max_length=500, verbose_name='ملاحظة الدليل')),
                ('source', models.CharField(choices=[('auto', 'آلي'), ('manual', 'يدوي')], default='manual', max_length=10, verbose_name='مصدر القياس')),
                ('mandatory', models.BooleanField(default=True, verbose_name='إلزامي للاعتماد')),
                ('action', models.CharField(blank=True, default='', max_length=500, verbose_name='الإجراء المطلوب')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='الموعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('health_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform_ops.companyhealthcheck', verbose_name='الفحص')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_check_items', to='platform_ops.workorder', verbose_name='أمر العمل المرتبط')),
            ],
            options={
                'verbose_name': 'بند فحص صحة الشركة',
                'verbose_name_plural': 'بنود فحوص صحة الشركات',
            },
        ),
        migrations.CreateModel(
            name='CustomerAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateField(verbose_name='تاريخ الاكتساب')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('acquired_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquired_customers', to='platform_ops.platformemployee', verbose_name='جالب العميل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='سجّلها')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_acquisition', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'اكتساب عميل',
                'verbose_name_plural': 'اكتسابات العملاء',
            },
        ),
        migrations.CreateModel(
            name='PlatformOperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('engagement', 'الإسناد'), ('health_check', 'فحص الصحة'), ('acquisition', 'اكتساب العميل')], max_length=20, verbose_name='النطاق')),
                ('action', models.CharField(choices=[('assigned', 'إسناد'), ('transferred', 'نقل'), ('suspended', 'تعليق'), ('resumed', 'استئناف'), ('revoked', 'إلغاء'), ('health_check_approved', 'اعتماد فحص صحة'), ('health_check_item_converted', 'تحويل بند إلى أمر عمل'), ('acquisition_set', 'تسجيل اكتساب')], max_length=40, verbose_name='الإجراء')),
                ('subject_id', models.PositiveIntegerField(verbose_name='معرّف الصفّ المتأثر')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='السبب')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل بلا بيانات شخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_operation_events', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_operation_events', to='tenants.tenant', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'حدث عملية منصّة',
                'verbose_name_plural': 'أحداث عمليات المنصة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companyhealthcheck',
            index=models.Index(fields=['tenant', 'kind', '-period'], name='platform_op_tenant__8acc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyhealthcheck',
            index=models.Index(fields=['tenant', 'status'], name='platform_op_tenant__e7c10c_idx'),
        ),
        migrations.AddIndex(
            model_name='companyhealthcheckitem',
            index=models.Index(fields=['health_check', 'status'], name='platform_op_health__76f94b_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyhealthcheckitem',
            constraint=models.UniqueConstraint(fields=('health_check', 'code'), name='platform_ops_health_item_check_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='platformoperationevent',
            index=models.Index(fields=['tenant', 'domain', '-created_at'], name='platform_op_tenant__24477e_idx'),
        ),
        migrations.AddIndex(
            model_name='platformoperationevent',
            index=models.Index(fields=['domain', 'subject_id', '-created_at'], name='platform_op_domain_8f742d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformoperationevent',
            index=models.Index(fields=['correlation_id'], name='platform_op_correla_4ecd2d_idx'),
        ),
    ]
