# Generated by Django 5.1.15 on 2026-09-11 23:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0014_engagement_capacity_override_reason_and_more'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderdeliverable',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('employee_error', 'خطأ الموظف'), ('customer_new_info', 'معلومات جديدة من العميل'), ('other', 'أخرى')], default='', help_text='إلزامي مع سبب الرفض المكتوب (٢١٠-ج، القصة ١٤): employee_error يمنع خصم حصة العميل ثانيةً ومنح إنجاز الموظف ثانيةً عند إعادة العمل، وcustomer_new_info يجيز احتساب وحدات جديدة إن اعتمدها السوبر أدمن كطلب جديد.', max_length=20, verbose_name='تصنيف سبب الرفض'),
        ),
        migrations.CreateModel(
            name='ServiceUnitCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='رقم النسخة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('retired', 'منتهية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('activation_reason', models.CharField(blank=True, default='', help_text='إلزامي لحظة تفعيل المسودة؛ يبقى في الصف بعد التفعيل.', max_length=500, verbose_name='سبب التفعيل')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة من')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة إلى')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='فعّلها')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'كتالوج وحدات الخدمة',
                'verbose_name_plural': 'كتالوجات وحدات الخدمة',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sales_invoice', 'فاتورة بيع'), ('purchase_invoice', 'فاتورة شراء'), ('receipt_or_payment', 'سند قبض/صرف أو دفعة'), ('journal_entry', 'قيد يومية'), ('sales_or_purchase_order', 'أمر بيع/شراء'), ('inventory_document', 'مستند مخزون/جرد'), ('bank_reconciliation', 'تسوية بنكية'), ('import_file_row', 'ملف إدخال'), ('report_or_check_or_support', 'تقرير أو فحص أو دعم')], max_length=30, verbose_name='نوع المستند')),
                ('document_id', models.PositiveIntegerField(verbose_name='معرّف المستند')),
                ('line_count', models.PositiveIntegerField(default=1, verbose_name='عدد البنود الموثقة')),
                ('complexity', models.CharField(blank=True, choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع')], default='', max_length=10, verbose_name='التعقيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deliverable', models.ForeignKey(blank=True, help_text='يُملأ عند تسليم أمر العمل بهذا الرابط.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_links', to='platform_ops.workorderdeliverable', verbose_name='المُسلَّم')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ربطه')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_work_order_document_links', to='tenants.tenant', verbose_name='الشركة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='platform_ops.workorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'ربط مستند بأمر عمل',
                'verbose_name_plural': 'روابط المستندات بأوامر العمل',
            },
        ),
        migrations.CreateModel(
            name='ServiceUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('usage', 'استخدام'), ('reversal', 'عكس')], default='usage', max_length=10, verbose_name='نوع الحدث')),
                ('source_type', models.CharField(choices=[('sales_invoice', 'فاتورة بيع'), ('purchase_invoice', 'فاتورة شراء'), ('receipt_or_payment', 'سند قبض/صرف أو دفعة'), ('journal_entry', 'قيد يومية'), ('sales_or_purchase_order', 'أمر بيع/شراء'), ('inventory_document', 'مستند مخزون/جرد'), ('bank_reconciliation', 'تسوية بنكية'), ('import_file_row', 'ملف إدخال'), ('report_or_check_or_support', 'تقرير أو فحص أو دعم')], max_length=30, verbose_name='نوع مصدر الوحدة')),
                ('source_id', models.PositiveIntegerField(verbose_name='معرّف المصدر')),
                ('line_count_snapshot', models.PositiveIntegerField(verbose_name='لقطة عدد البنود')),
                ('catalog_version', models.PositiveIntegerField(verbose_name='نسخة الكتالوج المستعملة')),
                ('units', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوحدات')),
                ('chargeable_to_customer', models.BooleanField(verbose_name='يستهلك حصة العميل')),
                ('creditable_to_employee', models.BooleanField(verbose_name='يدخل إنجاز الموظف')),
                ('approved_at', models.DateTimeField(verbose_name='وقت الاعتماد')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='بداية الدورة المنسوبة')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='نهاية الدورة المنسوبة')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='مفتاح idempotency')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='السبب')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل بلا بيانات شخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المعتمِد')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='platform_ops.workorderdeliverable', verbose_name='المُسلَّم')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='platform_ops.platformemployee', verbose_name='الموظف المنفّذ')),
                ('reversed_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='platform_ops.serviceusageevent', verbose_name='الحدث المعكوس')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='platform_ops.servicesubscription', verbose_name='اشتراك الخدمة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_service_usage_events', to='tenants.tenant', verbose_name='الشركة')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='platform_ops.workorder', verbose_name='أمر العمل')),
                ('document_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='platform_ops.workorderdocumentlink', verbose_name='ربط المستند')),
            ],
            options={
                'verbose_name': 'حدث استخدام خدمة',
                'verbose_name_plural': 'أحداث استخدام الخدمة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUnitCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sales_invoice', 'فاتورة بيع'), ('purchase_invoice', 'فاتورة شراء'), ('receipt_or_payment', 'سند قبض/صرف أو دفعة'), ('journal_entry', 'قيد يومية'), ('sales_or_purchase_order', 'أمر بيع/شراء'), ('inventory_document', 'مستند مخزون/جرد'), ('bank_reconciliation', 'تسوية بنكية'), ('import_file_row', 'ملف إدخال'), ('report_or_check_or_support', 'تقرير أو فحص أو دعم')], max_length=30, verbose_name='نوع المستند/العملية')),
                ('base_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='أساس الوحدة')),
                ('per_line_weight', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='وزن السطر/الكمية')),
                ('complexity_low_add', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إضافة تعقيد منخفض')),
                ('complexity_medium_add', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إضافة تعقيد متوسط')),
                ('complexity_high_add', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إضافة تعقيد مرتفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='platform_ops.serviceunitcatalog', verbose_name='الكتالوج')),
            ],
            options={
                'verbose_name': 'بند كتالوج وحدات الخدمة',
                'verbose_name_plural': 'بنود كتالوج وحدات الخدمة',
                'constraints': [models.UniqueConstraint(fields=('catalog', 'document_type'), name='platform_ops_catalog_entry_type_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ServiceUnitCatalogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء مسودة'), ('updated', 'تعديل مسودة'), ('cloned', 'استنساخ مسودة'), ('activated', 'تفعيل نسخة'), ('retired', 'إنهاء نسخة')], max_length=20, verbose_name='الإجراء')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل بلا بيانات شخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform_ops.serviceunitcatalog', verbose_name='الكتالوج')),
            ],
            options={
                'verbose_name': 'حدث كتالوج وحدات الخدمة',
                'verbose_name_plural': 'أحداث كتالوج وحدات الخدمة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['catalog', '-created_at'], name='platform_op_catalog_b67046_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workorderdocumentlink',
            index=models.Index(fields=['work_order'], name='platform_op_work_or_8e3332_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderdocumentlink',
            index=models.Index(fields=['document_type', 'document_id'], name='platform_op_documen_622e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderdocumentlink',
            index=models.Index(fields=['deliverable'], name='platform_op_deliver_7aef73_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceusageevent',
            index=models.Index(fields=['tenant', '-created_at'], name='platform_op_tenant__1a1e61_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceusageevent',
            index=models.Index(fields=['subscription', '-created_at'], name='platform_op_subscri_6b832a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceusageevent',
            index=models.Index(fields=['work_order'], name='platform_op_work_or_22796a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceusageevent',
            index=models.Index(fields=['source_type', 'source_id'], name='platform_op_source__3086dd_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceusageevent',
            index=models.Index(fields=['employee', '-created_at'], name='platform_op_employe_e4224d_idx'),
        ),
    ]
