# Generated by Django 5.1.15 on 2026-09-11 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0015_workorderdeliverable_rejection_category_and_more'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'مرتفعة'), ('urgent', 'عاجلة')], default='normal', help_text='لترتيب طابور الموظف — القصة ٣٤ من #210 (أولوية ثم أجل).', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assignee', 'priority', 'deadline_at'], name='platform_op_assigne_0e295d_idx'),
        ),
    ]
