# Generated by Django 5.1.15 on 2026-09-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0016_workorder_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformactivitylog',
            name='action',
            field=models.CharField(choices=[('work_order_transition', 'تغيير حالة أمر العمل'), ('deliverable_submit', 'تقديم مُسلَّم'), ('deliverable_review', 'مراجعة مُسلَّم'), ('comment_added', 'إضافة تعليق'), ('work_order_assigned', 'إسناد أمر عمل'), ('work_order_priority_changed', 'تغيير أولوية أمر عمل'), ('document_linked', 'ربط مستند بأمر عمل'), ('engagement_assigned', 'إسناد ارتباط'), ('engagement_suspended', 'تعليق ارتباط'), ('engagement_revoked', 'إلغاء ارتباط'), ('snapshot_captured', 'التقاط لقطة أداء'), ('other', 'أخرى')], max_length=50, verbose_name='نوع النشاط'),
        ),
    ]
