# Generated by Django 5.1.15 on 2026-09-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0017_alter_platformactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceusageevent',
            name='line_count_source',
            field=models.CharField(choices=[('observed', 'مرصود من المستند'), ('declared', 'مُصرَّح به')], default='declared', help_text='هل رُصد العددُ من المستند أم صُرِّح به؟ — يُراجَع عليه أيُّ اعتراضٍ على الوحدات.', max_length=10, verbose_name='مصدر عدد البنود'),
        ),
        migrations.AddField(
            model_name='workorderdocumentlink',
            name='line_count_source',
            field=models.CharField(choices=[('observed', 'مرصود من المستند'), ('declared', 'مُصرَّح به')], default='declared', max_length=10, verbose_name='مصدر عدد البنود'),
        ),
        migrations.AddField(
            model_name='workorderdocumentlink',
            name='recount_reason',
            field=models.CharField(blank=True, default='', help_text='إلزامي حين يكون المستند نفسُه قد احتُسب سلفاً لأمر العمل — طلبٌ جديد يعتمده مدير العمليات.', max_length=500, verbose_name='سبب إعادة الاحتساب'),
        ),
    ]
