# Generated by Django 5.1.15 on 2026-09-12 02:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0018_serviceusageevent_line_count_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='رقم النسخة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('retired', 'منتهية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الراتب الأساسي الشهري')),
                ('daily_hours', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ساعات الدوام اليومية')),
                ('weekly_days', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='أيام الدوام الأسبوعية')),
                ('acquisition_commission_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='عمولة اكتساب العميل الشهرية')),
                ('acquisition_commission_months', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة عمولة الاكتساب (أشهر)')),
                ('accrual_day_of_month', models.PositiveSmallIntegerField(default=1, help_text='اليوم من الشهر الذي يُفتَح فيه إغلاق مستحقات الشهر السابق — إعلاميٌّ للواجهة.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='يوم استحقاق الإغلاق الشهري')),
                ('activation_reason', models.CharField(blank=True, default='', help_text='إلزامي لحظة تفعيل المسودة؛ يبقى في الصف بعد التفعيل.', max_length=500, verbose_name='سبب التفعيل')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة من')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة إلى')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='فعّلها')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('employee', models.ForeignKey(blank=True, help_text='فارغ = افتراضيّات عامّة لكل الموظفين؛ موظفٌ محدَّد = نسخة خاصّة به تغلب العامّة.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_policies', to='platform_ops.platformemployee', verbose_name='موظف مستهدَف')),
            ],
            options={
                'verbose_name': 'سياسة تعويض موظف (pilot)',
                'verbose_name_plural': 'سياسات تعويض الموظفين (pilot)',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='رقم النسخة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('retired', 'منتهية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('specialty', models.CharField(blank=True, default='', help_text='فارغ = نسخة عامة لكل التخصصات؛ اسم تخصص = نسخة خاصة به تغلب العامة.', max_length=100, verbose_name='نطاق التخصص')),
                ('weights', models.JSONField(blank=True, default=dict, help_text='task_completion, quality_accuracy, sla_adherence, customer_satisfaction. مجموعُ المكتوب هنا مئةٌ بالضبط، يُرفض غيرُه لحظةَ حفظ المسودة أو تفعيلها. وإسقاطُ المحور غير المنطبق وإعادةُ توزيع وزنه بالتناسب يقعان لحظةَ الحساب لا لحظةَ الكتابة، فلا يُغيّران ما يُخزَّن في هذا الحقل.', verbose_name='أوزان المحاور الأربعة')),
                ('targets', models.JSONField(blank=True, default=dict, help_text='حقلٌ typed محجوزٌ لمستهدفاتٍ مستقبليةٍ فوق النسب المئوية — فارغٌ في الـpilot.', verbose_name='مستهدفات إضافية')),
                ('min_sample_size', models.PositiveIntegerField(default=5, help_text='عدد المُسلَّمات المراجَعة في الفترة؛ دونه تكون الحالة insufficient_data صراحة لا صفراً.', verbose_name='الحد الأدنى لحجم العينة')),
                ('review_grace_period_hours', models.PositiveIntegerField(default=48, help_text='مهلة إعلامية تُعرض في معاينة إغلاق الشهر؛ التسليمات المعلَّقة تبقى تمنع الإغلاق دوماً.', verbose_name='مهلة المراجعة قبل الإغلاق (ساعات)')),
                ('activation_reason', models.CharField(blank=True, default='', help_text='إلزامي لحظة تفعيل المسودة؛ يبقى في الصف بعد التفعيل.', max_length=500, verbose_name='سبب التفعيل')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة من')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='سريان النسخة إلى')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='فعّلها')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'سياسة تقييم أداء (pilot)',
                'verbose_name_plural': 'سياسات تقييم الأداء (pilot)',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCompensationClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سنة الإغلاق')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='شهر الإغلاق')),
                ('employees_processed', models.PositiveIntegerField(default=0, verbose_name='عدد الموظفين المعالَجين')),
                ('snapshots_captured', models.PositiveIntegerField(default=0, verbose_name='عدد لقطات الأداء الملتقَطة')),
                ('salary_lines_created', models.PositiveIntegerField(default=0, verbose_name='عدد سطور الرواتب المنشأة')),
                ('commission_lines_created', models.PositiveIntegerField(default=0, verbose_name='عدد سطور العمولات المنشأة')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإغلاق')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أغلقه')),
                ('performance_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_closes', to='platform_ops.performanceevaluationpolicy', verbose_name='سياسة التقييم المستعملة')),
            ],
            options={
                'verbose_name': 'إغلاق مستحقّات شهر',
                'verbose_name_plural': 'إغلاقات مستحقّات الأشهر',
            },
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='evaluation_policy',
            field=models.ForeignKey(blank=True, help_text='تُملأ فقط للقطات المُلتقَطة عبر محاور الـpilot الأربعة؛ وأوزانُها تُقرأ من النسخة المشار إليها هنا لا من نسبةٍ ثابتة. فارغة للقطات #207 القديمة بمحاورها الخمسة (policy_profile وحده).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='platform_ops.performanceevaluationpolicy', verbose_name='سياسة تقييم الـpilot المعتمدة (210-D)'),
        ),
        migrations.CreateModel(
            name='PerformanceEvaluationPolicyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء مسودة'), ('updated', 'تعديل مسودة'), ('cloned', 'استنساخ مسودة'), ('activated', 'تفعيل سياسة'), ('retired', 'إنهاء سياسة')], max_length=20, verbose_name='الإجراء')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل بلا بيانات شخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform_ops.performanceevaluationpolicy', verbose_name='سياسة التقييم')),
            ],
            options={
                'verbose_name': 'حدث سياسة تقييم أداء',
                'verbose_name_plural': 'أحداث سياسات تقييم الأداء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensationPolicyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'إنشاء مسودة'), ('updated', 'تعديل مسودة'), ('cloned', 'استنساخ مسودة'), ('activated', 'تفعيل سياسة'), ('retired', 'إنهاء سياسة')], max_length=20, verbose_name='الإجراء')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف الارتباط')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='تفاصيل بلا بيانات شخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='platform_ops.employeecompensationpolicy', verbose_name='سياسة التعويض')),
            ],
            options={
                'verbose_name': 'حدث سياسة تعويض',
                'verbose_name_plural': 'أحداث سياسات التعويض',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy', '-created_at'], name='platform_op_policy__d6838b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سنة الاستحقاق')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='شهر الاستحقاق')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='0 = السطر الأصلي؛ 1+ = سطور تسوية لاحقة.', verbose_name='تسلسل السطر')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'معلّق'), ('eligible', 'مؤهَّل'), ('approved', 'معتمَد'), ('payable', 'قابل للصرف'), ('paid', 'مصروف'), ('reversed', 'معكوس')], default='pending', max_length=20, verbose_name='الحالة')),
                ('pending_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='سبب التعليق')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='سبب التسوية/التعديل')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='مفتاح idempotency')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('adjustment_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='platform_ops.employeesalaryline', verbose_name='تسوية على')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('compensation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_lines', to='platform_ops.employeecompensationpolicy', verbose_name='سياسة التعويض المستعملة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_lines', to='platform_ops.platformemployee', verbose_name='الموظف')),
                ('monthly_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_lines', to='platform_ops.monthlycompensationclose', verbose_name='إغلاق الشهر')),
            ],
            options={
                'verbose_name': 'سطر راتب موظف',
                'verbose_name_plural': 'سطور رواتب الموظفين',
                'indexes': [models.Index(fields=['employee', 'period_year', 'period_month'], name='platform_op_employe_97edc3_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_year', 'period_month', 'sequence'), name='platform_ops_salaryline_employee_period_seq_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionCommissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سنة الاستحقاق')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='شهر الاستحقاق')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='0 = السطر الأصلي؛ 1+ = سطور تسوية لاحقة.', verbose_name='تسلسل السطر')),
                ('commission_month_index', models.PositiveSmallIntegerField(help_text='1..acquisition_commission_months — بعدها لا يُنشأ سطر جديد.', verbose_name='ترتيب شهر العمولة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'معلّق'), ('eligible', 'مؤهَّل'), ('approved', 'معتمَد'), ('payable', 'قابل للصرف'), ('paid', 'مصروف'), ('reversed', 'معكوس')], default='pending', max_length=20, verbose_name='الحالة')),
                ('pending_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='سبب التعليق')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='سبب التسوية/التعديل')),
                ('idempotency_key', models.CharField(max_length=128, unique=True, verbose_name='مفتاح idempotency')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_lines', to='platform_ops.customeracquisition', verbose_name='اكتساب العميل')),
                ('adjustment_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='platform_ops.acquisitioncommissionline', verbose_name='تسوية على')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('employee', models.ForeignKey(help_text='لقطة acquisition.acquired_by وقت إنشاء السطر — مستقلّ عن موظف الخدمة الحالي.', on_delete=django.db.models.deletion.PROTECT, related_name='commission_lines', to='platform_ops.platformemployee', verbose_name='جالب العميل')),
                ('compensation_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_lines', to='platform_ops.employeecompensationpolicy', verbose_name='سياسة التعويض المستعملة')),
                ('monthly_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_lines', to='platform_ops.monthlycompensationclose', verbose_name='إغلاق الشهر')),
            ],
            options={
                'verbose_name': 'سطر عمولة اكتساب',
                'verbose_name_plural': 'سطور عمولات الاكتساب',
                'indexes': [models.Index(fields=['acquisition', 'period_year', 'period_month'], name='platform_op_acquisi_4bf1ca_idx'), models.Index(fields=['employee', 'period_year', 'period_month'], name='platform_op_employe_483455_idx')],
                'constraints': [models.UniqueConstraint(fields=('acquisition', 'period_year', 'period_month', 'sequence'), name='platform_ops_commissionline_acq_period_seq_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlycompensationclose',
            constraint=models.UniqueConstraint(fields=('period_year', 'period_month'), name='platform_ops_monthlyclose_period_uniq'),
        ),
        migrations.AddIndex(
            model_name='performanceevaluationpolicyevent',
            index=models.Index(fields=['policy', '-created_at'], name='platform_op_policy__c825c2_idx'),
        ),
    ]
