# Generated by Django 5.1.15 on 2026-09-12 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0019_employeecompensationpolicy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سنة الفترة')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='شهر الفترة')),
                ('axis', models.CharField(blank=True, default='', max_length=50, verbose_name='المحور')),
                ('reason', models.TextField(verbose_name='سبب الاعتراض')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('accepted', 'قُبل وصُحِّح'), ('rejected', 'مرفوض')], default='open', max_length=10, verbose_name='حالة الطلب')),
                ('resolution_note', models.CharField(blank=True, default='', max_length=500, verbose_name='ردّ المدير')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الردّ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_review_requests', to='platform_ops.platformemployee', verbose_name='الموظف')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='من ردّ')),
            ],
            options={
                'verbose_name': 'طلب مراجعة نتيجة',
                'verbose_name_plural': 'طلبات مراجعة النتائج',
                'indexes': [models.Index(fields=['employee', 'period_year', 'period_month'], name='platform_op_employe_510544_idx'), models.Index(fields=['status', 'created_at'], name='platform_op_status_4b6a18_idx')],
            },
        ),
    ]
