# Generated by Django 5.1.15 on 2026-09-12 10:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    """فصلُ مقام الإنجاز عن طاقة الإسناد (#210 ت-ز).

    **ولا تعبئةَ رجعيّةً عمداً**: أيُّ قيمةٍ لـ`capacity_target` موجودةٍ اليوم ضُبطت
    لمعنى الإسناد (وحداتُ حِمل الشركات، وعددُ الأوامر النشطة) لا لمعنى الوحدات
    الشهريّة — فنسخُها إلى الحقل الجديد يستورد الخللَ نفسَه الذي فُصل الحقلُ لأجله.
    والصفرُ يعني «لم يُضبط» فيكون المقامُ وحداتِ المُسنَد كلَّها، وهو سلوكُ ما قبل
    الهجرة بعينه لكلّ صفٍّ لم تُضبط طاقتُه.
    """


    dependencies = [
        ('platform_ops', '0020_performance_review_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformemployee',
            name='monthly_units_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='سقفُ مقامِ محور «إنجاز العمل» بوحدات الكتالوج شهرياً. صفرٌ يعني «لم يُضبط» فيكون المقامُ وحداتِ المُسنَد كلَّها. **لا يُخلط بـ`capacity_target`**: ذاك يُقاس بالشركات الموزونة وبعدد الأوامر، وهذا بوحدات المستندات — سُلَّمان لا يجتمعان في رقمٍ واحد، ورقمٌ صالحٌ لأحدهما يُعطِّل الآخر بصمت.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مقام الإنجاز الشهري (وحدات)'),
        ),
        migrations.AlterField(
            model_name='platformemployee',
            name='capacity_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='طاقةُ الإسناد: تُقارَن بمجموع وحدات حِمل الشركات المرتبطة (١/٢/٣ للشركة) وبعدد أوامر العمل النشطة في شريط التدخّل. صفرٌ يعني «لم تُضبط» لا «طاقةَ صفر».', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مستهدف السعة الموزون'),
        ),
    ]
