# Generated by Django 5.1.15 on 2026-09-12 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0021_employee_monthly_units_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاجتماع')),
                ('agenda', models.TextField(blank=True, default='', verbose_name='جدول الأعمال')),
                ('start', models.DateTimeField(verbose_name='بداية الاجتماع')),
                ('end', models.DateTimeField(verbose_name='نهاية الاجتماع')),
                ('meeting_link', models.URLField(max_length=500, verbose_name='رابط الاجتماع')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('cancelled', 'ملغى'), ('finished', 'منتهٍ')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'اجتماع منصة',
                'verbose_name_plural': 'اجتماعات المنصة',
            },
        ),
        migrations.CreateModel(
            name='PlatformMeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attended', 'حضر'), ('absent', 'غائب'), ('excused_pending', 'عذر بانتظار البتّ'), ('excused_accepted', 'عذر مقبول'), ('excused_rejected', 'عذر مرفوض')], default='absent', max_length=20, verbose_name='الحالة')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت تسجيل الحضور')),
                ('excuse_note', models.TextField(blank=True, default='', verbose_name='سبب عدم الحضور')),
                ('excuse_decided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البتّ في العذر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to='platform_ops.platformemployee', verbose_name='الموظف')),
                ('excuse_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='من بتّ في العذر')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='platform_ops.platformmeeting', verbose_name='الاجتماع')),
            ],
            options={
                'verbose_name': 'حضور اجتماع منصة',
                'verbose_name_plural': 'حضور اجتماعات المنصة',
            },
        ),
        migrations.AddIndex(
            model_name='platformmeeting',
            index=models.Index(fields=['status', 'start'], name='platform_op_status_7bb023_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformmeeting',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='platform_ops_meeting_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='platformmeetingattendance',
            index=models.Index(fields=['employee', 'status'], name='platform_op_employe_a0575e_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmeetingattendance',
            index=models.Index(fields=['meeting', 'status'], name='platform_op_meeting_034d79_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformmeetingattendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'employee'), name='platform_ops_meetingattendance_meeting_employee_uniq'),
        ),
    ]
