# Generated by Django 5.1.15 on 2026-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0022_platformmeeting_platformmeetingattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformemployee',
            name='job_title',
            field=models.CharField(blank=True, default='', help_text='عنوانُ العرض على البطاقة — **حقلٌ منفصلٌ عن `specialty` عمداً**. `specialty` مفتاحُ سياسة يُطابَق بـ`PolicyProfile.specialty` في احتساب الأداء، فإعادةُ استعمالِه ليقرأ أجملَ على اللوحة تُبدّل سياسةَ تقييم الموظّف بصمت ودرجتُه مالٌ في محفظته. هذا الحقلُ عرضٌ صِرفٌ لا يحمل أيَّ أثرٍ حسابيّ.', max_length=100, verbose_name='المسمّى الوظيفي'),
        ),
        migrations.AddField(
            model_name='platformemployee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف'),
        ),
        migrations.AddField(
            model_name='platformemployee',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='رابطُ Cloudinary لصورة الموظّف — لا ملفَّ محلّياً؛ المستودعُ كلُّه يخزّن روابطَ Cloudinary.', max_length=500, verbose_name='رابط الصورة'),
        ),
    ]
