# Generated by Django 5.1.15 on 2026-09-13 10:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0023_platformemployee_job_title_platformemployee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluationpolicy',
            name='presence_day_cap_percent',
            field=models.PositiveIntegerField(default=125, help_text='سقفُ ما يعوّضه يومٌ طويلٌ عن يومٍ قصير. بلا سقفٍ يمحو يومٌ من اثنتي عشرةَ ساعةً ثلاثةَ أيّامٍ غائبة، فيصير «الانضباط» مقياسَ نَهَمٍ لا انتظام.', verbose_name='سقف نسبة اليوم الواحد (٪)'),
        ),
        migrations.AddField(
            model_name='performanceevaluationpolicy',
            name='presence_min_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='قرارُ المالك (#212): ثلاثُ ساعاتٍ حدّاً أدنى. اليومُ الذي يبلغها يأخذ مئةً بالمئة، وما زاد يرفع وما قلّ يخصم. صفرٌ يُلغي أثرَ الحضور على الدرجة إلغاءً تامّاً — فهو مفتاحُ الإطفاء لا «حدٌّ أدنى صفر».', max_digits=4, verbose_name='ساعات الحضور المطلوبة يومياً'),
        ),
        migrations.CreateModel(
            name='PlatformPresenceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='اليوم')),
                ('active_seconds', models.PositiveIntegerField(default=0, help_text='مجموعُ الفجوات بين نبضاتٍ متقاربة — لا الفرقُ بين أوّل نبضةٍ وآخرها.', verbose_name='ثواني الحضور الفعلي')),
                ('first_seen_at', models.DateTimeField(verbose_name='أول نبضة')),
                ('last_seen_at', models.DateTimeField(verbose_name='آخر نبضة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_days', to='platform_ops.platformemployee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'يوم حضور على المنصة',
                'verbose_name_plural': 'أيام الحضور على المنصة',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='idx_presence_day_date')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='uniq_platform_presence_employee_day')],
            },
        ),
    ]
