# Generated by Django 5.1.15 on 2026-09-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0024_performanceevaluationpolicy_presence_day_cap_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformnotification',
            name='notification_type',
            field=models.CharField(choices=[('sla_breach', 'تجاوز أجل'), ('low_score', 'تقييم منخفض'), ('quota_exceeded', 'تجاوز باقة'), ('task_assigned', 'إسنادُ مهمّة'), ('task_submission_reviewed', 'مراجعةُ تسليم مهمّة')], max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.CreateModel(
            name='PlatformTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المهمّة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'مرتفعة'), ('URGENT', 'عاجلة')], default='MEDIUM', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('OPEN', 'مجمَع بلا إسناد'), ('NEW', 'جديدة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('WAITING_FOR_REVIEW', 'بانتظار المراجعة'), ('COMPLETED', 'مكتملة')], default='NEW', max_length=25, verbose_name='الحالة')),
                ('audience', models.CharField(choices=[('INDIVIDUAL', 'موظّفٌ واحد'), ('SPECIFIC', 'موظّفون محدَّدون'), ('ALL', 'كلُّ الموظّفين'), ('OPEN', 'مجمَع — يختار الموظّف')], max_length=15, verbose_name='نطاق الإسناد')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('claim_limit', models.PositiveIntegerField(blank=True, help_text='لمهمّة المجمَع فقط: كم موظّفاً يجوز أن يطالب بها. لا حدّ إن ترك فارغاً.', null=True, verbose_name='حدُّ المطالبين')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'مهمّة موظّف منصّة',
                'verbose_name_plural': 'مهامّ موظّفي المنصّة',
            },
        ),
        migrations.CreateModel(
            name='PlatformTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFFERED', 'مُسندةٌ لم تُقبَل بعد'), ('ACCEPTED', 'مقبولة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('SUBMITTED', 'تم التسليم'), ('COMPLETED', 'مكتملة'), ('RETURNED', 'أُعيدت (رُفض تسليمها)')], default='OFFERED', max_length=15, verbose_name='حالة الإسناد')),
                ('offered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تسليم')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_task_assignments', to='platform_ops.platformemployee', verbose_name='الموظّف')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='platform_ops.platformtask', verbose_name='المهمّة')),
            ],
            options={
                'verbose_name': 'إسناد مهمّة موظّف منصّة',
                'verbose_name_plural': 'إسنادات مهامّ موظّفي المنصّة',
            },
        ),
        migrations.CreateModel(
            name='PlatformTaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='', verbose_name='ملاحظاتُ الموظّف على التسليم')),
                ('decision', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED_FULL', 'قبول كامل'), ('APPROVED_PARTIAL', 'قبول جزئي — ما زال العمل مستمراً'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='قرار المراجعة')),
                ('reviewer_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات المراجِع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_task_submissions', to='platform_ops.platformemployee', verbose_name='الموظّف')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المراجِع')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='platform_ops.platformtask', verbose_name='المهمّة')),
            ],
            options={
                'verbose_name': 'تسليم مهمّة موظّف منصّة',
                'verbose_name_plural': 'تسليمات مهامّ موظّفي المنصّة',
            },
        ),
        migrations.CreateModel(
            name='PlatformWorkspaceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نصّ الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_notes', to='platform_ops.platformemployee', verbose_name='الموظّف الكاتب')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_notes', to='platform_ops.platformtask', verbose_name='المهمّة (اختياري)')),
            ],
            options={
                'verbose_name': 'ملاحظة مساحة عمل',
                'verbose_name_plural': 'ملاحظات مساحة العمل',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEmployeeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نصّ الملاحظة')),
                ('visibility', models.CharField(choices=[('EMPLOYEE', 'يراها الموظّف'), ('MANAGER_ONLY', 'للمدير فقط')], default='EMPLOYEE', max_length=15, verbose_name='الرؤية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_notes', to='platform_ops.platformemployee', verbose_name='الموظّف')),
            ],
            options={
                'verbose_name': 'ملاحظة على موظّف منصّة',
                'verbose_name_plural': 'ملاحظات موظّفي المنصّة',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['employee', '-created_at'], name='platform_op_employe_08f37a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='platformtask',
            index=models.Index(fields=['status', '-created_at'], name='platform_op_status_5e1b07_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtask',
            index=models.Index(fields=['audience', 'status'], name='platform_op_audienc_4130a0_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtaskassignment',
            index=models.Index(fields=['employee', 'status'], name='platform_op_employe_43a927_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtaskassignment',
            index=models.Index(fields=['task', 'status'], name='platform_op_task_id_2cc5da_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformtaskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'employee'), name='platform_ops_task_assignment_task_employee_uniq'),
        ),
        migrations.AddIndex(
            model_name='platformtasksubmission',
            index=models.Index(fields=['task', '-created_at'], name='platform_op_task_id_ff17c2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtasksubmission',
            index=models.Index(fields=['employee', 'decision'], name='platform_op_employe_1bb9d5_idx'),
        ),
        migrations.AddIndex(
            model_name='platformworkspacenote',
            index=models.Index(fields=['employee', '-created_at'], name='platform_op_employe_5dcfb7_idx'),
        ),
        migrations.AddIndex(
            model_name='platformworkspacenote',
            index=models.Index(fields=['task', '-created_at'], name='platform_op_task_id_e65b42_idx'),
        ),
    ]
