# Generated by Django 6.0.3 on 2026-09-13 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0025_alter_platformnotification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformemployeenote',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_notes', to='platform_ops.platformtask', verbose_name='المهمّة (اختياري)'),
        ),
        migrations.AddIndex(
            model_name='platformemployeenote',
            index=models.Index(fields=['task', '-created_at'], name='platform_op_task_id_b82732_idx'),
        ),
    ]
