# Generated by Django 6.0.3 on 2026-09-14 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0026_platform_employee_note_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاجتماع')),
                ('agenda', models.TextField(blank=True, default='', verbose_name='جدول الأعمال')),
                ('start', models.DateTimeField(db_index=True, verbose_name='بداية الاجتماع')),
                ('end', models.DateTimeField(verbose_name='نهاية الاجتماع')),
                ('location', models.CharField(blank=True, default='', max_length=500, verbose_name='المكان أو الرابط')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظة عامة على الاجتماع')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('finished', 'منتهٍ'), ('cancelled', 'ملغى')], db_index=True, default='scheduled', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'اجتماع متقدّمين',
                'verbose_name_plural': 'اجتماعات المتقدّمين',
                'ordering': ['-start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantMeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم حاضرٍ من خارج الرابط')),
                ('status', models.CharField(choices=[('invited', 'مدعوّ'), ('attended', 'حضر'), ('absent', 'لم يحضر')], default='invited', max_length=20, verbose_name='الحضور')),
                ('note', models.TextField(blank=True, default='', verbose_name='ملاحظة على هذا الحاضر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to='platform_ops.jobapplicant', verbose_name='المتقدّم')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='platform_ops.applicantmeeting', verbose_name='الاجتماع')),
            ],
            options={
                'verbose_name': 'حاضر في اجتماع متقدّمين',
                'verbose_name_plural': 'حاضرو اجتماعات المتقدّمين',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='applicantmeeting',
            index=models.Index(fields=['status', '-start'], name='platform_op_status_8a64d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicantmeeting',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='platform_ops_applicant_meeting_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='applicantmeetingattendee',
            index=models.Index(fields=['meeting', 'status'], name='platform_op_meeting_8deb20_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicantmeetingattendee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applicant__isnull', False), ('guest_name', '')), models.Q(('applicant__isnull', True), models.Q(('guest_name', ''), _negated=True)), _connector='OR'), name='platform_ops_attendee_is_applicant_xor_guest'),
        ),
        migrations.AddConstraint(
            model_name='applicantmeetingattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('applicant__isnull', False)), fields=('meeting', 'applicant'), name='platform_ops_unique_applicant_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='applicantmeetingattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('applicant__isnull', True)), fields=('meeting', 'guest_name'), name='platform_ops_unique_guest_per_meeting'),
        ),
    ]
