# Generated by Django 6.0.3 on 2026-09-14 15:51

"""حاضرٌ واحدٌ لكلّ هويّةٍ في الاجتماع — قيدٌ تفرضه MySQL فعلاً.

‏**العمودُ المولَّدُ المخزَّنُ يعيد بناء الجدول في MySQL** (`ALGORITHM=COPY`)،
فالجدولُ مقفولٌ للكتابة طوال البناء. الجداولُ الثلاثةُ صغيرةٌ على الإنتاج
(قِيست يوم كتابة الهجرة: صفرُ حاضرين · ٣٩ جهازاً · ٢٤ مستودعاً) فلا أثرَ عمليّ.

والمكرّراتُ تُفحَص **قبل** البناء وتُرفع برسالةٍ تسمّي الصفوف، لا أن تسقط
الهجرةُ بـ`IntegrityError` عارٍ بعد نسخ الجدول كلِّه.
"""

from django.db import migrations, models
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db.models import Count


def refuse_existing_duplicates(apps, schema_editor):
    Attendee = apps.get_model("platform_ops", "ApplicantMeetingAttendee")
    offenders = []
    by_applicant = (
        Attendee.objects.filter(applicant__isnull=False)
        .values("meeting_id", "applicant_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .order_by("meeting_id", "applicant_id")
    )
    offenders += [
        f"اجتماع {row['meeting_id']} · متقدّم {row['applicant_id']} ({row['n']} صفوف)"
        for row in by_applicant
    ]
    by_guest = (
        Attendee.objects.filter(applicant__isnull=True)
        .values("meeting_id", "guest_name")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .order_by("meeting_id", "guest_name")
    )
    offenders += [
        f"اجتماع {row['meeting_id']} · ضيف «{row['guest_name']}» ({row['n']} صفوف)"
        for row in by_guest
    ]
    if offenders:
        raise RuntimeError(
            "‏لا يمكن فرضُ «حاضرٌ واحدٌ لكلّ هويّةٍ في الاجتماع»: " + " · ".join(offenders)
            + ". احذف الصفَّ الزائد (وانقل ملاحظتَه إن لزم) ثمّ أعِد تشغيل الهجرة."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0027_applicant_meetings'),
    ]

    operations = [
        migrations.RunPython(
            refuse_existing_duplicates, migrations.RunPython.noop, elidable=False
        ),
        migrations.RemoveConstraint(
            model_name='applicantmeetingattendee',
            name='platform_ops_unique_applicant_per_meeting',
        ),
        migrations.RemoveConstraint(
            model_name='applicantmeetingattendee',
            name='platform_ops_unique_guest_per_meeting',
        ),
        migrations.AddField(
            model_name='applicantmeetingattendee',
            name='identity_key',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(applicant__isnull=False, then=django.db.models.functions.text.Concat(models.Value('a:'), django.db.models.functions.comparison.Cast('applicant', models.CharField(max_length=20)))), default=django.db.models.functions.text.Concat(models.Value('g:'), 'guest_name'), output_field=models.CharField(max_length=210)), output_field=models.CharField(max_length=210), verbose_name='مفتاحُ هويّة الحاضر'),
        ),
        migrations.AddConstraint(
            model_name='applicantmeetingattendee',
            constraint=models.UniqueConstraint(fields=('meeting', 'identity_key'), name='platform_ops_unique_attendee_per_meeting'),
        ),
    ]
