# Generated by Django 6.0.3 on 2026-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0029_task_file_attachments_and_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicantinvitation',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='يظهر للمدعوّ ليسأل قبل قبول الدعوة', max_length=40, verbose_name='رقم التواصل'),
        ),
        migrations.AddField(
            model_name='jobapplicantinvitation',
            name='note',
            field=models.TextField(blank=True, default='', help_text='نصٌّ يظهر للمدعوّ في صفحة قبول الدعوة قبل تسجيل الدخول', verbose_name='شرح الدعوة'),
        ),
    ]
