# Generated by Django 6.0.3 on 2026-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0030_invitation_note_and_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompensationpolicy',
            name='pay_terms_note',
            field=models.TextField(blank=True, default='', help_text='نصٌّ يظهر للموظّف تحت أرقامه في صفحته الشخصيّة — اشرح ما لا يقوله الرقم وحدَه.', verbose_name='شرح شروط الصرف'),
        ),
    ]
