# Generated by Django 6.0.3 on 2026-09-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0031_compensation_pay_terms_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicantUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'تحديثُ مرحلة'), ('notice', 'رسالة')], db_index=True, default='notice', max_length=20, verbose_name='النوع')),
                ('author_kind', models.CharField(choices=[('system', 'النظام'), ('team', 'فريق التوظيف'), ('applicant', 'المتقدّم')], db_index=True, max_length=20, verbose_name='الكاتب')),
                ('body', models.TextField(blank=True, default='', verbose_name='النص')),
                ('link', models.URLField(blank=True, default='', max_length=500, verbose_name='رابط')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='رقم للتواصل')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='منشور للمتقدم')),
                ('from_status', models.CharField(blank=True, default='', max_length=30, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(blank=True, default='', max_length=30, verbose_name='الحالة الجديدة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='platform_ops.jobapplicant', verbose_name='المتقدم')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='كاتب الرسالة')),
            ],
            options={
                'verbose_name': 'تحديث على طلب متقدم',
                'verbose_name_plural': 'تحديثات طلبات المتقدمين',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['applicant', 'is_public', 'created_at'], name='platform_op_applica_ab6b82_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'notice'), _negated=True), models.Q(('body', ''), _negated=True), _connector='OR'), name='platform_ops_applicant_update_notice_needs_body')],
            },
        ),
    ]
