# Generated by Django 6.0.3 on 2026-04-14 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('address', models.CharField(blank=True, db_column='address', default='', max_length=500)),
                ('notes', models.TextField(blank=True, db_column='notes', default='')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'realestate_buildings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('meter_kind', models.CharField(choices=[('main', 'رئيسي'), ('sub', 'فرعي')], db_column='meter_kind', max_length=10)),
                ('label', models.CharField(blank=True, db_column='label', default='', max_length=120)),
                ('serial_number', models.CharField(blank=True, db_column='serial_number', default='', max_length=80)),
                ('building', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.CASCADE, related_name='electric_meters', to='realestate.building')),
            ],
            options={
                'db_table': 'realestate_electric_meters',
                'ordering': ['building', 'meter_kind', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reading_date', models.DateField(db_column='reading_date')),
                ('kwh_value', models.DecimalField(db_column='kwh_value', decimal_places=3, max_digits=14)),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=500)),
                ('meter', models.ForeignKey(db_column='meter_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='realestate.electricmeter')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'realestate_meter_readings',
                'ordering': ['-reading_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_type', models.CharField(choices=[('apartment', 'شقة'), ('warehouse', 'مخزن')], db_column='unit_type', default='apartment', max_length=20)),
                ('floor_number', models.SmallIntegerField(db_column='floor_number', default=0)),
                ('code', models.CharField(db_column='code', help_text='رمز الوحدة مثل: 3أ، مخزن-1', max_length=80)),
                ('area_sqm', models.DecimalField(blank=True, db_column='area_sqm', decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('building', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='realestate.building')),
            ],
            options={
                'db_table': 'realestate_rental_units',
                'ordering': ['building', 'floor_number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('renter_name', models.CharField(db_column='renter_name', max_length=200)),
                ('renter_phone', models.CharField(blank=True, db_column='renter_phone', default='', max_length=40)),
                ('monthly_rent', models.DecimalField(db_column='monthly_rent', decimal_places=2, max_digits=14)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True)),
                ('status', models.CharField(choices=[('active', 'ساري'), ('ended', 'منتهي')], db_column='status', default='active', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='notes', default='')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='realestate.rentalunit')),
            ],
            options={
                'db_table': 'realestate_leases',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='rental_unit',
            field=models.ForeignKey(blank=True, db_column='rental_unit_id', help_text='للعداد الفرعي فقط — يرتبط بشقة أو مخزن', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electric_meters', to='realestate.rentalunit'),
        ),
        migrations.AddConstraint(
            model_name='rentalunit',
            constraint=models.UniqueConstraint(fields=('building', 'code'), name='realestate_unit_unique_code_per_building'),
        ),
    ]
