"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-lnhmu5#_*fb#2gae88(=q+4(m3^i!0i^z4hmymf#%a_n7x*&zo",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'smart.ktragroup.com',
    'api.smart.ktragroup.com',
    'localhost',
    '127.0.0.1'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    # Local apps
    'partners',
    'tenants',
    'accounting',
    'inventory',
    'logistics',
    'hr',
    'bridge',
    'core',
    'realestate',
    'sales',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# كلمة المرور: إذا وُجد اسم المتغير MYSQL_PASSWORD في البيئة (مثل سطر MYSQL_PASSWORD= فارغ في .env)
# يُستخدم كما هو. إذا حذفت السطر من .env بالكامل، تُستخدم القيمة الافتراضية 123456 للتطوير.
_mysql_password = (
    os.environ["MYSQL_PASSWORD"]
    if "MYSQL_PASSWORD" in os.environ
    else "123456"
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "smartktra_smart-ktra",
        "USER": "smartktra_smartktra",
        "PASSWORD": "smart@102030", 
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET foreign_key_checks = 0; SET sql_mode='STRICT_TRANS_TABLES', innodb_strict_mode=1;",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# هذا السطر هو اللي ناقصك ومسبب المشكلة
STATIC_ROOT = BASE_DIR / 'staticfiles' 


# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS — في الإنتاج استخدم قائمة صريحة؛ لا تفتح السماح للجميع مع credentials
_DEFAULT_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://smart.ktragroup.com",
]
_origins_env = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").strip()
if _origins_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _origins_env.split(",") if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = list(_DEFAULT_ORIGINS)

# أصول إضافية (مثلاً فتح Vite من IP الشبكة: http://192.168.1.10:5173) دون إعادة كتابة القائمة كاملة
_origins_extra = os.environ.get("DJANGO_CORS_EXTRA_ORIGINS", "").strip()
if _origins_extra:
    _extra_list = [o.strip() for o in _origins_extra.split(",") if o.strip()]
    CORS_ALLOWED_ORIGINS = list(CORS_ALLOWED_ORIGINS) + [
        o for o in _extra_list if o not in CORS_ALLOWED_ORIGINS
    ]

CORS_ALLOW_CREDENTIALS = True
# للتطوير فقط: DJANGO_CORS_ALLOW_ALL=1 يسمح بكل الأصول (تجنّب في الإنتاج مع credentials)
CORS_ALLOW_ALL_ORIGINS = os.environ.get("DJANGO_CORS_ALLOW_ALL", "").lower() in (
    "1",
    "true",
    "yes",
)

# حل دائم للتطوير المحلي: السماح لأي بورت على localhost/127.0.0.1
# (حتى لا تنكسر CORS عند تغيّر بورت Vite/CRA من 3000 إلى 5173 أو العكس)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

# Allow custom tenant header used by frontend SQL pages.
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-tenant-id",
]

CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS) + ['https://api.smart.ktragroup.com']

# المساعد الذكي (OpenClaw على سيرفر منفصل — ليس نفس خادم Django).
# Django يتصل به عبر HTTP (صادر من هذا السيرفر)؛ على سيرفر OpenClaw يجب أن يكون المنفذ (مثل 18789)
# مفتوحاً للوارد (Inbound) من الإنترنت إن أردت الوصول من خارج الشبكة الداخلية.
# تشخيص: (1) OpenClaw مباشرة: من المتصفح افتح http://72.60...:18789/v1/status (هذا عنوان OpenClaw فقط).
# (2) من خادم **Django** (أي كان عنوانه: إنتاج أو محلي): GET …/api/assistant/openclaw-status/
#     هذا المسار ليس على OpenClaw — هو على تطبيقك؛ Django من داخله يطلب 72.60.../v1/status.
#     لا تخلط: 127.0.0.1:8000 مثال لعنوان Django أثناء التطوير، وليس سيرفر OpenClaw.
# إن نجح (1) وفشل المساعد: راجع OPENCLAW_BEARER_TOKEN وصيغة الطلب في الكود.
# الطلبات والتوكن يمرّان عبر Django فقط (لا يُعرَّض التوكن للمتصفح).
# ملاحظة: إن وُجد المفتاح في البيئة بقيمة فارغة (مثل OPENCLAW_BEARER_TOKEN=) فـ get تعيد ""
# وليس الافتراضي؛ لذلك نستخدم (or الافتراضي) حتى يعمل التوكن المضمّن بدون .env.
_DEFAULT_OPENCLAW_MESSAGES_URL = "http://72.60.181.210:18789/v1/messages"
_DEFAULT_OPENCLAW_FILES_URL = "http://72.60.181.210:18789/v1/files"
_DEFAULT_OPENCLAW_STATUS_URL = "http://72.60.181.210:18789/v1/status"
_DEFAULT_OPENCLAW_BEARER_TOKEN = "8c453853d17f13975d1d4d93849b114e76923b9b7776845c"
OPENCLAW_MESSAGES_URL = (
    os.environ.get("OPENCLAW_MESSAGES_URL") or _DEFAULT_OPENCLAW_MESSAGES_URL
).strip()
OPENCLAW_FILES_URL = (
    os.environ.get("OPENCLAW_FILES_URL") or _DEFAULT_OPENCLAW_FILES_URL
).strip()
OPENCLAW_STATUS_URL = (
    os.environ.get("OPENCLAW_STATUS_URL") or _DEFAULT_OPENCLAW_STATUS_URL
).strip()
# يُستخدم في Django فقط كـ: Authorization: Bearer <القيمة> على كل طلب لـ /v1/messages و /v1/files
OPENCLAW_BEARER_TOKEN = (
    os.environ.get("OPENCLAW_BEARER_TOKEN") or _DEFAULT_OPENCLAW_BEARER_TOKEN
).strip()
OPENCLAW_ASSISTANT_TIMEOUT = int(
    os.environ.get("OPENCLAW_ASSISTANT_TIMEOUT", "600") or "600"
)
# WebSocket لـ /v1/messages (اختياري): إن وُضع فارغاً يُشتق من OPENCLAW_MESSAGES_URL → ws://…/v1/messages?token=…
# بروتوكول OpenClaw يفرض مصافحة connect (challenge + device/signature) قبل الدردشة؛ للـ BFF الأنسب HTTP POST + Bearer.
OPENCLAW_WS_MESSAGES_URL = (os.environ.get("OPENCLAW_WS_MESSAGES_URL") or "").strip()
# 0 = HTTP فقط (افتراضي). 1 = جرّب WS ثم تراجع لـ HTTP — WS لا يكفي لإكمال الجلسة بدون connect كامل.
_oc_ws = (os.environ.get("OPENCLAW_USE_WEBSOCKET", "0") or "0").strip().lower()
OPENCLAW_USE_WEBSOCKET = _oc_ws in ("1", "true", "yes", "on")

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": None,
    "PAGE_SIZE": None,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# Cloudinary — يُفضّل تعريف المفاتيح عبر البيئة في الإنتاج
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME", "dd63wjj5x"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY", "156587365187698"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET", "mISroKaSW9B4ehHB_rA65Q8YVUg"),
}

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# محاسبة لوجستيات: عطّل الترحيل التلقائي لدفعات الصفقة فقط (قيد شراء من الصفقة معطّل دائماً في الكود).
# في .env: LOGISTICS_DISABLE_AUTO_ACCOUNTING=1
LOGISTICS_DISABLE_AUTO_ACCOUNTING = os.environ.get(
    "LOGISTICS_DISABLE_AUTO_ACCOUNTING", ""
).strip().lower() in ("1", "true", "yes", "on")

# بعد تأكيد المورد + حالة Paid/Confirmed: إنشاء قيد تلقائياً من إشارة logistics.signals (مدين مورد / دائن صندوق).
# ضع 1 في .env إذا أردت إيقاف القيد التلقائي والاكتفاء بقيد يدوي أو بـ POST .../post_payment/.
LOGISTICS_PAYMENT_SKIP_AUTO_JOURNAL = os.environ.get(
    "LOGISTICS_PAYMENT_SKIP_AUTO_JOURNAL", ""
).strip().lower() in ("1", "true", "yes", "on")

# حساب الأب تحت الأصول لإنشاء حسابات الصناديق (مثلاً 1110 نقدية بالصندوق)
CASH_BOX_PARENT_ACCOUNT_CODE = os.environ.get("CASH_BOX_PARENT_ACCOUNT_CODE", "1110").strip() or "1110"
# قيد إيداع الصندوق: دائن — حساب رأس ملك / مساهمات (Equity). إن لم يُوجد الكود يُستخدم أول Equity.
CASH_BOX_CAPITAL_ACCOUNT_CODE = os.environ.get("CASH_BOX_CAPITAL_ACCOUNT_CODE", "").strip()
# معرّف Firestore للصندوق الافتراضي عند ترحيل دفعة دون تمرير cash_box_external_id (مثل صندوق الدولار).
DEFAULT_CASH_BOX_EXTERNAL_ID = os.environ.get("DEFAULT_CASH_BOX_EXTERNAL_ID", "").strip()

# مفتاح API للـ AI Agent — يُرسل في هيدر X-Agent-Key لحماية نقطة الاستعلام
# غيّر القيمة في .env إلى مفتاح قوي وسري في الإنتاج
AGENT_DB_API_KEY = os.environ.get(
    "AGENT_DB_API_KEY",
    "ktra-agent-2025-secret-key",
).strip()

# ── Test database: SQLite in-memory (MySQL user lacks CREATE DATABASE) ──
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
