"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-lnhmu5#_*fb#2gae88(=q+4(m3^i!0i^z4hmymf#%a_n7x*&zo",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = ["*"] if DEBUG else ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    # Local apps
    'partners',
    'tenants',
    'accounting',
    'inventory',
    'logistics',
    'hr',
    'bridge',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# كلمة المرور: إذا وُجد اسم المتغير MYSQL_PASSWORD في البيئة (مثل سطر MYSQL_PASSWORD= فارغ في .env)
# يُستخدم كما هو. إذا حذفت السطر من .env بالكامل، تُستخدم القيمة الافتراضية 123456 للتطوير.
_mysql_password = (
    os.environ["MYSQL_PASSWORD"]
    if "MYSQL_PASSWORD" in os.environ
    else "123456"
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DATABASE", "global_erp_pro"),
        "USER": os.environ.get("MYSQL_USER", "root"),
        "PASSWORD": _mysql_password,
        "HOST": os.environ.get("MYSQL_HOST", "localhost"),
        "PORT": os.environ.get("MYSQL_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "use_unicode": True,
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES', innodb_strict_mode=1; SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS — في الإنتاج استخدم قائمة صريحة؛ لا تفتح السماح للجميع مع credentials
_DEFAULT_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
_origins_env = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").strip()
if _origins_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _origins_env.split(",") if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = list(_DEFAULT_ORIGINS)

# أصول إضافية (مثلاً فتح Vite من IP الشبكة: http://192.168.1.10:5173) دون إعادة كتابة القائمة كاملة
_origins_extra = os.environ.get("DJANGO_CORS_EXTRA_ORIGINS", "").strip()
if _origins_extra:
    _extra_list = [o.strip() for o in _origins_extra.split(",") if o.strip()]
    CORS_ALLOWED_ORIGINS = list(CORS_ALLOWED_ORIGINS) + [
        o for o in _extra_list if o not in CORS_ALLOWED_ORIGINS
    ]

CORS_ALLOW_CREDENTIALS = True
# للتطوير فقط: DJANGO_CORS_ALLOW_ALL=1 يسمح بكل الأصول (تجنّب في الإنتاج مع credentials)
CORS_ALLOW_ALL_ORIGINS = os.environ.get("DJANGO_CORS_ALLOW_ALL", "").lower() in (
    "1",
    "true",
    "yes",
)

# حل دائم للتطوير المحلي: السماح لأي بورت على localhost/127.0.0.1
# (حتى لا تنكسر CORS عند تغيّر بورت Vite/CRA من 3000 إلى 5173 أو العكس)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

# Allow custom tenant header used by frontend SQL pages.
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-tenant-id",
]

CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": None,
    "PAGE_SIZE": None,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# Cloudinary — يُفضّل تعريف المفاتيح عبر البيئة في الإنتاج
CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME", "dd63wjj5x"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY", "156587365187698"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET", "mISroKaSW9B4ehHB_rA65Q8YVUg"),
}

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
