# Generated by Django 6.0.3 on 2026-04-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(db_column='UOMID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=10, unique=True)),
                ('name_ar', models.CharField(db_column='Name_AR', max_length=50)),
                ('name_en', models.CharField(db_column='Name_EN', max_length=50)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'verbose_name_plural': 'Units of Measure',
                'db_table': 'units_of_measure',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='ParentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productcategory')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('sku', models.CharField(db_column='SKU', max_length=50)),
                ('barcode', models.CharField(blank=True, db_column='Barcode', max_length=50, null=True)),
                ('name_ar', models.CharField(blank=True, db_column='Name_AR', max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, db_column='Name_EN', max_length=200, null=True)),
                ('uom_legacy', models.CharField(blank=True, db_column='UOM', max_length=20, null=True)),
                ('weight_kg', models.DecimalField(blank=True, db_column='Weight_KG', decimal_places=4, max_digits=12, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, db_column='Volume_CBM', decimal_places=6, max_digits=12, null=True)),
                ('hs_code', models.CharField(blank=True, db_column='HS_Code', max_length=20, null=True)),
                ('min_stock_level', models.IntegerField(blank=True, db_column='MinStockLevel', null=True)),
                ('is_serialized', models.BooleanField(db_column='IsSerialized', default=False)),
                ('is_for_sale_online', models.BooleanField(db_column='IsForSaleOnline', default=False)),
                ('online_price', models.DecimalField(blank=True, db_column='OnlinePrice', decimal_places=2, max_digits=18, null=True)),
                ('online_description', models.TextField(blank=True, db_column='OnlineDescription', null=True)),
                ('quantity_on_hand', models.DecimalField(db_column='QuantityOnHand', decimal_places=4, default=0, max_digits=18)),
                ('avg_cost', models.DecimalField(db_column='AvgCost', decimal_places=4, default=0, help_text='Weighted average cost per unit (base currency)', max_digits=18)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('category', models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory')),
                ('uom', models.ForeignKey(blank=True, db_column='UOMID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.unitofmeasure')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(db_column='MovementID', primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'استلام بضاعة'), ('OUT', 'صرف / بيع'), ('ADJUST_IN', 'تسوية إضافة'), ('ADJUST_OUT', 'تسوية نقص'), ('RETURN_IN', 'مرتجع داخل'), ('RETURN_OUT', 'مرتجع خارج')], db_column='MovementType', max_length=20)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('unit_cost', models.DecimalField(db_column='UnitCost', decimal_places=4, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(db_column='TotalCost', decimal_places=2, default=0, max_digits=18)),
                ('reference_type', models.CharField(choices=[('SHIPMENT', 'شحنة'), ('DEAL', 'صفقة'), ('CLEARANCE', 'تخليص جمركي'), ('MANUAL', 'يدوي'), ('SALE', 'بيع')], db_column='ReferenceType', default='MANUAL', max_length=20)),
                ('reference_id', models.IntegerField(blank=True, db_column='ReferenceID', null=True)),
                ('movement_date', models.DateField(db_column='MovementDate')),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('quantity_before', models.DecimalField(db_column='QuantityBefore', decimal_places=4, default=0, max_digits=18)),
                ('quantity_after', models.DecimalField(db_column='QuantityAfter', decimal_places=4, default=0, max_digits=18)),
                ('avg_cost_before', models.DecimalField(db_column='AvgCostBefore', decimal_places=4, default=0, max_digits=18)),
                ('avg_cost_after', models.DecimalField(db_column='AvgCostAfter', decimal_places=4, default=0, max_digits=18)),
                ('partner', models.ForeignKey(blank=True, db_column='PartnerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-movement_date', '-id'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='idx_tenant_sku'),
        ),
    ]
