# Generated by Django 6.0.3 on 2026-04-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_base_currency_fields'),
        ('inventory', '0001_stock_movements_and_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_negative_stock',
            field=models.BooleanField(db_column='AllowNegativeStock', default=False, help_text='إن عُطّل، يُرفض الصرف إذا تجاوزت الكمية المتاحة (الافتراضي: مرفوض)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='cogs_account',
            field=models.ForeignKey(blank=True, db_column='CogsAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories_cogs', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='inventory_account',
            field=models.ForeignKey(blank=True, db_column='InventoryAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories_inventory', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='revenue_account',
            field=models.ForeignKey(blank=True, db_column='RevenueAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories_revenue', to='accounting.account'),
        ),
    ]
