# Generated by Django 6.0.3 on 2026-05-23 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_stock_issue_ref_type'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.AutoField(db_column='PriceTierID', primary_key=True, serialize=False)),
                ('tier_type', models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء')], db_column='TierType', max_length=10)),
                ('tier_number', models.PositiveSmallIntegerField(db_column='TierNumber')),
                ('price', models.DecimalField(db_column='Price', decimal_places=4, max_digits=18)),
                ('tax_inclusive', models.BooleanField(db_column='TaxInclusive', default=False)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='inventory.product')),
            ],
            options={
                'db_table': 'product_price_tiers',
                'managed': True,
                'unique_together': {('product', 'tier_type', 'tier_number')},
            },
        ),
    ]
