# Generated by Django 6.0.3 on 2026-05-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_n8_t7_account_default_cost_center'),
        ('inventory', '0005_n8_t9_product_price_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ending_inventory_account_override',
            field=models.ForeignKey(blank=True, db_column='EndingInventoryAccountOverrideID', help_text='حساب بضاعة آخر المدة البديل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_ending_inventory_override', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_account_override',
            field=models.ForeignKey(blank=True, db_column='PurchaseAccountOverrideID', help_text='حساب الشراء البديل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_purchase_override', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_return_account_override',
            field=models.ForeignKey(blank=True, db_column='PurchaseReturnAccountOverrideID', help_text='حساب مرجع الشراء البديل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_purchase_return_override', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_account_override',
            field=models.ForeignKey(blank=True, db_column='SaleAccountOverrideID', help_text='حساب البيع البديل — يتجاوز حساب البيع في ثوابت المجموعة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_sale_override', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_return_account_override',
            field=models.ForeignKey(blank=True, db_column='SaleReturnAccountOverrideID', help_text='حساب مرجع البيع البديل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_sale_return_override', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_account_override',
            field=models.ForeignKey(blank=True, db_column='SupplierAccountOverrideID', help_text='حساب المورد البديل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_supplier_override', to='accounting.account'),
        ),
    ]
