# Generated by Django 6.0.3 on 2026-06-13 06:29

import django.db.models.deletion
from django.db import migrations, models


def seed_default_warehouse(apps, schema_editor):
    """مستودع رئيسي افتراضي لكل شركة قائمة حتى يعمل الاستلام فوراً."""
    Tenant = apps.get_model('tenants', 'Tenant')
    Warehouse = apps.get_model('inventory', 'Warehouse')
    for tenant in Tenant.objects.all():
        if not Warehouse.objects.filter(tenant=tenant).exists():
            Warehouse.objects.create(
                tenant=tenant, name='المستودع الرئيسي', code='MAIN',
                is_default=True, is_active=True,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_created_at'),
        ('tenants', '0009_operational_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('SHIPMENT', 'شحنة'), ('DEAL', 'صفقة'), ('CLEARANCE', 'تخليص جمركي'), ('MANUAL', 'يدوي'), ('SALE', 'بيع'), ('STOCK_ISSUE', 'إذن صرف'), ('PURCHASE_INVOICE', 'فاتورة شراء')], db_column='ReferenceType', default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(db_column='WarehouseID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('code', models.CharField(blank=True, db_column='Code', default='', max_length=30)),
                ('location', models.CharField(blank=True, db_column='Location', default='', max_length=255)),
                ('is_default', models.BooleanField(db_column='IsDefault', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('branch', models.ForeignKey(blank=True, db_column='BranchID', help_text='الفرع الذي يتبع له المستودع (اختياري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='tenants.branch')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenants.tenant')),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['-is_default', 'name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='WarehouseID', help_text='المستودع الذي وصلت إليه/خرجت منه البضاعة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant', 'code'), name='idx_tenant_warehouse_code'),
        ),
        migrations.RunPython(seed_default_warehouse, noop),
    ]
