# Generated by Django 6.0.3 on 2026-06-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_voidedjournal'),
        ('inventory', '0009_alter_stockmovement_reference_type_warehouse_and_more'),
        ('tenants', '0009_operational_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('SHIPMENT', 'شحنة'), ('DEAL', 'صفقة'), ('CLEARANCE', 'تخليص جمركي'), ('MANUAL', 'يدوي'), ('SALE', 'بيع'), ('STOCK_ISSUE', 'إذن صرف'), ('PURCHASE_INVOICE', 'فاتورة شراء'), ('WAREHOUSE_TRANSFER', 'تحويل مستودعي'), ('STOCKTAKE', 'جرد')], db_column='ReferenceType', default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.AutoField(db_column='StocktakeID', primary_key=True, serialize=False)),
                ('stocktake_number', models.CharField(blank=True, db_column='StocktakeNumber', default='', max_length=30)),
                ('stocktake_date', models.DateField(db_column='StocktakeDate')),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=500)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes', to='accounting.journalheader')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, db_column='WarehouseID', help_text='المستودع المجرود (وسم على الحركات) — الرصيد على مستوى الشركة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stocktakes',
                'ordering': ['-stocktake_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.AutoField(db_column='StocktakeLineID', primary_key=True, serialize=False)),
                ('counted_quantity', models.DecimalField(db_column='CountedQuantity', decimal_places=4, max_digits=18)),
                ('system_quantity', models.DecimalField(db_column='SystemQuantity', decimal_places=4, default=0, max_digits=18)),
                ('variance', models.DecimalField(db_column='Variance', decimal_places=4, default=0, max_digits=18)),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('stocktake', models.ForeignKey(db_column='StocktakeID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
            ],
            options={
                'db_table': 'stocktake_lines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.AutoField(db_column='TransferID', primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(blank=True, db_column='TransferNumber', default='', max_length=30)),
                ('transfer_date', models.DateField(db_column='TransferDate')),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=500)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('dest_warehouse', models.ForeignKey(db_column='DestWarehouseID', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse')),
                ('source_warehouse', models.ForeignKey(db_column='SourceWarehouseID', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_transfers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'warehouse_transfers',
                'ordering': ['-transfer_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferLine',
            fields=[
                ('id', models.AutoField(db_column='TransferLineID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('transfer', models.ForeignKey(db_column='TransferID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.warehousetransfer')),
            ],
            options={
                'db_table': 'warehouse_transfer_lines',
                'managed': True,
            },
        ),
    ]
