# Generated by Django 6.0.3 on 2026-06-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockmovement_reference_type_stocktake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_column='Brand', default='', max_length=100),
        ),
    ]
