# Generated by Django 6.0.3 on 2026-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, db_column='VariantGroup', default='', max_length=120),
        ),
    ]
