# Generated by Django 6.0.3 on 2026-07-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_variant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('SHIPMENT', 'شحنة'), ('DEAL', 'صفقة'), ('CLEARANCE', 'تخليص جمركي'), ('MANUAL', 'يدوي'), ('SALE', 'بيع'), ('STOCK_ISSUE', 'إذن صرف'), ('PURCHASE_INVOICE', 'فاتورة شراء'), ('WAREHOUSE_TRANSFER', 'تحويل مستودعي'), ('STOCKTAKE', 'جرد'), ('GOODS_RECEIPT', 'سند استلام'), ('DELIVERY_NOTE', 'سند تسليم')], db_column='ReferenceType', default='MANUAL', max_length=20),
        ),
    ]
