# Generated by Django 6.0.3 on 2026-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockmovement_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, db_column='SalePrice', decimal_places=4, help_text='سعر البيع الافتراضي للوحدة (العملة الأساسية) — فارغ يعني الرجوع لآخر سعر بيع', max_digits=18, null=True),
        ),
    ]
