# Generated by Django 6.0.3 on 2026-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productserial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, db_column='SupplierWarrantyMonths', help_text='مدة كفالة المورد لنا بالأشهر — تُحسب من تاريخ فاتورة الشراء', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, db_column='WarrantyMonths', help_text='مدة كفالة الزبون بالأشهر (فارغ = بلا كفالة)', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('SHIPMENT', 'شحنة'), ('DEAL', 'صفقة'), ('CLEARANCE', 'تخليص جمركي'), ('MANUAL', 'يدوي'), ('SALE', 'بيع'), ('STOCK_ISSUE', 'إذن صرف'), ('PURCHASE_INVOICE', 'فاتورة شراء'), ('WAREHOUSE_TRANSFER', 'تحويل مستودعي'), ('STOCKTAKE', 'جرد'), ('GOODS_RECEIPT', 'سند استلام'), ('DELIVERY_NOTE', 'سند تسليم'), ('SERVICE_ISSUE', 'صرف قطع كفالة')], db_column='ReferenceType', default='MANUAL', max_length=20),
        ),
    ]
