# Generated by Django 5.1.15 on 2026-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_product_supplier_warranty_months_and_more"),
        ("partners", "0013_general_note_targets"),
        ("tenants", "0018_alter_rolepermission_role_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "product", "movement_date"],
                name="idx_sm_tenant_prod_date",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "-movement_date", "-id"], name="idx_sm_tenant_date_id"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "reference_type", "reference_id"],
                name="idx_sm_tenant_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "warehouse", "product"], name="idx_sm_tenant_wh_prod"
            ),
        ),
    ]
