# Generated by Django 6.0.3 on 2026-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_phase5_p0_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_preorder',
            field=models.BooleanField(db_column='AllowPreorder', default=False, help_text='إتاحة بيع الصنف كطلب مسبق / عند الطلب حتى لو كان الرصيد صفراً'),
        ),
    ]
