# Generated by Django 6.0.3 on 2026-08-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_product_allow_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_store_only',
            field=models.BooleanField(db_column='IsStoreOnly', default=False, help_text='صنف خاص بالمتجر الإلكتروني فقط — لا يظهر في شاشة الأصناف المخزنية أو محددات فواتير البيع'),
        ),
    ]
