# Generated by Django 5.1.15 on 2026-08-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_product_is_store_only'),
        ('logistics', '0074_purchaseorder_idx_po_tenant_status_and_more'),
        ('sales', '0037_salesinvoiceline_customer_note_and_more'),
        ('tenants', '0020_membership_ui_mode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productserial',
            index=models.Index(fields=['tenant', 'serial'], name='prodserial_tenant_serial'),
        ),
    ]
