# Generated by Django 5.1.15 on 2026-08-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_productserial_prodserial_tenant_serial'),
        ('partners', '0014_partner_idx_partner_tenant_type'),
        ('tenants', '0020_membership_ui_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(db_column='SupplierProductID', primary_key=True, serialize=False)),
                ('supplier_sku', models.CharField(db_column='SupplierSKU', help_text='رقم الصنف في كتالوج المورّد (مثال: 3068.82)', max_length=100)),
                ('supplier_name', models.CharField(blank=True, db_column='SupplierName', default='', help_text='اسم الصنف كما يسمّيه المورّد (اختياري — يساعد على المطابقة)', max_length=255)),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_codes', to='inventory.product')),
                ('supplier', models.ForeignKey(db_column='SupplierID', on_delete=django.db.models.deletion.CASCADE, related_name='product_codes', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='tenants.tenant')),
            ],
            options={
                'db_table': 'supplier_products',
                'ordering': ['supplier_id', 'supplier_sku'],
                'managed': True,
                'indexes': [models.Index(fields=['tenant', 'supplier_sku'], name='idx_tenant_supplier_sku'), models.Index(fields=['tenant', 'product'], name='idx_tenant_supplier_prod')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'supplier', 'supplier_sku'), name='uniq_supplier_sku_per_supplier')],
            },
        ),
    ]
