# Generated by Django 5.1.15 on 2026-08-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.IntegerField(blank=True, db_column='MaxStockLevel', null=True),
        ),
    ]
