# Generated by Django 5.1.15 on 2026-08-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_t_reorder_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_location',
            field=models.CharField(blank=True, db_column='StorageLocation', help_text='موقع الصنف في المستودع (رفّ/ممر) — نصّ إرشادي بلا أثر مخزني', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uom2',
            field=models.ForeignKey(blank=True, db_column='UOM2ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_uom2', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom2_factor',
            field=models.DecimalField(blank=True, db_column='UOM2Factor', decimal_places=6, help_text='كم وحدةً رئيسية في الوحدة الثانية (كرتونة = 12 قطعة ⇒ 12)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uom3',
            field=models.ForeignKey(blank=True, db_column='UOM3ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_uom3', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom3_factor',
            field=models.DecimalField(blank=True, db_column='UOM3Factor', decimal_places=6, help_text='كم وحدةً رئيسية في الوحدة الثالثة', max_digits=18, null=True),
        ),
    ]
