# Generated by Django 5.1.15 on 2026-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_description_product_storage_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allow_preorder',
            field=models.BooleanField(db_column='AllowPreorder', default=False, help_text='إتاحة بيع المنتج كطلب مسبق / عند الطلب حتى لو كان الرصيد صفراً'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(db_column='IsService', default=False, help_text='إذا مفعّل: يُعامل المنتج كخدمة — لا يُخصم من المخزون ويُرحّل لحساب مبيعات الخدمات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_store_only',
            field=models.BooleanField(db_column='IsStoreOnly', default=False, help_text='منتج خاص بالمتجر الإلكتروني فقط — لا يظهر في شاشة المنتجات المخزنية أو محددات فواتير البيع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_location',
            field=models.CharField(blank=True, db_column='StorageLocation', help_text='موقع المنتج في المستودع (رفّ/ممر) — نصّ إرشادي بلا أثر مخزني', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_name',
            field=models.CharField(blank=True, db_column='SupplierName', default='', help_text='اسم المنتج كما يسمّيه المورّد (اختياري — يساعد على المطابقة)', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_sku',
            field=models.CharField(db_column='SupplierSKU', help_text='رقم المنتج في كتالوج المورّد (مثال: 3068.82)', max_length=100),
        ),
    ]
