# Generated by Django 5.1.15 on 2026-08-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_cash_box_treasury'),
        ('inventory', '0024_alter_product_allow_preorder_and_more'),
        ('tenants', '0024_hr_settings_and_ess_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(db_column='ProductFamilyID', primary_key=True, serialize=False)),
                ('name_ar', models.CharField(blank=True, db_column='Name_AR', max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, db_column='Name_EN', max_length=200, null=True)),
                ('min_stock_level', models.IntegerField(blank=True, db_column='MinStockLevel', null=True)),
                ('max_stock_level', models.IntegerField(blank=True, db_column='MaxStockLevel', null=True)),
                ('is_serialized', models.BooleanField(db_column='IsSerialized', default=False)),
                ('is_service', models.BooleanField(db_column='IsService', default=False)),
                ('allow_negative_stock', models.BooleanField(db_column='AllowNegativeStock', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('category', models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families', to='inventory.productcategory')),
                ('ending_inventory_account_override', models.ForeignKey(blank=True, db_column='EndingInventoryAccountOverrideID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families_ending_inventory_override', to='accounting.account')),
                ('purchase_account_override', models.ForeignKey(blank=True, db_column='PurchaseAccountOverrideID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families_purchase_override', to='accounting.account')),
                ('purchase_return_account_override', models.ForeignKey(blank=True, db_column='PurchaseReturnAccountOverrideID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families_purchase_return_override', to='accounting.account')),
                ('sale_account_override', models.ForeignKey(blank=True, db_column='SaleAccountOverrideID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families_sale_override', to='accounting.account')),
                ('sale_return_account_override', models.ForeignKey(blank=True, db_column='SaleReturnAccountOverrideID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families_sale_return_override', to='accounting.account')),
                ('supplier_account_override', models.ForeignKey(blank=True, db_column='SupplierAccountOverrideID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families_supplier_override', to='accounting.account')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='product_families', to='tenants.tenant')),
                ('uom', models.ForeignKey(blank=True, db_column='UOMID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_families', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name_plural': 'Product Families',
                'db_table': 'product_families',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, db_column='ProductFamilyID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='inventory.productfamily'),
        ),
    ]
