# Generated by Django 5.1.15 on 2026-09-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0025_productfamily_product_family'),
        ('tenants', '0024_hr_settings_and_ess_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMerge',
            fields=[
                ('id', models.AutoField(db_column='ProductMergeID', primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(db_column='Snapshot', help_text='لكل براند مُضموم: {product_id, family_id, brand, name_ar, name_en} قبل الضمّ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('undone_at', models.DateTimeField(blank=True, db_column='UndoneAt', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_merges', to=settings.AUTH_USER_MODEL)),
                ('target_family', models.ForeignKey(db_column='TargetFamilyID', on_delete=django.db.models.deletion.CASCADE, related_name='merges', to='inventory.productfamily')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='product_merges', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_merges',
                'managed': True,
            },
        ),
    ]
