# Generated by Django 5.1.15 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_productmerge'),
        ('tenants', '0024_hr_settings_and_ess_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDemandForecast',
            fields=[
                ('id', models.AutoField(db_column='ProductDemandForecastID', primary_key=True, serialize=False)),
                ('level', models.DecimalField(db_column='Level', decimal_places=6, max_digits=18)),
                ('trend', models.DecimalField(db_column='Trend', decimal_places=6, max_digits=18)),
                ('weeks_observed', models.PositiveSmallIntegerField(db_column='WeeksObserved')),
                ('mad', models.DecimalField(blank=True, db_column='MAD', decimal_places=6, max_digits=18, null=True)),
                ('last_week_start', models.DateField(db_column='LastWeekStart')),
                ('computed_at', models.DateTimeField(auto_now=True, db_column='ComputedAt')),
                ('product', models.OneToOneField(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecast', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='product_demand_forecasts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'product_demand_forecasts',
                'managed': True,
            },
        ),
    ]
