# Generated by Django 5.1.15 on 2026-09-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_productdemandforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_mode',
            field=models.CharField(choices=[('manual', 'يدوي'), ('auto', 'تلقائي')], db_column='ReorderMode', default='manual', max_length=10),
        ),
    ]
