# Generated by Django 5.1.15 on 2026-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_product_reorder_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='min_order_qty',
            field=models.DecimalField(blank=True, db_column='MinOrderQty', decimal_places=3, help_text='أقلّ كمية يقبلها هذا المورّد لهذا الصنف في الطلبية الواحدة', max_digits=18, null=True),
        ),
    ]
