# Generated by Django 5.1.15 on 2026-09-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_supplierproduct_min_order_qty'),
        ('tenants', '0032_seed_purchase_rfq_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLayer',
            fields=[
                ('id', models.AutoField(db_column='StockLayerID', primary_key=True, serialize=False)),
                ('layer_date', models.DateField(db_column='LayerDate', help_text='تاريخ ورود البضاعة (من حركة المخزون المصدر)')),
                ('original_qty', models.DecimalField(db_column='OriginalQty', decimal_places=4, help_text='الكمية الأصلية وقت إنشاء الطبقة', max_digits=18)),
                ('remaining_qty', models.DecimalField(db_column='RemainingQty', decimal_places=4, help_text='المتبقّي غير المُستهلَك بعد (يُستهلَك FIFO)', max_digits=18)),
                ('unit_cost', models.DecimalField(db_column='UnitCost', decimal_places=4, help_text='كلفة الوحدة الفعلية لهذه الطبقة', max_digits=18)),
                ('is_provisional', models.BooleanField(db_column='IsProvisional', default=False, help_text='طبقة مؤقّتة نتجت عن بيعٍ على مخزون سالب — تُستعمل في مرحلة لاحقة')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='stock_layers', to='inventory.product')),
                ('source_movement', models.ForeignKey(blank=True, db_column='SourceMovementID', help_text='حركة المخزون الواردة التي أنشأت هذه الطبقة — فارغ للطبقات الافتتاحية التي ينتجها أمر إعادة بناء الرصيد (مرحلة لاحقة)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produced_layers', to='inventory.stockmovement')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='stock_layers', to='tenants.tenant')),
                ('warehouse', models.ForeignKey(blank=True, db_column='WarehouseID', help_text='المستودع الذي وصلت إليه هذه الدفعة — للأثر والتتبّع فقط، لا للتقسيم: الطبقة على مستوى الشركة والمنتج معاً (نظير Product.quantity_on_hand الذي هو رقمٌ واحدٌ على مستوى الشركة)، والاستهلاك لا يُقيَّد بمستودعٍ بعينه.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_layers', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_layers',
                'ordering': ['layer_date', 'id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockLayerConsumption',
            fields=[
                ('id', models.AutoField(db_column='StockLayerConsumptionID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, help_text='الكمية المأخوذة من هذه الطبقة لهذه الحركة', max_digits=18)),
                ('unit_cost', models.DecimalField(db_column='UnitCost', decimal_places=4, help_text='كلفة وحدة الطبقة لحظة الاستهلاك — لقطة لا مرجعاً متحرّكاً', max_digits=18)),
                ('layer', models.ForeignKey(db_column='StockLayerID', on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.stocklayer')),
                ('movement', models.ForeignKey(db_column='MovementID', on_delete=django.db.models.deletion.CASCADE, related_name='layer_consumptions', to='inventory.stockmovement')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='stock_layer_consumptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'stock_layer_consumptions',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='stocklayer',
            index=models.Index(fields=['tenant', 'product', 'remaining_qty'], name='idx_stocklayer_tenant_prod_rem'),
        ),
        migrations.AddIndex(
            model_name='stocklayerconsumption',
            index=models.Index(fields=['tenant', 'movement'], name='idx_slc_tenant_movement'),
        ),
    ]
