# Generated by Django 5.1.15 on 2026-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_stock_fifo_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklayer',
            name='reconciled_qty',
            field=models.DecimalField(db_column='ReconciledQty', decimal_places=4, default=0, help_text='الكمية من هذه الطبقة المؤقّتة التي سُوّيت كلفتها ببضاعةٍ حقيقيّةٍ وصلت لاحقاً (تسويةٌ جزئية مسموحة). المعلَّق = original_qty - reconciled_qty.', max_digits=18),
        ),
    ]
