# Generated by Django 5.1.15 on 2026-09-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_stocklayer_reconciled_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, db_column='ImageURL', default='', max_length=500),
        ),
    ]
