# Generated by Django 6.0.3 on 2026-09-14 15:51

"""رمزُ مستودعٍ فريدٌ في الشركة — قيدٌ تفرضه MySQL فعلاً.

‏**العمودُ المولَّدُ المخزَّنُ يعيد بناء الجدول في MySQL** (`ALGORITHM=COPY`)،
فالجدولُ مقفولٌ للكتابة طوال البناء. الجداولُ الثلاثةُ صغيرةٌ على الإنتاج
(قِيست يوم كتابة الهجرة: صفرُ حاضرين · ٣٩ جهازاً · ٢٤ مستودعاً) فلا أثرَ عمليّ.

والمكرّراتُ تُفحَص **قبل** البناء وتُرفع برسالةٍ تسمّي الصفوف، لا أن تسقط
الهجرةُ بـ`IntegrityError` عارٍ بعد نسخ الجدول كلِّه.
"""

from django.db import migrations, models
import django.db.models.functions.comparison
from django.db.models import Count


def refuse_existing_duplicates(apps, schema_editor):
    Warehouse = apps.get_model("inventory", "Warehouse")
    clashes = (
        Warehouse.objects.exclude(code="")
        .values("tenant_id", "code")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .order_by("tenant_id", "code")
    )
    offenders = [
        f"شركة {row['tenant_id']} · رمز «{row['code']}» ({row['n']} مستودعات)"
        for row in clashes
    ]
    if offenders:
        raise RuntimeError(
            "‏لا يمكن فرضُ «رمزٌ فريدٌ لكلّ مستودعٍ في الشركة»: " + " · ".join(offenders)
            + ". غيِّر الرمزَ المكرَّر (أو أفرِغه) ثمّ أعِد تشغيل الهجرة."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_product_reference_image'),
        ('tenants', '0034_field_staff_role'),
    ]

    operations = [
        migrations.RunPython(
            refuse_existing_duplicates, migrations.RunPython.noop, elidable=False
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='idx_tenant_warehouse_code',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code_key',
            field=models.GeneratedField(db_column='CodeKey', db_persist=True, expression=django.db.models.functions.comparison.NullIf('code', models.Value('')), output_field=models.CharField(max_length=30, null=True), verbose_name='مفتاحُ الرمز'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code_key'), name='idx_tenant_warehouse_code'),
        ),
    ]
