# Generated by Django 5.1.15 on 2026-09-16 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_conditional_uniqueness_becomes_real'),
        ('tenants', '0034_field_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLayerReconciliation',
            fields=[
                ('id', models.AutoField(db_column='StockLayerReconciliationID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, help_text='الكمية التي سدّها هذا الوارد من الطبقة المؤقّتة', max_digits=18)),
                ('provisional_unit_cost', models.DecimalField(db_column='ProvisionalUnitCost', decimal_places=4, help_text='الكلفة المخمَّنة للطبقة لحظة السدّ — لقطة لا مرجعاً متحرّكاً', max_digits=18)),
                ('layer', models.ForeignKey(db_column='StockLayerID', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='inventory.stocklayer')),
                ('movement', models.ForeignKey(db_column='MovementID', on_delete=django.db.models.deletion.CASCADE, related_name='layer_reconciliations', to='inventory.stockmovement')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='stock_layer_reconciliations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'stock_layer_reconciliations',
                'ordering': ['id'],
                'managed': True,
                'indexes': [models.Index(fields=['tenant', 'movement'], name='idx_slr_tenant_movement')],
            },
        ),
    ]
