# Generated by Django 5.1.15 on 2026-09-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_stock_layer_reconciliation'),
        ('sales', '0043_customerpayment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserial',
            name='return_line',
            field=models.ForeignKey(blank=True, db_column='ReturnSalesInvoiceLineID', help_text='بند مرجع البيع الذي أعاد هذه الوحدة للمخزن', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_serial_units', to='sales.salesinvoiceline'),
        ),
    ]
