# Generated by Django 6.1.1 on 2026-09-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_updated_at_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allow_negative_stock',
        ),
        migrations.RemoveField(
            model_name='productfamily',
            name='allow_negative_stock',
        ),
    ]
