# Generated by Django 6.1.1 on 2026-09-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0004_serviceorderpart_issued_cost_and_more'),
        ('inventory', '0037_remove_product_allow_negative_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productserial',
            name='issued_to',
            field=models.ForeignKey(blank=True, db_column='IssuedToServiceOrderPartID', help_text='بند المستند الذي صرف هذه الوحدة خارج مسار البيع (لا فاتورة)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_serial_units', to='after_sales.serviceorderpart'),
        ),
        migrations.AlterField(
            model_name='productserial',
            name='status',
            field=models.CharField(choices=[('in_stock', 'في المخزن'), ('sold', 'مُباع'), ('issued', 'مصروفة خارج البيع')], db_column='Status', default='in_stock', max_length=20),
        ),
    ]
