# Generated by Django 6.1.1 on 2026-09-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_productserial_issued_to_alter_productserial_status'),
        # #231: هذا العمود مصدر بيانات هجرة `after_sales` التي تنسخها إلى
        # `WarrantyPolicy` — لا يجوز أن يُحذف قبلها. الاعتمادية تفرض الترتيب
        # حتى لو طُبِّقت الهجرتان في تشغيلةٍ واحدة (`migrate` من صفر).
        ('after_sales', '0008_backfill_warranty_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_warranty_months',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_months',
        ),
    ]
