# Generated by Django 6.1.1 on 2026-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_remove_warranty_months_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productserial',
            name='status',
            field=models.CharField(choices=[('in_stock', 'في المخزن'), ('sold', 'مُباع'), ('issued', 'مصروفة خارج البيع'), ('defective', 'معطوبة لدينا')], db_column='Status', default='in_stock', max_length=20),
        ),
    ]
