# Generated by Django 6.1.1 on 2026-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_replacement_slice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('SHIPMENT', 'شحنة'), ('DEAL', 'صفقة'), ('CLEARANCE', 'تخليص جمركي'), ('MANUAL', 'يدوي'), ('SALE', 'بيع'), ('STOCK_ISSUE', 'إذن صرف'), ('PURCHASE_INVOICE', 'فاتورة شراء'), ('WAREHOUSE_TRANSFER', 'تحويل مستودعي'), ('STOCKTAKE', 'جرد'), ('GOODS_RECEIPT', 'سند استلام'), ('DELIVERY_NOTE', 'سند تسليم'), ('SERVICE_ISSUE', 'صرف قطع كفالة'), ('SERVICE_RESTOCK', 'عودة وحدة معطوبة للمخزن')], db_column='ReferenceType', default='MANUAL', max_length=20),
        ),
    ]
