# Generated by Django 6.1.1 on 2026-10-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_restock_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True, help_text='المنتج النشط وحده يظهر في قوائم ومنتقيات المستندات الجديدة؛ المعطَّل يبقى على المستندات القديمة والتقارير'),
        ),
    ]
