# Generated by Django 5.1.15 on 2026-08-04 19:00

import accountant_portal.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_tenantmodule'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_jurisdiction', models.CharField(choices=[('PS', 'فلسطين'), ('PS_IL_DUAL', 'فلسطين وإسرائيل')], default='PS', max_length=10)),
                ('strict_invoice_field_validation', models.BooleanField(default=False)),
                ('clearance_mode', models.CharField(choices=[('manual', 'يدوي'), ('api_reserved', 'API محجوز')], default='manual', max_length=20)),
                ('is_israeli_registered_dealer', models.BooleanField(default=False)),
                ('require_reauth_for_sensitive', models.BooleanField(default=True)),
                ('reauth_window_minutes', models.PositiveSmallIntegerField(default=15)),
                ('engagement_retention_years', models.PositiveSmallIntegerField(default=5)),
                ('allow_grant_cost_view', models.BooleanField(default=True)),
                ('invitation_expiry_days', models.PositiveSmallIntegerField(default=14, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('max_active_engagements', models.PositiveIntegerField(default=0)),
                ('lock_blocks_posting', models.BooleanField(default=True)),
                ('default_grant_profile', models.CharField(choices=[('review_only', 'مراجعة فقط'), ('review_and_prepare', 'مراجعة وتجهيز'), ('full_accounting', 'محاسبة كاملة')], default='review_only', max_length=24)),
                ('tax_period_type', models.CharField(choices=[('monthly', 'شهري'), ('custom', 'مخصص')], default='monthly', max_length=10)),
                ('filing_due_days', models.PositiveSmallIntegerField(default=15)),
                ('input_vat_window_months', models.PositiveSmallIntegerField(default=6)),
                ('allow_accountant_reopen', models.BooleanField(default=False)),
                ('export_formats', models.JSONField(default=accountant_portal.models.default_export_formats)),
                ('notify_company_on_accountant_action', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_portal_settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'acct_portal_settings',
            },
        ),
        migrations.CreateModel(
            name='AccountantEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('active', 'نشط'), ('suspended', 'معلق'), ('revoked', 'ملغى'), ('declined', 'مرفوض'), ('expired', 'منتهي')], default='pending', max_length=20)),
                ('initiated_by', models.CharField(choices=[('accountant', 'المحاسب'), ('company', 'الشركة')], max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('invitation_token_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_used_at', models.DateTimeField(blank=True, null=True)),
                ('approved_scope_snapshot', models.JSONField(default=list)),
                ('engagement_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountant_engagements', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accountant_engagements', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_accountant_engagements', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_accountant_engagements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_engagements', to='tenants.tenant')),
            ],
            options={
                'db_table': 'acct_portal_engagements',
                'indexes': [models.Index(fields=['tenant', 'status'], name='acct_eng_tenant_status'), models.Index(fields=['accountant', 'status'], name='acct_eng_user_status')],
                'constraints': [models.UniqueConstraint(fields=('accountant', 'tenant'), name='uniq_acct_engagement_tenant')],
            },
        ),
        migrations.CreateModel(
            name='AccountantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='legal_accountant', max_length=30)),
                ('professional_type', models.CharField(choices=[('lawyer', 'محامٍ'), ('licensed_auditor', 'مدقق حسابات مرخص'), ('accountant', 'محاسب'), ('finance_diploma', 'دبلوم مالية'), ('ex_tax_officer', 'موظف ضريبة سابق')], max_length=30)),
                ('license_number', models.CharField(blank=True, default='', max_length=60)),
                ('license_authority', models.CharField(blank=True, default='', max_length=120)),
                ('tax_registration_number', models.CharField(max_length=50)),
                ('business_address', models.TextField()),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'غير موثق'), ('pending_review', 'بانتظار المراجعة'), ('verified', 'موثق'), ('rejected', 'مرفوض'), ('barred', 'ممنوع')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('barred_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_accountant_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acct_portal_profiles',
                'constraints': [models.UniqueConstraint(fields=('tax_registration_number',), name='uniq_acct_profile_tax_reg')],
            },
        ),
    ]
