# Generated by Django 6.0.3 on 2026-08-05 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_portal', '0001_initial'),
        ('sales', '0032_salessettings_block_reserved_stock_sale'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPeriodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('in_review', 'قيد المراجعة'), ('needs_company_action', 'بانتظار الشركة'), ('ready', 'جاهزة'), ('approved', 'معتمدة'), ('submitted', 'مقدَّمة'), ('locked', 'مقفلة')], default='in_review', max_length=24)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_reference', models.CharField(blank=True, default='', max_length=120)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_count', models.PositiveSmallIntegerField(default=0)),
                ('last_reopen_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tax_period_reviews', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_tax_period_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_tax_period_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_period_reviews', to='tenants.tenant')),
                ('vat_statement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_review', to='sales.vatstatement')),
            ],
            options={
                'db_table': 'acct_portal_period_reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('sales_invoice', 'فاتورة بيع'), ('purchase_invoice', 'فاتورة شراء'), ('journal', 'قيد محاسبي'), ('customer_payment', 'سند قبض'), ('supplier_payment', 'سند صرف'), ('partner', 'طرف'), ('period', 'فترة ضريبية'), ('other', 'أخرى')], default='other', max_length=40)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('severity', models.CharField(choices=[('blocker', 'مانع'), ('warning', 'تحذير'), ('info', 'معلومة')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('answered', 'مُجاب'), ('resolved', 'مُغلق'), ('withdrawn', 'مسحوب')], default='open', max_length=12)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answer_body', models.TextField(blank=True, default='')),
                ('attachment_url', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_review_queries', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_queries', to='accountant_portal.accountantengagement')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_review_queries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_review_queries', to='tenants.tenant')),
                ('period_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='accountant_portal.taxperiodreview')),
            ],
            options={
                'db_table': 'acct_portal_review_queries',
            },
        ),
        migrations.AddIndex(
            model_name='taxperiodreview',
            index=models.Index(fields=['tenant', 'status'], name='acct_period_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='taxperiodreview',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_from', 'period_to'), name='uniq_acct_period_window'),
        ),
        migrations.AddIndex(
            model_name='reviewquery',
            index=models.Index(fields=['tenant', 'status', 'severity'], name='acct_q_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='reviewquery',
            index=models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='acct_q_tenant_entity'),
        ),
    ]
