# Generated by Django 6.0.3 on 2026-08-14 16:22

import accountant_portal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_portal', '0002_period_review_and_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200)),
                ('contact_first', models.CharField(blank=True, default='', max_length=100)),
                ('contact_last', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('mobile', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('sector', models.CharField(blank=True, default='', max_length=120)),
                ('tax_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('archived', 'مؤرشف')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_clients', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_clients', to='accountant_portal.accountantengagement')),
            ],
            options={
                'db_table': 'acct_portal_practice_clients',
            },
        ),
        migrations.CreateModel(
            name='PracticeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('annual', 'سنوي'), ('monthly', 'شهري'), ('once', 'مرة واحدة')], default='monthly', max_length=10)),
                ('team_note', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('in_progress', 'قيد التنفيذ'), ('done', 'منجز')], default='planned', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_programs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accountant_portal.practiceclient')),
            ],
            options={
                'db_table': 'acct_portal_practice_programs',
            },
        ),
        migrations.CreateModel(
            name='PracticeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_documents', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accountant_portal.practiceclient')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accountant_portal.practiceprogram')),
            ],
            options={
                'db_table': 'acct_portal_practice_documents',
            },
        ),
        migrations.CreateModel(
            name='PracticeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_program_due_days', models.PositiveSmallIntegerField(default=15)),
                ('service_types', models.JSONField(default=accountant_portal.models.default_service_types)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_settings', to='accountant_portal.accountantprofile')),
            ],
            options={
                'db_table': 'acct_portal_practice_settings',
            },
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('done', 'منجز')], default='open', max_length=6)),
                ('kind', models.CharField(choices=[('appointment', 'موعد'), ('deadline', 'استحقاق')], default='appointment', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accountant_portal.practiceclient')),
            ],
            options={
                'db_table': 'acct_portal_practice_tasks',
            },
        ),
        migrations.AddIndex(
            model_name='practiceclient',
            index=models.Index(fields=['accountant', 'status'], name='acct_pc_user_status'),
        ),
        migrations.AddConstraint(
            model_name='practiceclient',
            constraint=models.UniqueConstraint(fields=('accountant', 'trade_name'), name='uniq_practice_client_name'),
        ),
        migrations.AddIndex(
            model_name='practiceprogram',
            index=models.Index(fields=['accountant', 'status'], name='acct_pp_user_status'),
        ),
        migrations.AddIndex(
            model_name='practiceprogram',
            index=models.Index(fields=['accountant', 'due_date'], name='acct_pp_user_due'),
        ),
        migrations.AddIndex(
            model_name='practicedocument',
            index=models.Index(fields=['accountant', 'client'], name='acct_pd_user_client'),
        ),
        migrations.AddIndex(
            model_name='practicetask',
            index=models.Index(fields=['accountant', 'status', 'due_at'], name='acct_pt_user_due'),
        ),
    ]
