# Generated by Django 5.1.15 on 2026-09-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_portal', '0004_practiceclient_managed_tenant'),
        ('partners', '0014_partner_idx_partner_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicedocument',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_documents', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='practiceprogram',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_programs', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='practicetask',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_tasks', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='practicedocument',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accountant_portal.practiceclient'),
        ),
        migrations.AlterField(
            model_name='practiceprogram',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accountant_portal.practiceclient'),
        ),
    ]
