# Generated by Django 5.1.15 on 2026-09-03 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant_portal', '0005_practicedocument_partner_practiceprogram_partner_and_more'),
        ('partners', '0015_partner_engagement_partner_managed_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeClientArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_client_archives', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_archive_flags', to='partners.partner')),
            ],
            options={
                'db_table': 'acct_portal_practice_client_archive',
                'constraints': [models.UniqueConstraint(fields=('accountant', 'partner'), name='uniq_practice_client_archive')],
            },
        ),
    ]
