from django.urls import path

from accountant_portal import views


urlpatterns = [
    path("", views.portal_status, name="accountant-portal-status"),
    path("signup/", views.AccountantSignupView.as_view(), name="accountant-signup"),
    path("verify-email/", views.VerifyEmailView.as_view(), name="accountant-verify-email"),
    path("resend-verification/", views.ResendVerificationView.as_view(), name="accountant-resend-verification"),
    path("me/", views.AccountantMeView.as_view(), name="accountant-me"),
    path("me/submit-verification/", views.SubmitProfileVerificationView.as_view(), name="accountant-submit-verification"),
    path("workspace/companies/", views.WorkspaceCompaniesView.as_view(), name="accountant-workspace-companies"),
    path("engagements/", views.AccountantEngagementListView.as_view(), name="accountant-engagements"),
    path("companies/lookup/", views.CompanyLookupView.as_view(), name="accountant-company-lookup"),
    path("engagements/request/", views.RequestEngagementView.as_view(), name="accountant-engagement-request"),
    path("engagements/accept-invite/", views.AcceptInvitationView.as_view(), name="accountant-accept-invite"),
    path("engagements/<int:engagement_id>/withdraw/", views.WithdrawEngagementView.as_view(), name="accountant-withdraw"),
    path("engagements/<int:engagement_id>/resign/", views.ResignEngagementView.as_view(), name="accountant-resign"),
    path("practice/overview/", views.PracticeOverviewView.as_view(), name="accountant-practice-overview"),
    path("client/documents/", views.ClientDocumentsView.as_view(), name="accountant-client-documents"),
    path("client/statements/", views.ClientStatementsView.as_view(), name="accountant-client-statements"),
    path("client/trend/", views.ClientTrendView.as_view(), name="accountant-client-trend"),
    path("client/summary/", views.ClientSummaryView.as_view(), name="accountant-client-summary"),
    path("tax/periods/", views.TaxPeriodListView.as_view(), name="accountant-tax-periods"),
    path("tax/periods/prepare/", views.TaxPeriodPrepareView.as_view(), name="accountant-tax-period-prepare"),
    path("tax/periods/<int:period_id>/", views.TaxPeriodDetailView.as_view(), name="accountant-tax-period-detail"),
    path("tax/periods/<int:period_id>/readiness/", views.TaxPeriodReadinessView.as_view(), name="accountant-tax-period-readiness"),
    path("tax/periods/<int:period_id>/approve/", views.TaxPeriodApproveView.as_view(), name="accountant-tax-period-approve"),
    path("tax/periods/<int:period_id>/reopen/", views.TaxPeriodReopenView.as_view(), name="accountant-tax-period-reopen"),
    path("tax/periods/<int:period_id>/mark-submitted/", views.TaxPeriodSubmitView.as_view(), name="accountant-tax-period-submit"),
    path("tax/clearance/", views.TaxClearanceView.as_view(), name="accountant-tax-clearance"),
    path("review/queries/", views.ReviewQueryListCreateView.as_view(), name="accountant-review-queries"),
    path("review/queries/<int:query_id>/answer/", views.ReviewQueryAnswerView.as_view(), name="accountant-review-query-answer"),
    path("review/queries/<int:query_id>/resolve/", views.ReviewQueryResolveView.as_view(), name="accountant-review-query-resolve"),
    path("review/queries/<int:query_id>/withdraw/", views.ReviewQueryWithdrawView.as_view(), name="accountant-review-query-withdraw"),
    path("review/export/", views.ReviewPackageExportView.as_view(), name="accountant-review-export"),
    path("activity/", views.AccountantActivityView.as_view(), name="accountant-activity"),
    path("company/engagements/", views.CompanyEngagementListView.as_view(), name="company-engagements"),
    path("company/engagements/invite/", views.CompanyInviteView.as_view(), name="company-engagement-invite"),
    path("company/engagements/<int:engagement_id>/approve/", views.CompanyApproveView.as_view(), name="company-engagement-approve"),
    path("company/engagements/<int:engagement_id>/decline/", views.CompanyDeclineView.as_view(), name="company-engagement-decline"),
    path("company/engagements/<int:engagement_id>/suspend/", views.CompanySuspendView.as_view(), name="company-engagement-suspend"),
    path("company/engagements/<int:engagement_id>/resume/", views.CompanyResumeView.as_view(), name="company-engagement-resume"),
    path("company/engagements/<int:engagement_id>/revoke/", views.CompanyRevokeView.as_view(), name="company-engagement-revoke"),
    path("company/engagements/<int:engagement_id>/scope/", views.CompanyScopeView.as_view(), name="company-engagement-scope"),
    path("company/engagements/scope-catalog/", views.CompanyScopeCatalogView.as_view(), name="company-engagement-scope-catalog"),
    path("company/settings/", views.CompanyPortalSettingsView.as_view(), name="company-portal-settings"),
]
