# Generated by Django 5.1.15 on 2026-09-13 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_ops', '0023_platformemployee_job_title_platformemployee_phone_and_more'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الملف')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='عدد الصفوف')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفوف المُنشأة')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفوف المكرَّرة')),
                ('invalid_count', models.PositiveIntegerField(default=0, verbose_name='عدد الصفوف غير الصالحة')),
                ('duplicates', models.JSONField(blank=True, default=list, help_text='عناصر {row, phone, existing_lead_id, existing_lead_name, assigned_to_name}.', verbose_name='تفاصيل التكرار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='رافع الملف')),
            ],
            options={
                'verbose_name': 'دفعة استيراد عملاء',
                'verbose_name_plural': 'دفعات استيراد العملاء',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='اسم المحل')),
                ('owner_name', models.CharField(blank=True, default='', max_length=150, verbose_name='صاحب المحل')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان')),
                ('activity', models.CharField(blank=True, default='', max_length=150, verbose_name='النشاط')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم الاتصال'), ('interested', 'مهتم'), ('follow_up', 'متابعة'), ('customer', 'عميل'), ('not_interested', 'غير مهتم'), ('no_answer', 'لا يجيب'), ('wrong_number', 'رقم خاطئ'), ('postponed', 'مؤجل'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإسناد')),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد المتابعة القادمة')),
                ('source', models.CharField(choices=[('admin_upload', 'رفع المدير'), ('employee_suggestion', 'اقتراح موظف'), ('public_form', 'نموذج عام'), ('referral', 'إحالة'), ('whatsapp', 'واتساب'), ('web', 'الموقع')], default='admin_upload', max_length=24, verbose_name='المصدر')),
                ('approval_status', models.CharField(choices=[('approved', 'معتمد'), ('pending', 'بانتظار الاعتماد'), ('rejected', 'مرفوض')], default='approved', max_length=12, verbose_name='حالة الاعتماد')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='سبب رفض الاقتراح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='`None` يعني أنّ العميل في المخزن المتاح لا أنّ لا أحد سُئل.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_leads', to='platform_ops.platformemployee', verbose_name='الموظف المسند')),
                ('converted_tenant', models.ForeignKey(blank=True, help_text='يُملأ حين يصير هذا العميل المحتمَل شركةً فعليّة على المنصّة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant', verbose_name='الشركة الناتجة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_suggested_leads', to='platform_ops.platformemployee', verbose_name='مقترح العميل')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadimportbatch', verbose_name='دفعة الاستيراد')),
            ],
            options={
                'verbose_name': 'زبون محتمَل',
                'verbose_name_plural': 'زبائن محتمَلون',
            },
        ),
        migrations.CreateModel(
            name='LeadPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='الرقم المطبَّع')),
                ('raw', models.CharField(max_length=32, verbose_name='كما كُتب')),
                ('kind', models.CharField(choices=[('primary', 'أساسي'), ('whatsapp', 'واتساب'), ('secondary', 'ثانوي'), ('owner_mobile', 'جوال المالك')], max_length=16, verbose_name='النوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='crm.lead', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'هاتف عميل محتمَل',
                'verbose_name_plural': 'هواتف العملاء المحتمَلين',
            },
        ),
        migrations.CreateModel(
            name='LeadTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'بانتظار القرار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='من بتّ')),
                ('from_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_transfers_out', to='platform_ops.platformemployee', verbose_name='من')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='crm.lead', verbose_name='العميل')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='طالب التحويل')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_transfers_in', to='platform_ops.platformemployee', verbose_name='إلى')),
            ],
            options={
                'verbose_name': 'تحويل عميل',
                'verbose_name_plural': 'تحويلات العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('call', 'مكالمة'), ('whatsapp', 'واتساب'), ('visit', 'زيارة'), ('note', 'ملاحظة'), ('status_change', 'تغيير حالة'), ('assignment', 'إسناد'), ('transfer', 'تحويل'), ('materials_sent', 'إرسال مواد')], max_length=20, verbose_name='النوع')),
                ('body', models.TextField(blank=True, default='', verbose_name='ماذا حدث')),
                ('outcome', models.CharField(blank=True, default='', max_length=120, verbose_name='النتيجة')),
                ('materials', models.JSONField(blank=True, default=list, verbose_name='المواد المُرسَلة')),
                ('status_before', models.CharField(blank=True, default='', max_length=20, verbose_name='الحالة قبل')),
                ('status_after', models.CharField(blank=True, default='', max_length=20, verbose_name='الحالة بعد')),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد المتابعة القادمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت النشاط')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_lead_activities', to='platform_ops.platformemployee', verbose_name='الموظف')),
                ('lead', models.ForeignKey(help_text='PROTECT مقصود: عميلٌ له سجلّ تواصل لا يُحذف.', on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='crm.lead', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'نشاطُ تواصل',
                'verbose_name_plural': 'أنشطة التواصل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='crm_leadact_lead_id_639066_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='crm_lead_assigne_36bf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', '-created_at'], name='crm_lead_status_d0e831_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['approval_status'], name='crm_lead_approva_410be4_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadphone',
            constraint=models.UniqueConstraint(fields=('lead', 'kind'), name='crm_leadphone_one_per_kind'),
        ),
    ]
