# Generated by Django 6.1.1 on 2026-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('answered', 'ردّ'), ('no_answer', 'لم يردّ'), ('busy', 'مشغول'), ('unreachable', 'مغلق / خارج التغطية'), ('wrong_number', 'رقم خاطئ'), ('callback', 'طلب معاودة الاتصال')], default='', max_length=120, verbose_name='النتيجة'),
        ),
    ]
