import React, { useMemo, useState } from 'react';
import { ArrowRightLeft, MapPin, MessageCircle, Phone, Plus, StickyNote } from 'lucide-react';

import type { CrmActivity, CrmActivityInput, CrmColleague, CrmLead, CrmLeadStatus } from '../../../../services/platformCrmApi';
import { formatDateTimeValue } from '../../../../utils/formatDate';
import { formatNumber } from '../../../../utils/formatNumber';
import { STATUS_LABELS } from './CrmLeadList';

const HAPPY_PATH: CrmLeadStatus[] = ['new', 'contacted', 'interested', 'follow_up', 'customer'];
const ACTIVITY_LABELS: Record<CrmActivity['kind'], string> = { call: 'مكالمة', whatsapp: 'واتساب', visit: 'زيارة', note: 'ملاحظة', status_change: 'تغيير حالة', assignment: 'إسناد', transfer: 'تحويل', materials_sent: 'إرسال مواد' };

interface CrmLeadProfileProps {
  lead: CrmLead; activities: CrmActivity[]; loading: boolean; error: string; isManager: boolean; isOwner: boolean; colleagues: CrmColleague[];
  onBack: () => void; onStatus: (status: CrmLeadStatus, body: string) => void; onActivity: (input: CrmActivityInput) => void;
  onTransfer: (toEmployee: number, reason: string, direct: boolean) => void;
  /** السببُ يأتي من حقلٍ في الصفحة لا من حوار المتصفّح. */
  onRelease: (reason: string) => void;
}

export const CrmLeadProfile: React.FC<CrmLeadProfileProps> = ({ lead, activities, loading, error, isManager, isOwner, colleagues, onBack, onStatus, onActivity, onTransfer, onRelease }) => {
  const [noteOpen, setNoteOpen] = useState(false); const [activityKind, setActivityKind] = useState<CrmActivityInput['kind']>('note');
  const [body, setBody] = useState(''); const [nextFollowUp, setNextFollowUp] = useState(''); const [status, setStatus] = useState<CrmLeadStatus>(lead.status);
  const [transferTo, setTransferTo] = useState(''); const [reason, setReason] = useState('');
  const [releaseOpen, setReleaseOpen] = useState(false); const [releaseReason, setReleaseReason] = useState('');
  const availableColleagues = useMemo(() => colleagues.filter((employee) => !employee.is_me), [colleagues]);
  const happyIndex = HAPPY_PATH.indexOf(lead.status);
  // **رقمان لا رقمٌ واحد.** كان متغيّرٌ واحدٌ اسمُه `primaryPhone` يُفضّل رقمَ
  // واتساب، ثمّ يُعرَض في السطر «📞» — فيظهر رقمُ الواتساب مكانَ الأساسيّ.
  // والنموذجُ البصريُّ يفصلهما: «📞 الرقم» ثمّ شارةُ واتساب.
  const displayPhone = lead.phones.find((phone) => phone.kind === 'primary') || lead.phones[0];
  const whatsappPhone = lead.phones.find((phone) => phone.kind === 'whatsapp') || displayPhone;
  // الشارةُ لا تُرسَم إلّا إن كان للعميل رقمُ واتساب مسجَّلٌ فعلاً: شارةٌ ثابتةٌ
  // تُخبر الموظّفَ أنّ للمحلّ واتساب وهو غيرُ معروف — ادّعاءٌ لا بيانات.
  const hasWhatsApp = lead.phones.some((phone) => phone.kind === 'whatsapp');
  // حالةُ المنتقي تتبع العميلَ: بلا هذا يبقى المنتقي على الحالة القديمة بعد
  // الحفظ فيخالف ما تعرضه الترويسةُ فوقه.
  React.useEffect(() => { setStatus(lead.status); }, [lead.status]);
  const openActivity = (kind: CrmActivityInput['kind']) => { setActivityKind(kind); setNoteOpen(true); };
  const submitActivity = (event: React.FormEvent) => { event.preventDefault(); onActivity({ kind: activityKind, body, next_follow_up_at: nextFollowUp ? `${nextFollowUp}T09:00:00` : null }); setBody(''); setNextFollowUp(''); setNoteOpen(false); };
  const submitTransfer = (event: React.FormEvent) => { event.preventDefault(); if (!transferTo || !reason.trim()) return; onTransfer(Number(transferTo), reason, isOwner || isManager); setReason(''); setTransferTo(''); };

  return <section className="space-y-4" aria-label="ملف العميل">
    <button type="button" onClick={onBack} className="text-sm font-bold text-cyan-300 hover:text-cyan-200">← العودة إلى العملاء</button>
    <header className="rounded-2xl border border-[var(--staff-line)] bg-[var(--staff-panel)] p-5 shadow-lg shadow-black/30"><p className="text-sm text-[var(--staff-muted)]">ملف العميل</p><h1 className="mt-2 text-xl font-extrabold text-[var(--staff-text)]">🏪 {lead.store_name}</h1><p className="mt-2 text-sm text-[var(--staff-muted)]">صاحب المحل: {lead.owner_name || 'غير مسجل'}</p>{lead.city || lead.address ? <p className="mt-2 flex items-center gap-2 text-sm text-[var(--staff-muted)]"><MapPin className="h-4 w-4 text-cyan-300" />{[lead.city, lead.address].filter(Boolean).join(' – ')}</p> : null}<div className="mt-3 flex flex-wrap gap-4 text-sm"><span dir="ltr" className="inline-flex items-center gap-1 text-cyan-300"><Phone className="h-4 w-4" />{displayPhone?.raw || 'لا يوجد رقم'}</span>{hasWhatsApp && <span className="text-emerald-300">🟢 WhatsApp</span>}</div><div className="mt-4 border-t border-[var(--staff-line)] pt-4 text-sm"><p>الموظف المسؤول: <strong className="text-[var(--staff-text)]">{lead.assigned_to?.name || 'في المخزن المتاح'}</strong></p><p className="mt-1">الحالة: <strong className="text-amber-200">{STATUS_LABELS[lead.status]}</strong></p></div></header>

    <section className="rounded-2xl border border-[var(--staff-line)] bg-[var(--staff-panel)] p-5 shadow-lg shadow-black/30"><h2 className="font-extrabold text-[var(--staff-text)]">حالة العميل</h2><div className="mt-4 grid grid-cols-5 gap-2" aria-label="مسار حالة العميل">{HAPPY_PATH.map((item, index) => <div key={item} className="min-w-0 text-center"><span className={`mx-auto flex h-7 w-7 items-center justify-center rounded-full text-xs font-extrabold ${happyIndex >= index ? 'bg-[var(--staff-accent)] text-slate-950' : 'bg-black/20 text-[var(--staff-muted)]'}`}>{formatNumber(index + 1)}</span><span className="mt-2 block truncate text-xs text-[var(--staff-muted)]">{STATUS_LABELS[item]}</span></div>)}</div><p className="mt-3 text-sm text-[var(--staff-muted)]">{happyIndex === -1 ? `الحالة الحالية: ${STATUS_LABELS[lead.status]}` : `المرحلة ${formatNumber(happyIndex + 1)} من ${formatNumber(HAPPY_PATH.length)}`}</p><div className="mt-4 flex flex-wrap gap-2"><select value={status} onChange={(event) => setStatus(event.target.value as CrmLeadStatus)} className="rounded-lg border border-[var(--staff-line)] bg-black/15 px-3 py-2 text-sm text-[var(--staff-text)]" aria-label="تغيير حالة العميل">{Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={() => onStatus(status, '')} className="rounded-lg border border-cyan-400/50 px-3 py-2 text-sm font-bold text-cyan-300">حفظ الحالة</button></div></section>

    <section className="rounded-2xl border border-[var(--staff-line)] bg-[var(--staff-panel)] p-5 shadow-lg shadow-black/30"><h2 className="font-extrabold text-[var(--staff-text)]">سجل التواصل</h2>{loading ? <p className="mt-4 text-sm text-[var(--staff-muted)]">جارٍ تحميل سجل التواصل...</p> : error ? <p className="mt-4 text-sm text-rose-300" role="alert">{error}</p> : activities.length === 0 ? <p className="mt-4 text-sm text-[var(--staff-muted)]">لا توجد أنشطة مسجلة بعد. أضف ملاحظة أو سجّل اتصالاً بعد حدوثه.</p> : <ol className="mt-4 divide-y divide-[var(--staff-line)]">{activities.map((activity) => <li key={activity.id} className="py-4 first:pt-0"><div className="flex flex-wrap justify-between gap-2 text-xs text-[var(--staff-muted)]"><span>{formatDateTimeValue(activity.created_at)} · {activity.employee?.name || 'النظام'}</span><span>#{formatNumber(activity.id)}</span></div><p className="mt-2 text-sm font-bold text-[var(--staff-text)]">{ACTIVITY_LABELS[activity.kind]}{activity.body ? `: ${activity.body}` : ''}</p>{activity.materials.length > 0 && <p className="mt-1 text-sm text-[var(--staff-muted)]">المواد المرسلة: {activity.materials.join(' + ')}</p>}{activity.next_follow_up_at && <p className="mt-1 text-sm text-cyan-300">المتابعة القادمة: {formatDateTimeValue(activity.next_follow_up_at)}</p>}</li>)}</ol>}<div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => openActivity('note')} className="inline-flex items-center gap-2 rounded-lg border border-[var(--staff-line)] px-3 py-2 text-sm font-bold text-[var(--staff-text)]"><StickyNote className="h-4 w-4" />إضافة ملاحظة</button>{whatsappPhone && <a href={`https://wa.me/${whatsappPhone.e164.replace(/\D/g, '')}`} target="_blank" rel="noopener noreferrer" onClick={() => openActivity('whatsapp')} className="inline-flex items-center gap-2 rounded-lg bg-emerald-400 px-3 py-2 text-sm font-bold text-slate-950"><MessageCircle className="h-4 w-4" />إرسال WhatsApp</a>}<button type="button" onClick={() => openActivity('call')} className="inline-flex items-center gap-2 rounded-lg border border-cyan-400/50 px-3 py-2 text-sm font-bold text-cyan-300"><Phone className="h-4 w-4" />تسجيل اتصال</button></div></section>

    {noteOpen && <form onSubmit={submitActivity} className="rounded-2xl border border-cyan-400/40 bg-[var(--staff-panel)] p-5 shadow-lg shadow-black/30"><h2 className="font-extrabold text-[var(--staff-text)]">سجّل ما حدث</h2><p className="mt-1 text-sm text-[var(--staff-muted)]">فتح واتساب لا يسجل نشاطاً؛ أضف ما حدث فقط إن رغبت.</p><label className="mt-4 block text-sm font-bold text-[var(--staff-text)]" htmlFor="crm-activity-body">التفاصيل</label><textarea id="crm-activity-body" value={body} onChange={(event) => setBody(event.target.value)} className="mt-2 min-h-24 w-full rounded-xl border border-[var(--staff-line)] bg-black/15 p-3 text-sm text-[var(--staff-text)]" /><label className="mt-3 block text-sm font-bold text-[var(--staff-text)]" htmlFor="crm-follow-up">المتابعة القادمة</label><input id="crm-follow-up" type="date" value={nextFollowUp} onChange={(event) => setNextFollowUp(event.target.value)} className="mt-2 rounded-lg border border-[var(--staff-line)] bg-black/15 px-3 py-2 text-sm text-[var(--staff-text)]" /><div className="mt-4 flex gap-2"><button type="submit" className="rounded-lg bg-[var(--staff-accent)] px-4 py-2 text-sm font-extrabold text-slate-950">حفظ السجل</button><button type="button" onClick={() => setNoteOpen(false)} className="rounded-lg border border-[var(--staff-line)] px-4 py-2 text-sm font-bold text-[var(--staff-text)]">إلغاء</button></div></form>}

    <form onSubmit={submitTransfer} className="rounded-2xl border border-[var(--staff-line)] bg-[var(--staff-panel)] p-5 shadow-lg shadow-black/30"><h2 className="flex items-center gap-2 font-extrabold text-[var(--staff-text)]"><ArrowRightLeft className="h-5 w-5 text-cyan-300" />{isOwner || isManager ? 'تحويل العميل' : 'طلب تحويل العميل'}</h2><p className="mt-1 text-sm text-[var(--staff-muted)]">الموظف الحالي: {lead.assigned_to?.name || 'في المخزن المتاح'}</p><label className="mt-4 block text-sm font-bold text-[var(--staff-text)]" htmlFor="crm-transfer-to">تحويل إلى</label><select required id="crm-transfer-to" value={transferTo} onChange={(event) => setTransferTo(event.target.value)} className="mt-2 w-full rounded-lg border border-[var(--staff-line)] bg-black/15 px-3 py-2 text-sm text-[var(--staff-text)]"><option value="">اختر الموظف</option>{availableColleagues.map((employee) => <option key={employee.id} value={employee.id}>{employee.name} · {employee.job_title}</option>)}</select><label className="mt-3 block text-sm font-bold text-[var(--staff-text)]" htmlFor="crm-transfer-reason">سبب التحويل</label><input required id="crm-transfer-reason" value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 w-full rounded-lg border border-[var(--staff-line)] bg-black/15 px-3 py-2 text-sm text-[var(--staff-text)]" /><div className="mt-4 flex flex-wrap gap-2"><button type="submit" className="rounded-lg bg-[var(--staff-accent)] px-4 py-2 text-sm font-extrabold text-slate-950">{isOwner || isManager ? 'تأكيد التحويل' : 'إرسال طلب التحويل'}</button>{isManager && <button type="button" onClick={() => setReleaseOpen((value) => !value)} className="rounded-lg border border-rose-400/50 px-4 py-2 text-sm font-bold text-rose-300">إعادة إلى المخزن</button>}</div></form>

    {releaseOpen && isManager && <form onSubmit={(event) => { event.preventDefault(); if (!releaseReason.trim()) return; onRelease(releaseReason); setReleaseOpen(false); setReleaseReason(''); }} className="rounded-2xl border border-rose-400/40 bg-[var(--staff-panel)] p-5 shadow-lg shadow-black/30"><h2 className="font-extrabold text-[var(--staff-text)]">إعادة العميل إلى المخزن</h2><p className="mt-1 text-sm text-[var(--staff-muted)]">يُرفَع الإسنادُ عن الموظّف الحالي ويُسجَّل السببُ في سجلّ التواصل.</p><label className="mt-4 block text-sm font-bold text-[var(--staff-text)]" htmlFor="crm-release-reason">سبب الإعادة</label><input id="crm-release-reason" required value={releaseReason} onChange={(event) => setReleaseReason(event.target.value)} className="mt-2 w-full rounded-lg border border-[var(--staff-line)] bg-black/15 px-3 py-2 text-sm text-[var(--staff-text)]" /><div className="mt-4 flex gap-2"><button type="submit" className="rounded-lg bg-rose-400 px-4 py-2 text-sm font-extrabold text-slate-950">تأكيد الإعادة</button><button type="button" onClick={() => setReleaseOpen(false)} className="rounded-lg border border-[var(--staff-line)] px-4 py-2 text-sm font-bold text-[var(--staff-text)]">إلغاء</button></div></form>}
  </section>;
};
