# Generated by Django 6.0.3 on 2026-08-16 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0074_purchaseorder_idx_po_tenant_status_and_more'),
        ('tenants', '0020_membership_ui_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('offer', 'عرض سعر الاستيراد'), ('deal', 'الصفقة'), ('deal_payments', 'دفعات الصفقة'), ('shipment', 'الشحنة الدولية'), ('freight', 'الشحن الدولي'), ('clearance', 'التخليص الجمركي'), ('local', 'النقل المحلي'), ('invoice', 'فاتورة الشراء الدولية')], max_length=16)),
                ('item_type', models.CharField(choices=[('document', 'مستند'), ('task', 'مهمّة')], default='document', max_length=16)),
                ('kind', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=True, help_text='يدخل مقام نسبة اكتمال المرحلة')),
                ('done', models.BooleanField(default=False, help_text='لبنود المهامّ وحدها — حالة المستند مشتقّة من مرفقه')),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='فارغ لبنود الكتالوج — النظام زرعها لا مستخدم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_import_file_items', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_file_items', to='logistics.logisticsdeal')),
                ('shipment', models.ForeignKey(blank=True, help_text='وثائق الشحن والتخليص ترسو على الشحنة وتظهر في ملف كل صفقة عليها', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_file_items', to='logistics.logisticsshipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_file_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'import_file_items',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportFileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_file_documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_import_file_documents', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='import_file.importfileitem')),
            ],
            options={
                'db_table': 'import_file_documents',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='importfileitem',
            index=models.Index(fields=['tenant', 'deal'], name='impfile_item_tenant_deal_idx'),
        ),
        migrations.AddIndex(
            model_name='importfileitem',
            index=models.Index(fields=['tenant', 'shipment'], name='impfile_item_tenant_ship_idx'),
        ),
        migrations.AddConstraint(
            model_name='importfileitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deal__isnull', False), ('shipment__isnull', True)), models.Q(('deal__isnull', True), ('shipment__isnull', False)), _connector='OR'), name='import_file_item_one_anchor'),
        ),
        migrations.AddIndex(
            model_name='importfiledocument',
            index=models.Index(fields=['tenant', 'item'], name='impfile_doc_tenant_item_idx'),
        ),
    ]
