# Generated by Django 5.1.15 on 2026-08-24 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0023_tenant_status_varchar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.AutoField(db_column='DocumentShareID', primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('sales_invoice', 'فاتورة بيع'), ('sales_quotation', 'عرض سعر')], db_column='DocType', max_length=20)),
                ('doc_id', models.PositiveIntegerField(db_column='DocID')),
                ('token', models.CharField(db_column='Token', db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_column='ExpiresAt')),
                ('revoked_at', models.DateTimeField(blank=True, db_column='RevokedAt', null=True)),
                ('view_count', models.PositiveIntegerField(db_column='ViewCount', default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, db_column='FirstViewedAt', null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, db_column='LastViewedAt', null=True)),
                ('decision', models.CharField(blank=True, choices=[('accepted', 'مقبول'), ('rejected', 'مرفوض')], db_column='Decision', default='', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, db_column='DecidedAt', null=True)),
                ('decided_ip', models.CharField(blank=True, db_column='DecidedIP', default='', max_length=64)),
                ('decided_name', models.CharField(blank=True, db_column='DecidedName', default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='tenants.tenant')),
            ],
            options={
                'db_table': 'document_shares',
                'managed': True,
                'indexes': [models.Index(fields=['tenant', 'doc_type', 'doc_id'], name='docshare_doc_idx'), models.Index(fields=['tenant', 'created_at'], name='docshare_tenant_ts_idx')],
            },
        ),
    ]
