# Generated by Django 5.1.15 on 2026-09-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docshare', '0003_add_purchase_rfq_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentshare',
            name='is_public',
            field=models.BooleanField(db_column='IsPublic', default=False),
        ),
    ]
