# Generated by Django 6.0.3 on 2026-08-10 14:29

import device_registry.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=32, validators=[device_registry.models.validate_phone])),
                ('model_name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=15, validators=[device_registry.models.validate_imei])),
                ('technical_notes', models.TextField(blank=True, default='')),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('registered', 'مسجَّل'), ('in_check', 'في الفحص'), ('delivered', 'تم التسليم')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_sensitive_devices', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_sensitive_devices', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_devices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sensitive_devices',
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'تسجيل'), ('update', 'تعديل'), ('status', 'تغيير الحالة'), ('delete', 'حذف'), ('restore', 'استرجاع'), ('view', 'عرض'), ('search', 'بحث')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_audit_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_audit_logs', to='tenants.tenant')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='device_registry.sensitivedevice')),
            ],
            options={
                'db_table': 'device_audit_logs',
            },
        ),
        migrations.AddIndex(
            model_name='sensitivedevice',
            index=models.Index(fields=['tenant', 'imei'], name='sens_dev_tenant_imei_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivedevice',
            index=models.Index(fields=['tenant', 'serial_number'], name='sens_dev_tenant_sn_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitivedevice',
            index=models.Index(fields=['tenant', '-created_at'], name='sens_dev_tenant_new_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceauditlog',
            index=models.Index(fields=['tenant', '-created_at'], name='dev_audit_tenant_new_idx'),
        ),
    ]
