# Generated by Django 6.0.3 on 2026-08-12 13:20

import device_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivedevice',
            name='imei',
            field=models.CharField(blank=True, default='', max_length=15, validators=[device_registry.models.validate_imei]),
        ),
    ]
