# Generated by Django 5.1.15 on 2026-09-08 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0033_grant_store_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOpsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_full', models.PositiveIntegerField(default=10, verbose_name='نقاط القبول الكامل')),
                ('points_partial', models.PositiveIntegerField(default=5, verbose_name='نقاط القبول الجزئي')),
                ('points_attendance', models.PositiveIntegerField(default=1, verbose_name='نقاط الحضور')),
                ('attendance_daily_cap', models.PositiveIntegerField(default=5, verbose_name='سقف نقاط الحضور يومياً')),
                ('leaderboard_highlight_count', models.PositiveIntegerField(default=5, verbose_name='عدد المُبرَزين في لوحة الشرف')),
                ('rejected_retention_months', models.PositiveIntegerField(default=12, verbose_name='أشهر الاحتفاظ بالطلبات المرفوضة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'إعدادات متابعة الموظفين',
                'verbose_name_plural': 'إعدادات متابعة الموظفين',
            },
        ),
    ]
