# Generated by Django 5.1.15 on 2026-09-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_ops', '0001_initial'),
        ('hr', '0010_migrate_tokens_to_user_devices'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeopssettings',
            name='invitation_expiry_days',
            field=models.PositiveIntegerField(default=7, verbose_name='أجل رابط الدعوة بالأيام'),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_profile', to='hr.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ops_reports', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_profiles', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ملحق موظف متابعة الموظفين',
                'verbose_name_plural': 'ملاحق موظفي متابعة الموظفين',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبولة'), ('cancelled', 'ملغاة'), ('expired', 'منتهية الصلاحية')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_invitations', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_invitations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'دعوة موظف',
                'verbose_name_plural': 'دعوات الموظفين',
                'indexes': [models.Index(fields=['tenant', 'status'], name='employee_op_tenant__ee052e_idx')],
            },
        ),
    ]
