# Generated by Django 5.1.15 on 2026-09-08 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_ops', '0002_employeeopssettings_invitation_expiry_days_and_more'),
        ('hr', '0010_migrate_tokens_to_user_devices'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المهمة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('LOW', 'منخفضة'), ('MEDIUM', 'متوسطة'), ('HIGH', 'مرتفعة'), ('URGENT', 'عاجلة')], default='MEDIUM', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('NEW', 'جديدة'), ('ACCEPTED', 'مقبولة'), ('IN_PROGRESS', 'قيد التنفيذ'), ('WAITING_FOR_REVIEW', 'بانتظار المراجعة'), ('COMPLETED', 'مكتملة'), ('REJECTED', 'مرفوضة')], default='NEW', max_length=25, verbose_name='الحالة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='التصنيف')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='الوسوم')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='السعر المستهدف')),
                ('allowed_sites', models.JSONField(blank=True, default=list, verbose_name='المواقع المسموحة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('source_path', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='مسار المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_tasks', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'مهام متابعة الموظفين',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'لم تبدأ'), ('in_progress', 'قيد التنفيذ'), ('submitted', 'تم التسليم'), ('completed', 'مكتملة'), ('rejected', 'مرفوضة')], default='not_started', max_length=20, verbose_name='حالة الإسناد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('work_started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء جلسة العمل')),
                ('total_work_seconds', models.PositiveIntegerField(default=0, verbose_name='إجمالي ثواني العمل')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_assignments', to='hr.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employee_ops.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_task_assignments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'إسناد مهمة',
                'verbose_name_plural': 'إسنادات المهام',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='', verbose_name='نص التسليم')),
                ('decision', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved_full', 'قبول كامل'), ('approved_partial', 'قبول جزئي'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='قرار المراجعة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('reviewer_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات المراجع')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('source_path', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='مسار المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_submissions', to='hr.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='employee_ops.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_submissions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'تسليم مهمة',
                'verbose_name_plural': 'تسليمات المهام',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='رابط المرفق')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم المرفق')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='employee_ops.tasksubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_submission_attachments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'مرفق تسليم مهمة',
                'verbose_name_plural': 'مرفقات تسليمات المهام',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_link', models.TextField(blank=True, default='', verbose_name='رابط المنتج')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='سعر المنتج')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('attachment_url', models.TextField(blank=True, default='', verbose_name='رابط المرفق')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم المرفق')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='روابط الصور')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employee_ops.tasksubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_submission_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'بند تسليم مهمة',
                'verbose_name_plural': 'بنود تسليمات المهام',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'status'], name='employee_op_tenant__289c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'due_date'], name='employee_op_tenant__b0345e_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_path'), name='employee_ops_task_source_unique'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='employee_op_tenant__0a8432_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.UniqueConstraint(fields=('task', 'employee'), name='employee_ops_task_employee_unique'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['tenant', 'decision'], name='employee_op_tenant__da8a26_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubmission',
            index=models.Index(fields=['tenant', 'employee'], name='employee_op_tenant__0650cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_path'), name='employee_ops_submission_source_unique'),
        ),
    ]
