# Generated by Django 5.1.15 on 2026-09-08 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_ops', '0003_tasks_and_submissions'),
        ('hr', '0010_migrate_tokens_to_user_devices'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('source', models.CharField(choices=[('task_full', 'مهمة كاملة'), ('task_partial', 'مهمة جزئية'), ('attendance', 'حضور'), ('manual', 'يدوي'), ('reversal', 'إلغاء')], max_length=20, verbose_name='المصدر')),
                ('awarded_on', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('reason', models.TextField(blank=True, default='', verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('source_path', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='مسار المصدر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_points', to='hr.employee')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='employee_ops.pointentry', verbose_name='القيد المُلغى')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_entries', to='employee_ops.tasksubmission', verbose_name='التسليم المرتبط')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_points', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'قيد نقاط',
                'verbose_name_plural': 'قيود النقاط',
                'indexes': [models.Index(fields=['tenant', 'awarded_on', 'employee'], name='employee_op_tenant__57d53a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source_path'), name='employee_ops_point_source_unique')],
            },
        ),
    ]
