# Generated by Django 5.1.15 on 2026-09-08 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_ops', '0004_point_entry'),
        ('hr', '0010_migrate_tokens_to_user_devices'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نص الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('source_path', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='مسار المصدر')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_notes', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_notes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'ملاحظة على موظف',
                'verbose_name_plural': 'ملاحظات الموظفين',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'employee', '-created_at'], name='employee_op_tenant__7fc89e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source_path'), name='employee_ops_note_source_unique')],
            },
        ),
    ]
