# Generated by Django 5.1.15 on 2026-09-09 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_ops', '0005_employee_notes'),
        ('hr', '0010_migrate_tokens_to_user_devices'),
        ('tenants', '0034_field_staff_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوظيفة')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('requirements', models.TextField(blank=True, default='', verbose_name='المتطلبات')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='المكان')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد'), ('temporary', 'مؤقت')], default='', max_length=20, verbose_name='نوع الدوام')),
                ('salary_range', models.CharField(blank=True, default='', max_length=120, verbose_name='نطاق الراتب')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='مفتاح الرابط العام')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوحة للتقديم')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الرابط')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_jobs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'وظيفة',
                'verbose_name_plural': 'الوظائف',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المتقدم')),
                ('phone', models.CharField(max_length=40, verbose_name='رقم التواصل')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد')),
                ('about', models.TextField(blank=True, default='', verbose_name='نبذة')),
                ('cv_url', models.URLField(blank=True, default='', max_length=500, verbose_name='رابط السيرة')),
                ('cv_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم ملف السيرة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('interview', 'للمقابلة'), ('hired', 'موظَّف'), ('rejected', 'مرفوض')], default='new', max_length=20, verbose_name='الحالة')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='التقييم')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات المدير')),
                ('reference_code', models.CharField(max_length=32, verbose_name='رقم المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hired_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.employee', verbose_name='سجل الموظف')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_ops_applicants', to='tenants.tenant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='employee_ops.jobposting')),
            ],
            options={
                'verbose_name': 'متقدم على وظيفة',
                'verbose_name_plural': 'المتقدمون',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['tenant', 'is_open', '-created_at'], name='employee_op_tenant__594364_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicant',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='employee_op_tenant__5b2247_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicant',
            index=models.Index(fields=['tenant', 'job', '-created_at'], name='employee_op_tenant__4828ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplicant',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference_code'), name='employee_ops_applicant_reference_unique'),
        ),
    ]
