# Generated by Django 6.0.1 on 2026-02-04 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='AccountID', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense')], db_column='Type', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'chartofaccounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountingAuditLog',
            fields=[
                ('id', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('POST', 'Post')], db_column='Action', max_length=20)),
                ('model_name', models.CharField(db_column='ModelName', max_length=100)),
                ('object_id', models.IntegerField(db_column='ObjectID')),
                ('change_details', models.TextField(db_column='ChangeDetails')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='Timestamp')),
            ],
            options={
                'db_table': 'accounting_audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.AutoField(db_column='PeriodID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='PeriodName', max_length=100)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(db_column='EndDate')),
                ('status', models.CharField(db_column='Status', default='Open', max_length=20)),
            ],
            options={
                'db_table': 'fiscal_periods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalHeader',
            fields=[
                ('id', models.AutoField(db_column='JournalID', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, db_column='TransactionDate', null=True)),
                ('reference_type', models.CharField(blank=True, db_column='ReferenceType', max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, db_column='ReferenceID', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
            ],
            options={
                'db_table': 'journal_headers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.AutoField(db_column='JLineID', primary_key=True, serialize=False)),
                ('debit', models.DecimalField(db_column='Debit', decimal_places=2, default=0.0, max_digits=18)),
                ('credit', models.DecimalField(db_column='Credit', decimal_places=2, default=0.0, max_digits=18)),
                ('project_id', models.IntegerField(blank=True, db_column='ProjectID', null=True)),
            ],
            options={
                'db_table': 'journal_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(db_column='ChequeID', primary_key=True, serialize=False)),
                ('cheque_number', models.CharField(db_column='ChequeNumber', max_length=50)),
                ('bank_name', models.CharField(blank=True, db_column='BankName', max_length=100, null=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('due_date', models.DateField(db_column='DueDate')),
                ('issue_date', models.DateField(blank=True, db_column='IssueDate', null=True)),
                ('payee_name', models.CharField(blank=True, db_column='PayeeName', max_length=150, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Under_Collection', 'Under Collection'), ('Collected', 'Collected'), ('Bounced', 'Bounced'), ('Returned', 'Returned')], db_column='Status', default='Draft', max_length=50)),
                ('direction', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], db_column='Direction', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_by', models.ForeignKey(db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('partner', models.ForeignKey(blank=True, db_column='PartnerID', null=True, on_delete=django.db.models.deletion.RESTRICT, to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'cheques',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(db_column='CostCenterID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'cost_centers',
                'managed': True,
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
