# Generated by Django 6.0.1 on 2026-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='accountingauditlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='journalheader',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='journalline',
            options={'managed': True},
        ),
    ]
