# Generated by Django 6.0.1 on 2026-03-26 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_account_options_and_more'),
        ('partners', '0002_alter_partner_options_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='ParentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='accountingauditlog',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='accountingauditlog',
            name='user',
            field=models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(db_column='AccountID', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='CostCenterID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal',
            field=models.ForeignKey(db_column='JournalID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalheader'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='PartnerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='amount',
            field=models.DecimalField(db_column='Amount', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='direction',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], db_column='Direction', default='Incoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='due_date',
            field=models.DateField(blank=True, db_column='DueDate', null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'code')},
        ),
    ]
