# Generated by Django 6.0.3 on 2026-04-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_journalline_description'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalperiod',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='is_closed',
            field=models.BooleanField(db_column='IsClosed', default=False),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='status',
            field=models.CharField(
                choices=[('Open', 'Open'), ('Closed', 'Closed')],
                db_column='Status', default='Open', max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='CurrencyID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_headers', to='tenants.currency'),
        ),
        migrations.AddField(
            model_name='journalheader',
            name='exchange_rate',
            field=models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=18),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(db_column='ExchangeRateID', primary_key=True, serialize=False)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=6, max_digits=18)),
                ('effective_date', models.DateField(db_column='EffectiveDate')),
                ('from_currency', models.ForeignKey(db_column='FromCurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='tenants.currency')),
                ('tenant', models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('to_currency', models.ForeignKey(db_column='ToCurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='tenants.currency')),
            ],
            options={
                'db_table': 'exchange_rates',
                'managed': True,
                'unique_together': {('tenant', 'from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(db_column='TaxRateID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('code', models.CharField(db_column='Code', max_length=20)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('tax_account', models.ForeignKey(db_column='TaxAccountID', on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='accounting.account')),
                ('tenant', models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'tax_rates',
                'managed': True,
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
