# Generated by Django 6.0.3 on 2026-04-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_multi_currency_tax_fiscal'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalperiod',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
