# Generated by Django 6.0.3 on 2026-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_purchase_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='base_credit',
            field=models.DecimalField(db_column='BaseCredit', decimal_places=2, default=0.0, help_text='مبلغ الدائن بالعملة الأساسية = credit × سعر الصرف', max_digits=18),
        ),
        migrations.AddField(
            model_name='journalline',
            name='base_debit',
            field=models.DecimalField(db_column='BaseDebit', decimal_places=2, default=0.0, help_text='مبلغ المدين بالعملة الأساسية = debit × سعر الصرف', max_digits=18),
        ),
    ]
