# Generated by Django 6.0.3 on 2026-05-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_seed_import_accounts_and_fix_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(db_column='AccountID', default=1, on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
    ]
