# Generated by Django 6.0.3 on 2026-05-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_change_journal_line_account_to_protect'),
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        # m3-03 (uq_journal_source_key) removed: MySQL lacks partial-unique
        # support (silently unenforced) and the key is not actually unique
        # in this domain. Idempotency stays application-enforced.
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='journal_line_debit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='journal_line_credit_non_negative'),
        ),
    ]
