# Generated by Django 6.0.3 on 2026-05-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_add_journal_constraints'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='accountingauditlog',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cashboxledgeraccount',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='fiscalperiod',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='journalheader',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='journal',
            field=models.ForeignKey(db_column='JournalID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalheader'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='tenant',
            field=models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
