# Generated by Django 6.0.3 on 2026-05-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_account_tenant_alter_accountingauditlog_tenant_and_more'),
        ('sales', '0007_add_aseel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='customer_payment',
            field=models.ForeignKey(blank=True, db_column='CustomerPaymentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='sales.customerpayment'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, db_column='SalesInvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='sales.salesinvoice'),
        ),
    ]
