# Generated by Django 6.0.3 on 2026-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_cheque_invoice_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nature',
            field=models.CharField(blank=True, choices=[('debit_only', 'مدين فقط'), ('credit_only', 'دائن فقط'), ('both', 'مدين/دائن')], db_column='Nature', help_text='طبيعة الحساب: مدين فقط / دائن فقط / مدين ودائن. تُفرَض على القيود.', max_length=20, null=True),
        ),
    ]
