# Generated by Django 6.0.3 on 2026-05-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_n8_t6_account_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_cost_center',
            field=models.ForeignKey(blank=True, db_column='DefaultCostCenterID', help_text='مركز التكلفة الافتراضي للحساب — يُملأ تلقائياً في القيود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_with_default', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='ملاحظات الحساب — تُعرض عند F4 drill-down', null=True),
        ),
    ]
