# Generated by Django 6.0.3 on 2026-05-23 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_n8_t7_account_default_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeMovement',
            fields=[
                ('id', models.AutoField(db_column='ChequeMovementID', primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdraw', 'صرف'), ('bounce', 'رفض'), ('return_to_customer', 'إرجاع للعميل'), ('settle', 'تسوية')], db_column='MovementType', max_length=30)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('cheque', models.ForeignKey(db_column='ChequeID', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='accounting.cheque')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque Movement',
                'verbose_name_plural': 'Cheque Movements',
                'db_table': 'cheque_movements',
                'managed': True,
            },
        ),
    ]
