# Generated by Django 6.0.3 — P-H-1: add purchase_invoice FK to Cheque
# Mirrors sales_invoice FK added in 0017_add_cheque_invoice_links.py

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0040_pf4_backfill_deal_status_cache'),
        ('accounting', '0020_n8_t14_cheque_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, db_column='PurchaseInvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='logistics.purchaseinvoice'),
        ),
    ]
