# Generated by Django 6.0.3 on 2026-06-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_cheque_pi_link'),
        ('tenants', '0007_branch_alter_tenantbook_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalheader',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='BranchID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_headers', to='tenants.branch'),
        ),
    ]
