# Generated by Django 6.0.3 on 2026-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_journalheader_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Under_Collection', 'Under Collection'), ('Collected', 'Collected'), ('Bounced', 'Bounced'), ('Returned', 'Returned'), ('Settled', 'Settled')], db_column='Status', default='Draft', max_length=50),
        ),
    ]
