# Generated by Django 6.0.1 on 2026-06-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_cheque_status'),
        ('tenants', '0009_operational_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidedJournal',
            fields=[
                ('id', models.AutoField(db_column='VoidedJournalID', primary_key=True, serialize=False)),
                ('original_journal_id', models.IntegerField(db_column='OriginalJournalID', help_text='رقم القيد (JournalID) الأصلي المحجوز لإعادة الاستخدام عند إعادة الترحيل.')),
                ('reference_type', models.CharField(db_column='ReferenceType', max_length=50)),
                ('reference_id', models.IntegerField(db_column='ReferenceID')),
                ('transaction_date', models.DateField(blank=True, db_column='TransactionDate', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('voided_at', models.DateTimeField(auto_now_add=True, db_column='VoidedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, db_column='VoidedByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voided_journals',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'reference_type', 'reference_id'), name='uniq_voided_journal_per_document')],
            },
        ),
    ]
