# Generated by Django 6.0.3 on 2026-07-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_cashboxfxlot'),
        ('partners', '0007_customer_notes'),
        ('tenants', '0011_tenantsettings_appearance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['tenant', 'transaction_date', 'id'], name='idx_jh_tenant_date_id'),
        ),
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['tenant', 'reference_type', 'reference_id'], name='idx_jh_tenant_ref'),
        ),
        migrations.AddIndex(
            model_name='journalheader',
            index=models.Index(fields=['tenant', 'is_posted'], name='idx_jh_tenant_posted'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['tenant', 'account'], name='idx_jl_tenant_account'),
        ),
    ]
