# Generated by Django 6.0.3 on 2026-07-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_journal_indexes'),
        ('sales', '0025_salessettings_dormant_customer_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='supplier_payment',
            field=models.ForeignKey(blank=True, db_column='SupplierPaymentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='sales.supplierpayment'),
        ),
    ]
