# Generated by Django 6.0.3 on 2026-08-05 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_cheque_bank_snapshot'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(db_column='BankID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('code', models.CharField(blank=True, db_column='Code', help_text='رمز البنك المحلي (اختياري)', max_length=30, null=True)),
                ('swift_code', models.CharField(blank=True, db_column='SwiftCode', max_length=20, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=80, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'banks',
                'ordering': ['name'],
                'managed': True,
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='bank',
            field=models.ForeignKey(blank=True, db_column='BankID', help_text='البنك المسحوب عليه الشيك', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='accounting.bank'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(db_column='BankAccountID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', help_text='تسمية الحساب كما تظهر في الشجرة والتقارير', max_length=150)),
                ('account_number', models.CharField(blank=True, db_column='AccountNumber', max_length=50, null=True)),
                ('iban', models.CharField(blank=True, db_column='IBAN', max_length=50, null=True)),
                ('is_default', models.BooleanField(db_column='IsDefault', default=False)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('account', models.OneToOneField(db_column='AccountID', on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounting.account')),
                ('bank', models.ForeignKey(db_column='BankID', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.bank')),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='tenants.currency')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'company_bank_accounts',
                'ordering': ['bank__name', 'name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='deposit_bank_account',
            field=models.ForeignKey(blank=True, db_column='DepositBankAccountID', help_text='حساب الشركة البنكي الذي أُودع/صُرف منه الشيك', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='accounting.bankaccount'),
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(db_column='BankBranchID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('branch_code', models.CharField(blank=True, db_column='BranchCode', max_length=30, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('bank', models.ForeignKey(db_column='BankID', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounting.bank')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'bank_branches',
                'ordering': ['name'],
                'managed': True,
                'unique_together': {('bank', 'name')},
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='BankBranchID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.bankbranch'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bank_branch_ref',
            field=models.ForeignKey(blank=True, db_column='BankBranchID', help_text='فرع البنك المسحوب عليه', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='accounting.bankbranch'),
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.AutoField(db_column='BankReconciliationID', primary_key=True, serialize=False)),
                ('statement_date', models.DateField(db_column='StatementDate')),
                ('statement_balance', models.DecimalField(db_column='StatementBalance', decimal_places=2, default=0.0, max_digits=18)),
                ('status', models.CharField(choices=[('Open', 'مفتوحة'), ('Closed', 'مُقفلة')], db_column='Status', default='Open', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('closed_at', models.DateTimeField(blank=True, db_column='ClosedAt', null=True)),
                ('bank_account', models.ForeignKey(db_column='BankAccountID', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'bank_reconciliations',
                'ordering': ['-statement_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationLine',
            fields=[
                ('id', models.AutoField(db_column='BankReconciliationLineID', primary_key=True, serialize=False)),
                ('cleared_at', models.DateTimeField(auto_now_add=True, db_column='ClearedAt')),
                ('journal_line', models.OneToOneField(db_column='JLineID', on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliation_line', to='accounting.journalline')),
                ('reconciliation', models.ForeignKey(db_column='BankReconciliationID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankreconciliation')),
            ],
            options={
                'db_table': 'bank_reconciliation_lines',
                'managed': True,
            },
        ),
    ]
