# Generated by Django 6.0.3 on 2026-08-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_banks_and_reconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequemovement',
            name='movement_type',
            field=models.CharField(choices=[('deposit', 'إيداع'), ('withdraw', 'صرف'), ('collect', 'تحصيل'), ('bounce', 'رفض'), ('return_to_customer', 'إرجاع للعميل'), ('settle', 'تسوية')], db_column='MovementType', max_length=30),
        ),
    ]
