# Generated by Django 5.1.15 on 2026-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0032_cheques_align_nullable_columns"),
        ("partners", "0013_general_note_targets"),
        ("tenants", "0018_alter_rolepermission_role_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["tenant", "partner"], name="idx_jl_tenant_partner"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["tenant", "journal"], name="idx_jl_tenant_journal"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["tenant", "account", "journal"], name="idx_jl_tenant_acc_jrn"
            ),
        ),
    ]
