# Generated by Django 5.1.15 on 2026-08-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_cheque_cycle_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequemovement',
            name='movement_type',
            field=models.CharField(choices=[('receive', 'استلام'), ('issue', 'تسليم شيك صادر'), ('revert', 'إلغاء ترحيل السند'), ('deposit', 'إيداع'), ('redeposit', 'إعادة إيداع'), ('withdraw', 'صرف'), ('collect', 'تحصيل'), ('endorse', 'تظهير'), ('bounce', 'رفض'), ('return_to_customer', 'إرجاع للعميل'), ('cancel', 'إلغاء'), ('settle', 'تسوية')], db_column='MovementType', max_length=30),
        ),
    ]
