# Generated by Django 5.1.15 on 2026-08-27 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_cheque_status_varchar'),
        ('tenants', '0024_hr_settings_and_ess_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxledgeraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt', null=True),
        ),
        migrations.AddField(
            model_name='cashboxledgeraccount',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
        migrations.AddField(
            model_name='cashboxledgeraccount',
            name='is_default',
            field=models.BooleanField(db_column='IsDefault', default=False),
        ),
        migrations.AddField(
            model_name='cashboxledgeraccount',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', null=True),
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.AutoField(db_column='CashCountID', primary_key=True, serialize=False)),
                ('count_date', models.DateField(db_column='CountDate')),
                ('book_balance', models.DecimalField(db_column='BookBalance', decimal_places=2, default=0, help_text='الرصيد الدفتري لحظة الجرد', max_digits=18)),
                ('counted_total', models.DecimalField(db_column='CountedTotal', decimal_places=2, default=0, max_digits=18)),
                ('difference', models.DecimalField(db_column='Difference', decimal_places=2, default=0, help_text='المعدود − الدفتري: موجب زيادة، سالب عجز', max_digits=18)),
                ('denominations', models.JSONField(blank=True, db_column='Denominations', null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحَّل')], db_column='Status', default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('cash_box', models.ForeignKey(db_column='CashBoxLedgerID', on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='accounting.cashboxledgeraccount')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_counts', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_counts', to='accounting.journalheader')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'cash_counts',
                'ordering': ['-count_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.AutoField(db_column='CashTransferID', primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='Number', default=0)),
                ('transfer_date', models.DateField(db_column='TransferDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, help_text='المبلغ بعملة الطرف المُرسِل', max_digits=18)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=6, default=1, help_text='سعر الصرف حين تختلف العملتان', max_digits=18)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_bank_account', models.ForeignKey(blank=True, db_column='FromBankAccountID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.bankaccount')),
                ('from_cash_box', models.ForeignKey(blank=True, db_column='FromCashBoxID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.cashboxledgeraccount')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transfers', to='accounting.journalheader')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('to_bank_account', models.ForeignKey(blank=True, db_column='ToBankAccountID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.bankaccount')),
                ('to_cash_box', models.ForeignKey(blank=True, db_column='ToCashBoxID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.cashboxledgeraccount')),
            ],
            options={
                'db_table': 'cash_transfers',
                'ordering': ['-transfer_date', '-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CashBoxUserDefault',
            fields=[
                ('id', models.AutoField(db_column='CashBoxUserDefaultID', primary_key=True, serialize=False)),
                ('cash_box', models.ForeignKey(db_column='CashBoxLedgerID', on_delete=django.db.models.deletion.CASCADE, related_name='user_defaults', to='accounting.cashboxledgeraccount')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='cash_box_defaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_box_user_defaults',
                'managed': True,
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
