# Generated by Django 5.1.15 on 2026-09-03 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_expensevoucher'),
        ('partners', '0014_partner_idx_partner_tenant_type'),
        ('tenants', '0029_alter_tenantbook_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensevoucher',
            name='kind',
            field=models.CharField(choices=[('normal', 'عاديّ'), ('return', 'مرتجع')], db_column='Kind', default='normal', help_text='عاديّ أو مرتجع — يقلب اتجاه القيد ويُبقي المبلغ موجباً (issue #80).', max_length=10),
        ),
        migrations.CreateModel(
            name='RevenueVoucher',
            fields=[
                ('id', models.AutoField(db_column='RevenueVoucherID', primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='Number', default=0)),
                ('date', models.DateField(db_column='Date')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, default=0, help_text='ضريبة مخرجات (2104) — جزء من amount لا إضافة عليه', max_digits=18)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1, max_digits=18)),
                ('payment_method', models.CharField(choices=[('cash', 'صندوق/بنك'), ('cheque', 'شيك'), ('on_account', 'على الحساب')], db_column='PaymentMethod', default='cash', max_length=10)),
                ('kind', models.CharField(choices=[('normal', 'عاديّ'), ('return', 'مرتجع')], db_column='Kind', default='normal', help_text='عاديّ أو مرتجع — يقلب اتجاه القيد ويُبقي المبلغ موجباً (issue #80).', max_length=10)),
                ('payer_name', models.CharField(blank=True, db_column='PayerName', default='', max_length=200)),
                ('description', models.CharField(blank=True, db_column='Description', default='', max_length=500)),
                ('attachment_url', models.URLField(blank=True, db_column='AttachmentUrl', default='', max_length=500)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('cash_or_bank_account', models.ForeignKey(blank=True, db_column='CashAccountID', help_text='الصندوق/البنك — يُملأ فقط عند payment_method=cash', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_vouchers_cash', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_vouchers', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_vouchers', to='accounting.journalheader')),
                ('payer_partner', models.ForeignKey(blank=True, db_column='PayerPartnerID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_vouchers', to='partners.partner')),
                ('revenue_account', models.ForeignKey(db_column='RevenueAccountID', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_vouchers', to='accounting.account')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'revenue_vouchers',
                'ordering': ['-date', '-id'],
                'managed': True,
                'indexes': [models.Index(fields=['tenant', '-date', '-id'], name='idx_revvouch_tenant_date')],
            },
        ),
    ]
