# Generated by Django 5.1.15 on 2026-09-03 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_expensevoucher_kind_revenuevoucher'),
        ('partners', '0014_partner_idx_partner_tenant_type'),
        ('tenants', '0029_alter_tenantbook_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAccountCodingRule',
            fields=[
                ('id', models.AutoField(db_column='PartnerAccountCodingRuleID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.PROTECT, related_name='partner_coding_rules', to='accounting.account')),
                ('partner', models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.CASCADE, related_name='accounting_coding_rules', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'partner_account_coding_rules',
                'managed': True,
                'unique_together': {('tenant', 'partner')},
            },
        ),
    ]
