# Generated by Django 5.1.15 on 2026-09-08 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_partneraccountcodingrule'),
        ('sales', '0043_customerpayment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequemovement',
            name='sales_return',
            field=models.ForeignKey(blank=True, db_column='SalesReturnID', help_text='مرتجع البيع الذي أعاد هذه الورقة تلقائياً عند ترحيله', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_returned_cheque_movements', to='sales.salesinvoice'),
        ),
    ]
