# Generated by Django 5.1.15 on 2026-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_chequemovement_sales_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalheader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt'),
        ),
    ]
