# Generated by Django 6.1.1 on 2026-10-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_journalline_amount_currency'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxfxlot',
            name='source',
            field=models.CharField(choices=[('capital', 'إيداع من رأس المال'), ('transfer_ils', 'تحويل من صندوق الشيقل'), ('opening', 'طبقة افتتاحية (جرد فعلي)')], db_column='Source', max_length=20),
        ),
        migrations.CreateModel(
            name='CashBoxFxConsumption',
            fields=[
                ('id', models.AutoField(db_column='CashBoxFxConsumptionID', primary_key=True, serialize=False)),
                ('fc', models.DecimalField(db_column='FC', decimal_places=4, help_text='المأخوذ من هذه الطبقة بالعملة الأجنبية', max_digits=18)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=6, help_text='سعر الطبقة لحظة الاستهلاك — لقطة', max_digits=18)),
                ('reference_type', models.CharField(db_column='ReferenceType', max_length=50)),
                ('reference_id', models.IntegerField(db_column='ReferenceID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('restored_at', models.DateTimeField(blank=True, db_column='RestoredAt', help_text='أُرجع إلى طبقته بفكّ ترحيل المستند', null=True)),
                ('lot', models.ForeignKey(db_column='CashBoxFxLotID', on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='accounting.cashboxfxlot')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'cash_box_fx_consumptions',
                'ordering': ['id'],
                'managed': True,
                'indexes': [models.Index(fields=['tenant', 'reference_type', 'reference_id'], name='idx_cbfc_tenant_ref')],
            },
        ),
    ]
