# Generated by Django 6.0.3 on 2026-04-17 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0007_purchase_invoices'),
        ('inventory', '0001_stock_movements_and_product_qty'),
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.AutoField(db_column='CustomerPaymentID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=18)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('cash_or_bank_account', models.ForeignKey(db_column='DebitAccountID', help_text='الصندوق أو البنك (مدين)', on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments_debit', to='accounting.account')),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='accounting.journalheader')),
                ('partner', models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_customer_payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(db_column='SalesInvoiceID', primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_column='InvoiceNumber', max_length=50)),
                ('invoice_date', models.DateField(db_column='InvoiceDate')),
                ('due_date', models.DateField(blank=True, db_column='DueDate', null=True)),
                ('invoice_type', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], db_column='InvoiceType', default='credit', max_length=20)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّلة'), ('cancelled', 'ملغاة')], db_column='Status', default='draft', max_length=20)),
                ('subtotal_excl_tax', models.DecimalField(db_column='SubtotalExclTax', decimal_places=2, default=0, max_digits=18)),
                ('invoice_discount', models.DecimalField(db_column='InvoiceDiscount', decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(db_column='GrandTotal', decimal_places=2, default=0, max_digits=18)),
                ('amount_paid', models.DecimalField(db_column='AmountPaid', decimal_places=2, default=0, max_digits=18)),
                ('stock_on_post', models.BooleanField(db_column='StockOnPost', default=True, help_text='إذا عطّل: لا يُخصم المخزون عند الترحيل بل عند تسليم أمر الإخراج')),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('accounts_receivable_account', models.ForeignKey(blank=True, db_column='AccountsReceivableAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices_ar', to='accounting.account')),
                ('cash_or_bank_account', models.ForeignKey(blank=True, db_column='CashOrBankAccountID', help_text='حساب الصندوق أو البنك لفواتير النقدي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices_cash', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='partners.partner')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounting.journalheader')),
                ('revenue_account', models.ForeignKey(blank=True, db_column='RevenueAccountID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices_revenue', to='accounting.account')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_invoices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.AutoField(db_column='PaymentAllocationID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('payment', models.ForeignKey(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.customerpayment')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('invoice', models.ForeignKey(db_column='InvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='sales.salesinvoice')),
            ],
            options={
                'db_table': 'sales_module_payment_allocations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.AutoField(db_column='DeliveryOrderID', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], db_column='Status', default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('delivered_at', models.DateTimeField(blank=True, db_column='DeliveredAt', null=True)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('invoice', models.ForeignKey(db_column='InvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='sales.salesinvoice')),
            ],
            options={
                'db_table': 'sales_module_delivery_orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.AutoField(db_column='SalesInvoiceLineID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('line_discount', models.DecimalField(db_column='LineDiscount', decimal_places=2, default=0, max_digits=18)),
                ('line_total_excl_tax', models.DecimalField(db_column='LineTotalExclTax', decimal_places=2, default=0, max_digits=18)),
                ('line_tax_amount', models.DecimalField(db_column='LineTaxAmount', decimal_places=2, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(db_column='InvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='inventory.product')),
                ('tax_rate', models.ForeignKey(blank=True, db_column='TaxRateID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_lines', to='accounting.taxrate')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_invoice_lines',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'status', 'invoice_date'], name='sales_modul_TenantI_23fcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer'], name='sales_modul_Custome_3dc519_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice_number'), name='uniq_sales_invoice_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='uniq_payment_invoice_allocation'),
        ),
    ]
