# Generated by Django 6.0.3 on 2026-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='amount_in_invoice_currency',
            field=models.DecimalField(blank=True, db_column='AmountInInvoiceCurrency', decimal_places=2, help_text='المبلغ محوّلاً لعملة الفاتورة. إذا كانت عملة الدفعة = عملة الفاتورة يساوي amount.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='conversion_rate',
            field=models.DecimalField(blank=True, db_column='ConversionRate', decimal_places=6, help_text='سعر الصرف المستخدم لتحويل مبلغ الدفعة لعملة الفاتورة', max_digits=18, null=True),
        ),
    ]
