# Generated by Django 6.0.3 on 2026-04-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_seed_import_accounts_and_fix_vat'),
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('sales', '0003_sales_settings'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessettings',
            name='default_ar_account',
            field=models.ForeignKey(blank=True, db_column='DefaultArAccountID', help_text='حساب ذمم افتراضي للعملاء الآجلين', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_ar', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_cash_account',
            field=models.ForeignKey(blank=True, db_column='DefaultCashAccountID', help_text='حساب الصندوق الافتراضي للفواتير النقدية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_cash', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_cogs_account',
            field=models.ForeignKey(blank=True, db_column='DefaultCogsAccountID', help_text='حساب تكلفة مبيعات افتراضي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_cogs', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_currency',
            field=models.ForeignKey(blank=True, db_column='DefaultCurrencyID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sales_settings', to='tenants.currency'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_customer',
            field=models.ForeignKey(blank=True, db_column='DefaultCustomerID', help_text='العميل الافتراضي للفواتير (الزبون العام)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sales_settings', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_inventory_account',
            field=models.ForeignKey(blank=True, db_column='DefaultInventoryAccountID', help_text='حساب مخزون افتراضي (إن لم تُحدَّد فئة المنتج حساب مخزون)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_inventory', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_revenue_account_product',
            field=models.ForeignKey(blank=True, db_column='DefaultRevenueAccountProductID', help_text='حساب إيراد افتراضي لبيع البضائع (المنتجات)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_rev_product', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_revenue_account_service',
            field=models.ForeignKey(blank=True, db_column='DefaultRevenueAccountServiceID', help_text='حساب إيراد افتراضي للخدمات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_rev_service', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='default_vat_rate',
            field=models.ForeignKey(blank=True, db_column='DefaultVatRateID', help_text='نسبة ضريبة القيمة المضافة الافتراضية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_vat', to='accounting.taxrate'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='tenant',
            field=models.OneToOneField(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, related_name='sales_settings', to='tenants.tenant'),
        ),
    ]
