# Generated by Django 6.0.3 on 2026-05-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_account_tenant_alter_accountingauditlog_tenant_and_more'),
        ('sales', '0004_alter_salessettings_default_ar_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='vat_input_account',
            field=models.ForeignKey(blank=True, db_column='VatInputAccountID', help_text='حساب ضريبة المدخلات (VAT Input) المستخدم في فواتير الشراء — الربط الصريح يُغني عن البحث بالاسم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_vat_input', to='accounting.account'),
        ),
    ]
