# Generated by Django 6.0.3 on 2026-05-18 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_account_tenant_alter_accountingauditlog_tenant_and_more'),
        ('inventory', '0003_product_is_service'),
        ('partners', '0003_alter_partner_createdat_and_more'),
        ('sales', '0005_salessettings_vat_input_account'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.AutoField(db_column='SalesQuotationID', primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(db_column='QuotationNumber', max_length=50)),
                ('quotation_date', models.DateField(db_column='QuotationDate')),
                ('valid_until', models.DateField(blank=True, db_column='ValidUntil', null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'أُرسل'), ('accepted', 'مقبول'), ('converted', 'محوّل'), ('expired', 'منتهي الصلاحية'), ('rejected', 'مرفوض')], db_column='Status', default='draft', max_length=20)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=18)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(db_column='DiscountAmount', decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(db_column='GrandTotal', decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to='partners.partner')),
                ('invoice', models.ForeignKey(blank=True, db_column='InvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_backref', to='sales.salesinvoice')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_quotations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationLine',
            fields=[
                ('id', models.AutoField(db_column='SalesQuotationLineID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('line_discount', models.DecimalField(db_column='LineDiscount', decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(db_column='LineTotal', decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotation_lines', to='inventory.product')),
                ('quotation', models.ForeignKey(db_column='QuotationID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesquotation')),
                ('tax_rate', models.ForeignKey(blank=True, db_column='TaxRateID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotation_lines', to='accounting.taxrate')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_quotation_lines',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['tenant', 'status', 'quotation_date'], name='sales_modul_TenantI_7c9973_idx'),
        ),
        migrations.AddIndex(
            model_name='salesquotation',
            index=models.Index(fields=['customer'], name='sales_modul_Custome_91540b_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesquotation',
            constraint=models.UniqueConstraint(fields=('tenant', 'quotation_number'), name='uniq_sales_quotation_number_per_tenant'),
        ),
    ]
