# Generated by Django 6.0.3 on 2026-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='book_number',
            field=models.PositiveIntegerField(db_column='BookNumber', default=0, help_text='رقم الدفتر. 0 = يدوي. >0 = مسلسل لكل دفتر مستقل.'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='discount_percent',
            field=models.DecimalField(db_column='DiscountPercent', decimal_places=2, default=0, help_text='نسبة الخصم على مستوى الفاتورة (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='licensed_dealer_no',
            field=models.CharField(blank=True, db_column='LicensedDealerNo', default='', help_text='رقم المشتغل المرخص الخاص بالمورد أو العميل', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='prices_include_tax',
            field=models.BooleanField(db_column='PricesIncludeTax', default=False, help_text='إذا مفعّل: الأسعار المدخلة شاملة للضريبة (تجاوز إعدادات المبيعات)'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='second_date',
            field=models.DateField(blank=True, db_column='SecondDate', help_text='تاريخ ثاني لحركة الفواتير (حقل اختياري)', null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='settlement_invoice_no',
            field=models.CharField(blank=True, db_column='SettlementInvoiceNo', default='', help_text='رقم فاتورة المقاصة', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='catalog_no',
            field=models.CharField(blank=True, db_column='CatalogNo', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='expiry_date',
            field=models.DateField(blank=True, db_column='ExpiryDate', null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='extra_quantity',
            field=models.DecimalField(blank=True, db_column='ExtraQuantity', decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='line_tax_percent',
            field=models.DecimalField(blank=True, db_column='LineTaxPercent', decimal_places=2, help_text='نسبة ضريبة مخصصة للسطر (تجاوز النسبة الافتراضية)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='warehouse',
            field=models.CharField(blank=True, db_column='Warehouse', default='', max_length=100),
        ),
    ]
