# Generated by Django 6.0.3 on 2026-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_aseel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='financial_document_no',
            field=models.CharField(blank=True, db_column='FinancialDocumentNo', default='', help_text='رقم السند المالي المرفق بالفاتورة (إيصال قبض/صرف)', max_length=50),
        ),
    ]
