# Generated by Django 6.0.3 on 2026-05-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_cheque_invoice_links'),
        ('sales', '0008_add_financial_document_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='source_discount_amount_override',
            field=models.DecimalField(blank=True, db_column='SourceDiscountAmountOverride', decimal_places=2, help_text='مبلغ خصم مصدر — تجاوز على مستوى الفاتورة (null = احسب من النسبة أو افتراضي العميل)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='source_discount_percent_override',
            field=models.DecimalField(blank=True, db_column='SourceDiscountPercentOverride', decimal_places=2, help_text='نسبة خصم مصدر — تجاوز على مستوى الفاتورة (null = استخدم افتراضي العميل)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='default_source_discount_account',
            field=models.ForeignKey(blank=True, db_column='DefaultSourceDiscountAccountID', help_text='حساب خصم المصدر (Asset/Receivable). يستلم مبلغ الضريبة المحجوزة من العميل عند الترحيل.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_source_disc', to='accounting.account'),
        ),
    ]
