# Generated by Django 6.0.3 on 2026-05-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_cheque_invoice_links'),
        ('sales', '0009_source_discount_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='attached_cash_account',
            field=models.ForeignKey(blank=True, db_column='AttachedCashAccountID', help_text='حساب الصندوق/البنك الذي استلم المبلغ النقدي المرفق', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices_attached_cash', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='attached_cash_amount',
            field=models.DecimalField(db_column='AttachedCashAmount', decimal_places=2, default=0, help_text='مبلغ نقدي مرفق مع الفاتورة (يُحسم من ذمم العميل ويُرحَّل ضمن نفس قيد الفاتورة)', max_digits=18),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='default_cheques_under_collection_account',
            field=models.ForeignKey(blank=True, db_column='DefaultChequesUnderCollectionAccountID', help_text='حساب شيكات برسم التحصيل (Asset). يستقبل الشيكات الواردة المرفقة بفواتير المبيعات.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_cheques_uc', to='accounting.account'),
        ),
    ]
