# Generated by Django 6.0.3 on 2026-05-20 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_cheque_invoice_links'),
        ('partners', '0004_add_source_discount'),
        ('sales', '0010_invoice_payment_voucher'),
        ('tenants', '0002_alter_currency_options_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDebitNote',
            fields=[
                ('id', models.AutoField(db_column='CreditDebitNoteID', primary_key=True, serialize=False)),
                ('note_number', models.CharField(db_column='NoteNumber', max_length=50)),
                ('note_date', models.DateField(db_column='NoteDate')),
                ('note_type', models.CharField(choices=[('credit', 'دائن'), ('debit', 'مدين')], db_column='NoteType', max_length=10)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('reason', models.TextField(blank=True, db_column='Reason', default='')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغي')], db_column='Status', default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.PROTECT, related_name='credit_debit_notes', to='partners.partner')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalheader')),
                ('related_invoice', models.ForeignKey(blank=True, db_column='RelatedInvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_debit_notes', to='sales.salesinvoice')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_credit_debit_notes',
                'managed': True,
                'unique_together': {('tenant', 'note_number')},
            },
        ),
    ]
