# Generated by Django 6.0.3 on 2026-05-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_creditdebitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_kind',
            field=models.CharField(choices=[('sale', 'فاتورة بيع'), ('sale_return', 'مرجع بيع'), ('purchase', 'فاتورة شراء'), ('purchase_return', 'مرجع شراء')], db_column='InvoiceKind', default='sale', help_text='نوع الفاتورة: بيع / مرجع بيع / شراء / مرجع شراء', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, db_column='OriginalInvoiceID', help_text='الفاتورة الأصلية (للمراجيع) — يربط مرجع البيع/الشراء بأصلها', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_invoices', to='sales.salesinvoice'),
        ),
    ]
