# Generated by Django 6.0.3 on 2026-05-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_n8_t7_account_default_cost_center'),
        ('partners', '0005_n8_t8_partner_enrichment'),
        ('sales', '0012_n8_t11_invoice_kind'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.AutoField(db_column='SupplierPaymentID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=18)),
                ('is_posted', models.BooleanField(db_column='IsPosted', default=False)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('cash_or_bank_account', models.ForeignKey(db_column='CashAccountID', help_text='الصندوق أو البنك (دائن)', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_cash', to='accounting.account')),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('journal', models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='accounting.journalheader')),
                ('partner', models.ForeignKey(db_column='PartnerID', on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='partners.partner')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_supplier_payments',
                'managed': True,
            },
        ),
    ]
