# Generated by Django 6.0.3 on 2026-05-23 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_n8_t12_supplier_payment'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VatStatement',
            fields=[
                ('id', models.AutoField(db_column='VatStatementID', primary_key=True, serialize=False)),
                ('statement_number', models.CharField(db_column='StatementNumber', max_length=50)),
                ('period_from', models.DateField(db_column='PeriodFrom')),
                ('period_to', models.DateField(db_column='PeriodTo')),
                ('total_sales_vat', models.DecimalField(db_column='TotalSalesVat', decimal_places=2, default=0, max_digits=18)),
                ('total_purchase_vat', models.DecimalField(db_column='TotalPurchaseVat', decimal_places=2, default=0, max_digits=18)),
                ('net_vat', models.DecimalField(db_column='NetVat', decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('final', 'نهائي')], db_column='Status', default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_vat_statements',
                'managed': True,
                'unique_together': {('tenant', 'statement_number')},
            },
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='vat_statement',
            field=models.ForeignKey(blank=True, db_column='VatStatementID', help_text='كشف ضريبة القيمة المضافة الدوري', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.vatstatement'),
        ),
    ]
