# Generated by Django 6.0.3 on 2026-05-25 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_n8_t13_vat_statement'),
        ('tenants', '0003_n0_tenant_settings_and_books'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vatstatement',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_from', 'period_to'), name='unique_vat_statement_period'),
        ),
    ]
