# Generated by Django 6.0.3 on 2026-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_vatstatement_unique_vat_statement_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='allow_negative_stock_default',
            field=models.BooleanField(db_column='AllowNegativeStockDefault', default=True, help_text='السماح ببيع المخزون بالسالب افتراضياً (يمكن تجاوزه على مستوى الصنف)'),
        ),
    ]
