# Generated by Django 6.0.3 on 2026-06-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_salessettings_allow_negative_stock_default'),
        ('tenants', '0007_branch_alter_tenantbook_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='BranchID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='tenants.branch'),
        ),
    ]
