# Generated by Django 6.0.3 on 2026-06-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stockmovement_reference_type_warehouse_and_more'),
        ('partners', '0006_n9_t8_partner_row_color'),
        ('sales', '0017_salesinvoice_branch'),
        ('tenants', '0009_operational_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductQuote',
            fields=[
                ('id', models.AutoField(db_column='CustomerProductQuoteID', primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, help_text='سعر العرض اليدوي للوحدة (بعملة الشركة الأساسية)', max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('currency', models.ForeignKey(blank=True, db_column='CurrencyID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_product_quotes', to='tenants.currency')),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, related_name='product_quotes', to='partners.partner')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotes', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_customer_product_quotes',
                'managed': True,
                'indexes': [models.Index(fields=['tenant', 'customer'], name='sales_modul_TenantI_d807df_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer', 'product'), name='uniq_customer_product_quote')],
            },
        ),
    ]
