# Generated by Django 6.0.3 on 2026-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_customerproductquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='warn_on_duplicate_item',
            field=models.BooleanField(db_column='WarnOnDuplicateItem', default=True, help_text='عند تكرار المادة في الفاتورة: إظهار رسالة تنبيه وتأكيد'),
        ),
    ]
