# Generated by Django 6.0.1 on 2026-07-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_salessettings_block_loss_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='use_moving_average_cost',
            field=models.BooleanField(db_column='UseMovingAverageCost', default=False, help_text='مفعّل = متوسط مرجّح متحرك (تكلفة لحظة البيع، مثل الأنظمة الاحترافية)؛ معطّل = متوسط كل فواتير الشراء (النموذج الدوري)'),
        ),
    ]
