# Generated by Django 6.0.1 on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0057_shipment_freight_accrual'),
        ('sales', '0021_salessettings_use_moving_average_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, db_column='PurchaseInvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='logistics.purchaseinvoice'),
        ),
    ]
