# Generated by Django 6.0.3 on 2026-07-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_supplierpayment_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='auto_post_payments',
            field=models.BooleanField(db_column='AutoPostPayments', default=True, help_text='ترحيل تلقائي لسندات القبض والصرف بعد الحفظ'),
        ),
    ]
