# Generated by Django 6.0.3 on 2026-07-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0057_shipment_freight_accrual'),
        ('sales', '0023_salessettings_auto_post_payments'),
        ('tenants', '0013_whatsappcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.AutoField(db_column='SupplierPaymentAllocationID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('amount_in_invoice_currency', models.DecimalField(blank=True, db_column='AmountInInvoiceCurrency', decimal_places=2, help_text='المبلغ محوّلاً لعملة الفاتورة. إذا كانت عملة السند = عملة الفاتورة يساوي amount.', max_digits=18, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, db_column='ConversionRate', decimal_places=6, help_text='سعر الصرف المستخدم لتحويل مبلغ السند لعملة الفاتورة', max_digits=18, null=True)),
                ('invoice', models.ForeignKey(db_column='PurchaseInvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='logistics.purchaseinvoice')),
                ('payment', models.ForeignKey(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.supplierpayment')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_supplier_payment_allocations',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('payment', 'invoice'), name='uniq_supplier_payment_invoice_allocation')],
            },
        ),
    ]
