# Generated by Django 6.0.3 on 2026-07-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_supplierpaymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='dormant_customer_days',
            field=models.PositiveIntegerField(db_column='DormantCustomerDays', default=30, help_text='عدد أيام توقّف العميل عن الشراء قبل إطلاق إشعار «عميل مختفٍ» (0 = تعطيل)'),
        ),
    ]
