# Generated by Django 6.0.3 on 2026-07-26 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_cheque_bank_snapshot'),
        ('inventory', '0012_product_variant_group'),
        ('partners', '0008_partnerbankaccount_defaults'),
        ('sales', '0025_salessettings_dormant_customer_days'),
        ('tenants', '0016_tenantsettings_dashboard_month_start_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='allow_document_delete',
            field=models.BooleanField(db_column='AllowDocumentDelete', default=True, help_text='إظهار «حذف» للعروض والطلبيات (الإلغاء متاح دائماً ولا يحذف)'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='order_reserve_days',
            field=models.PositiveIntegerField(db_column='OrderReserveDays', default=7, help_text='أيام حجز الكمية للطلبية المؤكَّدة قبل أن تعود متاحة (0 = بلا حجز)'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='quotation_valid_days',
            field=models.PositiveIntegerField(db_column='QuotationValidDays', default=14, help_text='أيام صلاحية عرض السعر افتراضياً (0 = بلا تاريخ انتهاء)'),
        ),
        migrations.AlterField(
            model_name='salesquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('sent', 'أُرسل'), ('accepted', 'مقبول'), ('converted', 'محوّل'), ('expired', 'منتهي الصلاحية'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], db_column='Status', default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(db_column='SalesOrderID', primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_column='OrderNumber', max_length=50)),
                ('order_date', models.DateField(db_column='OrderDate')),
                ('delivery_date', models.DateField(blank=True, db_column='DeliveryDate', null=True)),
                ('reserved_until', models.DateField(blank=True, db_column='ReservedUntil', help_text='آخر يوم يحجز فيه هذا الطلب الكمية — بعده تعود متاحة تلقائياً', null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكَّدة'), ('converted', 'محوّلة لفاتورة'), ('cancelled', 'ملغاة')], db_column='Status', default='draft', max_length=20)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=18)),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(db_column='DiscountAmount', decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(db_column='GrandTotal', decimal_places=2, default=0, max_digits=18)),
                ('deposit_amount', models.DecimalField(db_column='DepositAmount', decimal_places=2, default=0, help_text='مجموع العربون المقبوض (سندات قبض مرتبطة بالطلبية)', max_digits=18)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('cancel_reason', models.CharField(blank=True, db_column='CancelReason', default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy_UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.PROTECT, to='tenants.currency')),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='partners.partner')),
                ('invoice', models.ForeignKey(blank=True, db_column='InvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_backref', to='sales.salesinvoice')),
                ('quotation', models.ForeignKey(blank=True, db_column='QuotationID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.salesquotation')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_orders',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='sales_order',
            field=models.ForeignKey(blank=True, db_column='SalesOrderID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='sales.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.AutoField(db_column='SalesOrderLineID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=18)),
                ('line_discount', models.DecimalField(db_column='LineDiscount', decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(db_column='LineTotal', decimal_places=2, default=0, max_digits=18)),
                ('order', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='inventory.product')),
                ('tax_rate', models.ForeignKey(blank=True, db_column='TaxRateID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='accounting.taxrate')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_order_lines',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'status', 'order_date'], name='so_tenant_status_date'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'status', 'reserved_until'], name='so_tenant_reserve'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='so_customer'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='uniq_sales_order_number_per_tenant'),
        ),
    ]
