# Generated by Django 6.0.3 on 2026-07-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_variant_group'),
        ('sales', '0026_orders_and_quote_settings'),
        ('tenants', '0016_tenantsettings_dashboard_month_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='delivery_status',
            field=models.CharField(choices=[('not_delivered', 'غير مسلَّمة'), ('partially_delivered', 'مسلَّمة جزئياً'), ('delivered', 'مسلَّمة')], db_column='DeliveryStatus', default='not_delivered', help_text='هل خرجت بنود الفاتورة للعميل فعلياً؟', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='delivered_quantity',
            field=models.DecimalField(db_column='DeliveredQuantity', decimal_places=4, default=0, help_text='الكمية المسلَّمة فعلياً للعميل من هذا البند', max_digits=18),
        ),
        migrations.CreateModel(
            name='DeliveryOrderLine',
            fields=[
                ('id', models.AutoField(db_column='DeliveryOrderLineID', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=4, max_digits=18)),
                ('delivery', models.ForeignKey(db_column='DeliveryOrderID', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliveryorder')),
                ('invoice_line', models.ForeignKey(db_column='SalesInvoiceLineID', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lines', to='sales.salesinvoiceline')),
                ('product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_order_lines', to='inventory.product')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_delivery_order_lines',
                'managed': True,
            },
        ),
    ]
