# Generated by Django 6.0.3 on 2026-07-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_salesinvoice_delivery_status_and_more'),
        ('tenants', '0016_tenantsettings_dashboard_month_start_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='auto_created',
            field=models.BooleanField(db_column='AutoCreated', default=False, help_text='أُنشئت تلقائياً مع ترحيل الفاتورة (خصم المخزون عند الترحيل)'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='BranchID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_date',
            field=models.DateField(blank=True, db_column='DeliveryDate', null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_number',
            field=models.CharField(blank=True, db_column='DeliveryNumber', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='invoice',
            field=models.ForeignKey(db_column='InvoiceID', help_text='الفاتورة المرتبطة — بنود الإرسالية تُختار من بنودها حصراً', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='sales.salesinvoice'),
        ),
    ]
