# Generated by Django 6.0.3 on 2026-07-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_variant_group'),
        ('partners', '0009_customer_note_priority'),
        ('sales', '0028_alter_deliveryorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_ref',
            field=models.CharField(blank=True, db_column='CustomerRef', default='', help_text='رقم/مرجع العميل لهذا التسليم (طلب شراء، إشعار استلام…)', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='partner',
            field=models.ForeignKey(blank=True, db_column='PartnerID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='deliveryorderline',
            name='movement',
            field=models.ForeignKey(blank=True, db_column='MovementID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order_lines', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='allow_edit_delivery',
            field=models.BooleanField(db_column='AllowEditDelivery', default=True, help_text='السماح بتعديل/إلغاء الإرسالية بعد حفظها (يعكس أثرها ويعيد تطبيقه)'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='allow_standalone_delivery',
            field=models.BooleanField(db_column='AllowStandaloneDelivery', default=True, help_text='السماح بإنشاء سند تسليم بلا فاتورة مرتبطة (بضاعة خرجت قبل فوترتها)'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='delivery_doc_label',
            field=models.CharField(db_column='DeliveryDocLabel', default='إرسالية بيع', help_text='اسم مستند التسليم المرتبط بفاتورة كما يظهر في الشاشات والطباعة', max_length=50),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='standalone_delivery_label',
            field=models.CharField(db_column='StandaloneDeliveryLabel', default='سند تسليم', help_text='اسم مستند التسليم بلا فاتورة مرتبطة', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='invoice',
            field=models.ForeignKey(blank=True, db_column='InvoiceID', help_text='الفاتورة المرتبطة — بنود الإرسالية تُختار من بنودها حصراً. فارغة = «سند تسليم» مستقل (بضاعة خرجت بلا فاتورة بعد).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='sales.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='deliveryorderline',
            name='invoice_line',
            field=models.ForeignKey(blank=True, db_column='SalesInvoiceLineID', help_text='سطر الفاتورة المرتبطة — فارغ في سند التسليم المستقل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lines', to='sales.salesinvoiceline'),
        ),
    ]
