# Generated by Django 6.0.3 on 2026-07-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_cheque_bank_snapshot'),
        ('sales', '0029_deliveryorder_customer_ref_deliveryorder_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='journal',
            field=models.ForeignKey(blank=True, db_column='JournalID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='accounting.journalheader'),
        ),
    ]
