# Generated by Django 6.0.3 on 2026-07-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockmovement_reference_type'),
        ('sales', '0030_deliveryorder_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderline',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='WarehouseID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_order_lines', to='inventory.warehouse'),
        ),
    ]
