# Generated by Django 6.0.3 on 2026-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_deliveryorderline_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='block_reserved_stock_sale',
            field=models.BooleanField(db_column='BlockReservedStockSale', default=True, help_text='رفض ترحيل فاتورة تستهلك كمية محجوزة لطلبية زبون آخر'),
        ),
    ]
