# Generated by Django 6.0.3 on 2026-08-11 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_phase5_p0_indexes'),
        ('logistics', '0071_logisticsclearance_idx_clearance_tenant_status_and_more'),
        ('partners', '0014_partner_idx_partner_tenant_type'),
        ('sales', '0034_salesinvoiceline_serials_and_more'),
        ('tenants', '0018_alter_rolepermission_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['tenant', '-payment_date', '-id'], name='idx_cp_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['tenant', 'partner', '-payment_date'], name='idx_cp_tenant_partner_date'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', '-invoice_date', '-id'], name='idx_si_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'branch', '-invoice_date'], name='idx_si_tenant_branch_date'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['tenant', '-payment_date', '-id'], name='idx_sp_tenant_date'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['tenant', 'partner', '-payment_date'], name='idx_sp_tenant_partner_date'),
        ),
    ]
