# Generated by Django 5.1.15 on 2026-08-20 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_cheque_cycle_v2'),
        ('sales', '0035_customerpayment_idx_cp_tenant_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='default_cheques_in_hand_account',
            field=models.ForeignKey(blank=True, db_column='DefaultChequesInHandAccountID', help_text='حساب شيكات في المحفظة (Asset). يستقبل الشيك الوارد المستلَم قبل إيداعه في البنك.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_settings_cheques_in_hand', to='accounting.account'),
        ),
    ]
