# Generated by Django 5.1.15 on 2026-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_salessettings_default_cheques_in_hand_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='customer_note',
            field=models.CharField(blank=True, db_column='CustomerNote', default='', help_text='ملاحظة تُطبع للعميل تحت اسم الصنف في الفاتورة', max_length=500),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='internal_note',
            field=models.CharField(blank=True, db_column='InternalNote', default='', help_text='ملاحظة داخلية للموظف — لا تُطبع للعميل', max_length=500),
        ),
    ]
