# Generated by Django 5.1.15 on 2026-08-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0074_purchaseorder_idx_po_tenant_status_and_more'),
        ('sales', '0037_salesinvoiceline_customer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='auto_settled_invoice',
            field=models.ForeignKey(blank=True, db_column='AutoSettledPurchaseInvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_settlements', to='logistics.purchaseinvoice'),
        ),
    ]
