# Generated by Django 5.1.15 on 2026-08-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_supplierpayment_auto_settled_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_terms_days',
            field=models.PositiveIntegerField(blank=True, db_column='PaymentTermsDays', help_text='مهلة السداد بالأيام من تاريخ الفاتورة (0 = فوراً).', null=True),
        ),
    ]
