# Generated by Django 5.1.15 on 2026-08-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_cheque_document_movements'),
        ('sales', '0039_salesinvoice_payment_terms_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='attached_cash_account',
            field=models.ForeignKey(blank=True, db_column='AttachedCashAccountID', help_text='حساب الصندوق/البنك الذي سيستلم المبلغ النقدي المرفق', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices_attached_cash', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='attached_cash_amount',
            field=models.DecimalField(db_column='AttachedCashAmount', decimal_places=2, default=0, help_text='نيّة دفع نقدي مرفقة بالمسودة — تتجسّد سند قبض عند ترحيل الفاتورة', max_digits=18),
        ),
    ]
