# Generated by Django 5.1.15 on 2026-08-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_alter_salesinvoice_attached_cash_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='customer_note',
            field=models.CharField(blank=True, db_column='CustomerNote', default='', help_text='ملاحظة تُطبع للعميل تحت اسم المنتج في الفاتورة', max_length=500),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='allow_negative_stock_default',
            field=models.BooleanField(db_column='AllowNegativeStockDefault', default=True, help_text='السماح ببيع المخزون بالسالب افتراضياً (يمكن تجاوزه على مستوى المنتج)'),
        ),
    ]
