# Generated by Django 5.1.15 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_alter_salesinvoiceline_customer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='name_snapshot',
            field=models.CharField(blank=True, db_column='NameSnapshot', default='', max_length=255),
        ),
    ]
