# Generated by Django 5.1.15 on 2026-09-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_salesinvoiceline_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='kind',
            field=models.CharField(choices=[('receipt', 'قبض'), ('refund', 'ردّ دفعة')], db_column='Kind', default='receipt', help_text='قبض (عادي) أو ردّ دفعة — يقلب اتجاه القيد ويُبقي المبلغ موجباً.', max_length=20),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='refund_for_invoice',
            field=models.ForeignKey(blank=True, db_column='RefundForInvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_refunds', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='auto_refund_on_sales_return',
            field=models.BooleanField(db_column='AutoRefundOnSalesReturn', default=False, help_text='عند ترحيل مرتجع البيع يُردّ للزبون ما دفعه: الشيكُ الذي ما زال في المحفظة يعود إليه ورقةً، وما وصل الصندوقَ يعود نقداً من الصندوق الافتراضيّ. وما يقابله شيكٌ عند البنك لم يُحصَّل بعدُ لا يُردّ — يبقى رصيداً دائناً للزبون. مطفأً: تُسأل عند كل ترحيل.'),
        ),
    ]
