# Generated by Django 5.1.15 on 2026-09-17 14:42

from django.db import migrations, models
from django.db.models import F


def copy_created_at_into_updated_at(apps, schema_editor):
    """الصفوف القائمة: «آخر تعديل» = لحظة الإنشاء — لا لحظة الهجرة.

    `AddField` لحقل `auto_now` يملأ الصفوف القائمة بلحظة تشغيل الهجرة (عمودٌ
    NOT NULL بقيمةٍ افتراضيّة تُحذف فوراً). هذا يستبدلها بـ`created_at` في
    `UPDATE` واحد لكل جدول، على MySQL وSQLite معاً.
    """
    for model_name in ('CreditDebitNote', 'DeliveryOrder'):
        apps.get_model('sales', model_name).objects.update(updated_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_customerpayment_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdebitnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt'),
        ),
        migrations.RunPython(copy_created_at_into_updated_at, migrations.RunPython.noop),
    ]
