# Generated by Django 6.1.1 on 2026-09-26 13:00

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models

#: مرآة `partners.models.CREDITOR_PARTNER_TYPES` — الهجرة لا تستورد كوداً حيّاً.
CREDITOR_TYPES = ('Supplier', 'FreightForwarder', 'CustomsBroker', 'LocalTransporter', 'Carrier')
#: حقل الربط ← حقل الهدف في `LogisticsAccrualAllocation`.
ACCRUAL_LINKS = (
    ('related_clearance_id', 'clearance_id'),
    ('related_shipment_id', 'shipment_id'),
    ('related_local_shipment_id', 'local_shipment_id'),
)


def backfill_linked_debit_notes(apps, schema_editor):
    """الإشعار المدين المرحّل المربوط بمستند دائنٍ كان يُطفئه بكامل مبلغه (قراءةً من الربط)؛
    صار الإطفاء توزيعاً — فيُنشأ له توزيعٌ بالمبلغ نفسه، فلا يتغيّر متبقٍّ على أيّ مستند."""
    Note = apps.get_model('sales', 'CreditDebitNote')
    NoteAllocation = apps.get_model('sales', 'CreditDebitNoteAllocation')
    AccrualAllocation = apps.get_model('logistics', 'LogisticsAccrualAllocation')
    notes = Note.objects.filter(
        status='posted', note_type='debit', partner__partner_type__in=CREDITOR_TYPES,
    )
    for note in notes.iterator():
        amount = Decimal(str(note.amount))
        base = (amount * Decimal(str(note.exchange_rate or 1))).quantize(Decimal('0.01'))
        if note.related_purchase_invoice_id:
            NoteAllocation.objects.create(
                tenant_id=note.tenant_id, note_id=note.pk, purchase_invoice_id=note.related_purchase_invoice_id,
                amount=amount, amount_in_invoice_currency=amount, amount_base=base,
            )
            continue
        for link, target in ACCRUAL_LINKS:
            doc_id = getattr(note, link)
            if doc_id:
                AccrualAllocation.objects.create(
                    tenant_id=note.tenant_id, note_id=note.pk, **{target: doc_id},
                    amount=amount, amount_base=base,
                )
                break


def drop_note_accrual_allocations(apps, schema_editor):
    # الرجوع يعيد `payment` إلزامياً — صفوف الإشعارات تُحذف قبله.
    apps.get_model('logistics', 'LogisticsAccrualAllocation').objects.filter(note__isnull=False).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0096_note_allocations'),
        ('sales', '0045_credit_debit_note_any_partner'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDebitNoteAllocation',
            fields=[
                ('id', models.AutoField(db_column='NoteAllocationID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, help_text='بعملة الإشعار', max_digits=18)),
                ('amount_in_invoice_currency', models.DecimalField(db_column='AmountInInvoiceCurrency', decimal_places=2, help_text='ما يُطرح من متبقّي الفاتورة — يساوي `amount` حين تتطابق العملتان', max_digits=18)),
                ('amount_base', models.DecimalField(db_column='AmountBase', decimal_places=2, help_text='بالعملة الأساسية = المبلغ × سعر صرف الإشعار — لكشف الحساب', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('note', models.ForeignKey(db_column='CreditDebitNoteID', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.creditdebitnote')),
                ('purchase_invoice', models.ForeignKey(blank=True, db_column='PurchaseInvoiceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_allocations', to='logistics.purchaseinvoice')),
                ('sales_invoice', models.ForeignKey(blank=True, db_column='SalesInvoiceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_allocations', to='sales.salesinvoice')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_credit_debit_note_allocations',
                'indexes': [models.Index(fields=['tenant', 'note'], name='note_alloc_tenant_note_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('purchase_invoice__isnull', True), ('sales_invoice__isnull', False)), models.Q(('purchase_invoice__isnull', False), ('sales_invoice__isnull', True)), _connector='OR'), name='note_allocation_one_target')],
            },
        ),
        migrations.RunPython(backfill_linked_debit_notes, drop_note_accrual_allocations),
    ]
