# Generated by Django 6.1.1 on 2026-09-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_note_allocations'),
        ('tenants', '0035_grant_import_procurement_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRefundAllocation',
            fields=[
                ('id', models.AutoField(db_column='RefundAllocationID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, help_text='بعملة السند والمصدر', max_digits=18)),
                ('amount_base', models.DecimalField(db_column='AmountBase', decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('refund', models.ForeignKey(db_column='RefundPaymentID', on_delete=django.db.models.deletion.CASCADE, related_name='refund_sources', to='sales.customerpayment')),
                ('source_customer_payment', models.ForeignKey(blank=True, db_column='SourceCustomerPaymentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.customerpayment')),
                ('source_note', models.ForeignKey(blank=True, db_column='SourceNoteID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.creditdebitnote')),
                ('source_supplier_payment', models.ForeignKey(blank=True, db_column='SourceSupplierPaymentID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.supplierpayment')),
                ('tenant', models.ForeignKey(db_column='TenantID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'sales_module_party_refund_allocations',
                'indexes': [models.Index(fields=['tenant', 'refund'], name='refund_alloc_tenant_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source_customer_payment__isnull', True), ('source_note__isnull', False), ('source_supplier_payment__isnull', True)), models.Q(('source_customer_payment__isnull', True), ('source_note__isnull', True), ('source_supplier_payment__isnull', False)), models.Q(('source_customer_payment__isnull', False), ('source_note__isnull', True), ('source_supplier_payment__isnull', True)), _connector='OR'), name='refund_allocation_one_source')],
            },
        ),
    ]
