# Generated by Django 6.1.1 on 2026-10-08 18:27

from django.db import migrations, models


def booleans_to_policies(apps, schema_editor):
    """المنطقيَّان القديمان → السياستان، بلا تغيّر في سلوك أي شركة.

    الحقلان الجديدان يولدان `allow`، فيكفي تحويل الحالة غير الافتراضية فقط:
    السالب كان «ممنوعاً» (False) ⇒ `block`، والخسارة كانت «ممنوعة» (True) ⇒ `block`.
    """
    SalesSettings = apps.get_model('sales', 'SalesSettings')
    SalesSettings.objects.filter(allow_negative_stock_default=False).update(
        negative_stock_policy='block')
    SalesSettings.objects.filter(block_loss_invoices=True).update(
        loss_invoice_policy='block')


def policies_to_booleans(apps, schema_editor):
    """الرجوع: الحقلان القديمان يعودان بافتراضيَّيهما (True / False) ثم يُضبطان.

    `save_only` لا مقابل له في المنطقيّ القديم فيُعامَل منعاً (الأكثر تحفّظاً).
    """
    SalesSettings = apps.get_model('sales', 'SalesSettings')
    SalesSettings.objects.exclude(negative_stock_policy='allow').update(
        allow_negative_stock_default=False)
    SalesSettings.objects.exclude(loss_invoice_policy='allow').update(
        block_loss_invoices=True)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_supplierpayment_split_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='loss_invoice_policy',
            field=models.CharField(choices=[('allow', 'السماح (تحذير فقط)'), ('save_only', 'السماح بالحفظ كمسودة ومنع الترحيل'), ('block', 'منع الحفظ والترحيل')], db_column='LossInvoicePolicy', default='allow', help_text='فاتورة بيع فيها سعر أقل من التكلفة: السماح (تحذير فقط) | الحفظ كمسودة ومنع الترحيل | منع الحفظ والترحيل.', max_length=12),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='negative_stock_policy',
            field=models.CharField(choices=[('allow', 'السماح (تحذير فقط)'), ('save_only', 'السماح بالحفظ كمسودة ومنع الترحيل'), ('block', 'منع الحفظ والترحيل')], db_column='NegativeStockPolicy', default='allow', help_text='بيع كمية تتجاوز المتوفر: السماح (تحذير فقط) | الحفظ كمسودة ومنع الترحيل | منع الحفظ والترحيل. المسودة لا تحرّك مخزوناً.', max_length=12),
        ),
        migrations.RunPython(booleans_to_policies, policies_to_booleans),
        migrations.RemoveField(
            model_name='salessettings',
            name='allow_negative_stock_default',
        ),
        migrations.RemoveField(
            model_name='salessettings',
            name='block_loss_invoices',
        ),
    ]
